In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/corpus/positive_pairs.json

# Phase 0A — CSN Judge Calibration (RQ3)


*Compares Llama-8B/ Qwen-3.5B / Qwen-coder-7B against CodeSearchNet human judgements.Metrics: Quadratic Weighted Kappa (QWK) + Kendall-τ*

In [2]:
!pip install -q python-terrier pyterrier-dr datasets ir_datasets scipy scikit-learn accelerate groq

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 60.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.8/208.8 kB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 78.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 25.7 MB/s eta 0:00:00
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Building wheel for cbor (setup.py) ... done

In [3]:
import os, json, gc, re, requests
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import torch
from scipy.stats import kendalltau
from sklearn.metrics import cohen_kappa_score
import pyterrier as pt
import pyterrier_dr
pd.set_option('display.max_colwidth', 200)
print('PyTerrier:', pt.__version__)
print('CUDA:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

2026-04-01 15:32:41.920205: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775057562.135473      54 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775057562.199559      54 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775057562.712138      54 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775057562.712181      54 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775057562.712184      54 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775057562.712186      54 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

PyTerrier: 1.0.4
CUDA: True
GPU: Tesla T4

#### only taking the python codes from CSN to evalute

In [4]:
import ir_datasets
import pandas as pd

# 1. Load the dataset
dataset = ir_datasets.load("codesearchnet/challenge")

# 2. Extract Queries into a DataFrame
queries_df = pd.DataFrame(
    [{"query_id": q.query_id, "query_text": q.text} for q in dataset.queries_iter()]
)

# 3. Extract Qrels into a DataFrame
qrels_df = pd.DataFrame(
    [{"query_id": q.query_id, "doc_id": q.doc_id, "relevance": q.relevance} for q in dataset.qrels_iter()]
)

# 4. Extract Documents into a DataFrame (Filtering for Python ONLY)
python_docs = []
for doc in dataset.docs_iter():
    if doc.language == 'python':
        python_docs.append({
            "doc_id": doc.doc_id,
            "code": doc.code,               # The actual python code
            "repo": doc.repo,               # The github repository name (like 'huggingface/transformers')
            "path": doc.path,               # The file path in the repository
            "func_name": doc.func_name      # The exact function name 
        })
        
docs_df = pd.DataFrame(python_docs)

# 5. Merge everything together
merged_df = pd.merge(qrels_df, queries_df, on="query_id", how="inner")
documents_csn= pd.merge(merged_df, docs_df, on="doc_id", how="inner")

print(f"Total Python Relevance Judgements found: {len(documents_csn)}")

[INFO] [starting] https://raw.githubusercontent.com/github/CodeSearchNet/master/resources/queries.csv
[INFO] [finished] https://raw.githubusercontent.com/github/CodeSearchNet/master/resources/queries.csv: [00:00] [2.49kB] [4.43MB/s]
[INFO] [starting] https://raw.githubusercontent.com/github/CodeSearchNet/master/resources/annotationStore.csv
[INFO] [finished] https://raw.githubusercontent.com/github/CodeSearchNet/master/resources/annotationStore.csv: [00:00] [678kB] [25.5MB/s]
[INFO] If you have a local copy of https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/python.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/07b49dd01fbac894fbdae22da6462e4f
[INFO] [starting] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/python.zip
[INFO] [finished] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/python.zip: [00:04] [941MB] [203MB/s]
[INFO] If you have a local copy of https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/java.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/fea180077275d8f98f42a3386f492837
[INFO] [starting] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/java.zip
[INFO] [finished] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/java.zip: [00:05] [1.06GB] [189MB/s]
[INFO] If you have a local copy of https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/go.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/c0288db91f067c95bb952577949e7b13
[INFO] [starting] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/go.zip
[INFO] [finished] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/go.zip: [00:02] [488MB] [180MB/s]
[INFO] If you have a local copy of https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/php.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/62373f85cfae2f5d7422dc1e55fbbb50
[INFO] [starting] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/php.zip
[INFO] [finished] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/php.zip: [00:04] [852MB] [191MB/s]
[INFO] If you have a local copy of https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/ruby.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/6847c0149666334cc937909b0e2297ae
[INFO] [starting] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/ruby.zip
[INFO] [finished] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/ruby.zip: [00:00] [112MB] [171MB/s]
[INFO] If you have a local copy of https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/javascript.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/7649178a02f7b5c8fbccb64abe7946b6
[INFO] [starting] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/javascript.zip
[INFO] [finished] https://huggingface.co/datasets/macavaney/codesearchnet-mirror/resolve/main/v2/javascript.zip: [00:09] [1.66GB] [183MB/s]

Total Python Relevance Judgements found: 1109

In [5]:
# Basic check
display(documents_csn.head())

,query_id,doc_id,relevance,query_text,code,repo,path,func_name
0,64,https://github.com/JoseAntFer/pyny3d/blob/fb81684935a24f7e50c975cb4383c81a63ab56df/pyny3d/utils.py#L8-L33,2,sorting multiple arrays based on another arrays sorted order,"def sort_numpy(array, col=0, order_back=False):\r\n """"""\r\n Sorts the columns for an entire ``ndarrray`` according to sorting\r\n one of them.\r\n \r\n :param array: Array to sort.\...",JoseAntFer/pyny3d,pyny3d/utils.py,sort_numpy
1,2,https://github.com/keon/algorithms/blob/4d6569464a62a75c1357acc97e2dd32ee2f9f4a3/algorithms/queues/priority_queue.py#L38-L49,3,priority queue,"def push(self, item, priority=None):\n """"""Push the item in the priority queue.\n if priority is not given, priority is set to the value of item.\n """"""\n priority = item...",keon/algorithms,algorithms/queues/priority_queue.py,PriorityQueue.push
2,60,https://github.com/mapbox/mapbox-sdk-py/blob/72d19dbcf2d254a6ea08129a726471fd21f13023/mapbox/services/base.py#L122-L144,3,custom http error response,"def handle_http_error(self, response, custom_messages=None,\n raise_for_status=False):\n """"""Converts service errors to Python exceptions\n\n Parameters\n ...",mapbox/mapbox-sdk-py,mapbox/services/base.py,Service.handle_http_error
3,61,https://github.com/a-tal/nagaram/blob/2edcb0ef8cb569ebd1c398be826472b4831d6110/nagaram/scrabble.py#L136-L184,0,how to determine a string is a valid word,"def valid_scrabble_word(word):\n """"""Checks if the input word could be played with a full bag of tiles.\n\n Returns:\n True or false\n """"""\n\n letters_in_bag = {\n ""a"": 9,...",a-tal/nagaram,nagaram/scrabble.py,valid_scrabble_word
4,80,https://github.com/rkargon/pixelsorter/blob/0775d1e487fbcb023e411e1818ba3290b0e8665e/pixelsorter/util.py#L72-L84,2,randomly extract x items from a list,"def weighted_random_choice(items):\n """"""\n Returns a weighted random choice from a list of items.\n :param items: A list of tuples (object, weight)\n :return: A random object, whose li...",rkargon/pixelsorter,pixelsorter/util.py,weighted_random_choice

In [6]:
documents_csn.to_csv('/kaggle/working/documents_csn.tsv',sep='\t',index=False)

In [7]:
documents_csn=pd.read_csv('/kaggle/working/documents_csn.tsv',sep='\t',index_col=0)

In [8]:
documents_csn

,doc_id,relevance,query_text,code,repo,path,func_name
query_id,,,,,,,
64,https://github.com/JoseAntFer/pyny3d/blob/fb81684935a24f7e50c975cb4383c81a63ab56df/pyny3d/utils.py#L8-L33,2,sorting multiple arrays based on another arrays sorted order,"def sort_numpy(array, col=0, order_back=False):\r\n """"""\r\n Sorts the columns for an entire ``ndarrray`` according to sorting\r\n one of them.\r\n \r\n :param array: Array to sort.\...",JoseAntFer/pyny3d,pyny3d/utils.py,sort_numpy
2,https://github.com/keon/algorithms/blob/4d6569464a62a75c1357acc97e2dd32ee2f9f4a3/algorithms/queues/priority_queue.py#L38-L49,3,priority queue,"def push(self, item, priority=None):\n """"""Push the item in the priority queue.\n if priority is not given, priority is set to the value of item.\n """"""\n priority = item...",keon/algorithms,algorithms/queues/priority_queue.py,PriorityQueue.push
60,https://github.com/mapbox/mapbox-sdk-py/blob/72d19dbcf2d254a6ea08129a726471fd21f13023/mapbox/services/base.py#L122-L144,3,custom http error response,"def handle_http_error(self, response, custom_messages=None,\n raise_for_status=False):\n """"""Converts service errors to Python exceptions\n\n Parameters\n ...",mapbox/mapbox-sdk-py,mapbox/services/base.py,Service.handle_http_error
61,https://github.com/a-tal/nagaram/blob/2edcb0ef8cb569ebd1c398be826472b4831d6110/nagaram/scrabble.py#L136-L184,0,how to determine a string is a valid word,"def valid_scrabble_word(word):\n """"""Checks if the input word could be played with a full bag of tiles.\n\n Returns:\n True or false\n """"""\n\n letters_in_bag = {\n ""a"": 9,...",a-tal/nagaram,nagaram/scrabble.py,valid_scrabble_word
80,https://github.com/rkargon/pixelsorter/blob/0775d1e487fbcb023e411e1818ba3290b0e8665e/pixelsorter/util.py#L72-L84,2,randomly extract x items from a list,"def weighted_random_choice(items):\n """"""\n Returns a weighted random choice from a list of items.\n :param items: A list of tuples (object, weight)\n :return: A random object, whose li...",rkargon/pixelsorter,pixelsorter/util.py,weighted_random_choice
...,...,...,...,...,...,...,...
55,https://github.com/simonw/datasette/blob/11b352b4d52fd02a422776edebb14f12e4994d3b/datasette/app.py#L521-L527,1,how to get database table name,"def table_metadata(self, database, table):\n ""Fetch table-specific metadata.""\n return (self.metadata(""databases"") or {}).get(database, {}).get(\n ""tables"", {}\n )....",simonw/datasette,datasette/app.py,Datasette.table_metadata
39,https://github.com/apple/turicreate/blob/74514c3f99e25b46f22c6e02977fe3da69221c2e/src/external/coremltools_wrap/coremltools/deps/protobuf/python/google/protobuf/descriptor.py#L321-L337,3,get name of enumerated value,"def EnumValueName(self, enum, value):\n """"""Returns the string name of an enum value.\n\n This is just a small helper method to simplify a common operation.\n\n Args:\n enum: string n...",apple/turicreate,src/external/coremltools_wrap/coremltools/deps/protobuf/python/google/protobuf/descriptor.py,Descriptor.EnumValueName
47,https://github.com/nion-software/nionswift/blob/d43693eaf057b8683b9638e575000f055fede452/nion/swift/model/NDataHandler.py#L469-L481,1,read properties file,"def read_properties(self):\n """"""\n Read properties from the ndata file reference\n\n :param reference: the reference from which to read\n :return: a tuple o...",nion-software/nionswift,nion/swift/model/NDataHandler.py,NDataHandler.read_properties
8,https://github.com/materialsproject/pymatgen/blob/4ca558cf72f8d5f8a1f21dfdfc0181a971c186da/pymatgen/io/abinit/flows.py#L254-L266,2,set working directory,"def set_workdir(self, workdir, chroot=False):\n """"""\n Set the working directory. Cannot be set more than once unless chroot is True\n """"""\n if not chroot and hasattr(se...",materialsproject/pymatgen,pymatgen/io/abinit/flows.py,Flow.set_workdir
10,https://github.com/tisimst/mcerp/blob/2bb8260c9ad2d58a806847f1b627b6451e407de1/mcerp/__init__.py#L1150-L1167,3,binomial distribution,"def Binomial(n, p, tag=None):\n """"""\n A Binomial random variate\n \n Parameters\n ----------\n n : int\n The number of trials\n p : scalar\n The probability of s...",tisimst/mcerp,mcerp/__init__.py,Binomial

In [9]:
# 1. Move query_id from the Index back into a regular column
documents_csn = documents_csn.reset_index()
# 2. Now your rename will work perfectly
documents_csn = documents_csn.rename(columns={
    'query_id': 'qid',
    'doc_id': 'docno',
    'query_text': 'query',
    'relevance':  'human_relevance',
})

In [10]:
documents_csn['qid']   = documents_csn['qid'].astype(str)
documents_csn['docno'] = documents_csn['docno'].astype(str)

In [11]:
documents_csn = documents_csn.dropna(subset=['code'])
print(f'Total human-judged pairs: {len(documents_csn)}')
print('Relevance distribution:')
print(documents_csn['human_relevance'].value_counts().sort_index())

Total human-judged pairs: 1109
Relevance distribution:
human_relevance
0    244
1    291
2    274
3    300
Name: count, dtype: int64

In [12]:
documents_csn

,qid,docno,human_relevance,query,code,repo,path,func_name
0,64,https://github.com/JoseAntFer/pyny3d/blob/fb81684935a24f7e50c975cb4383c81a63ab56df/pyny3d/utils.py#L8-L33,2,sorting multiple arrays based on another arrays sorted order,"def sort_numpy(array, col=0, order_back=False):\r\n """"""\r\n Sorts the columns for an entire ``ndarrray`` according to sorting\r\n one of them.\r\n \r\n :param array: Array to sort.\...",JoseAntFer/pyny3d,pyny3d/utils.py,sort_numpy
1,2,https://github.com/keon/algorithms/blob/4d6569464a62a75c1357acc97e2dd32ee2f9f4a3/algorithms/queues/priority_queue.py#L38-L49,3,priority queue,"def push(self, item, priority=None):\n """"""Push the item in the priority queue.\n if priority is not given, priority is set to the value of item.\n """"""\n priority = item...",keon/algorithms,algorithms/queues/priority_queue.py,PriorityQueue.push
2,60,https://github.com/mapbox/mapbox-sdk-py/blob/72d19dbcf2d254a6ea08129a726471fd21f13023/mapbox/services/base.py#L122-L144,3,custom http error response,"def handle_http_error(self, response, custom_messages=None,\n raise_for_status=False):\n """"""Converts service errors to Python exceptions\n\n Parameters\n ...",mapbox/mapbox-sdk-py,mapbox/services/base.py,Service.handle_http_error
3,61,https://github.com/a-tal/nagaram/blob/2edcb0ef8cb569ebd1c398be826472b4831d6110/nagaram/scrabble.py#L136-L184,0,how to determine a string is a valid word,"def valid_scrabble_word(word):\n """"""Checks if the input word could be played with a full bag of tiles.\n\n Returns:\n True or false\n """"""\n\n letters_in_bag = {\n ""a"": 9,...",a-tal/nagaram,nagaram/scrabble.py,valid_scrabble_word
4,80,https://github.com/rkargon/pixelsorter/blob/0775d1e487fbcb023e411e1818ba3290b0e8665e/pixelsorter/util.py#L72-L84,2,randomly extract x items from a list,"def weighted_random_choice(items):\n """"""\n Returns a weighted random choice from a list of items.\n :param items: A list of tuples (object, weight)\n :return: A random object, whose li...",rkargon/pixelsorter,pixelsorter/util.py,weighted_random_choice
...,...,...,...,...,...,...,...,...
1104,55,https://github.com/simonw/datasette/blob/11b352b4d52fd02a422776edebb14f12e4994d3b/datasette/app.py#L521-L527,1,how to get database table name,"def table_metadata(self, database, table):\n ""Fetch table-specific metadata.""\n return (self.metadata(""databases"") or {}).get(database, {}).get(\n ""tables"", {}\n )....",simonw/datasette,datasette/app.py,Datasette.table_metadata
1105,39,https://github.com/apple/turicreate/blob/74514c3f99e25b46f22c6e02977fe3da69221c2e/src/external/coremltools_wrap/coremltools/deps/protobuf/python/google/protobuf/descriptor.py#L321-L337,3,get name of enumerated value,"def EnumValueName(self, enum, value):\n """"""Returns the string name of an enum value.\n\n This is just a small helper method to simplify a common operation.\n\n Args:\n enum: string n...",apple/turicreate,src/external/coremltools_wrap/coremltools/deps/protobuf/python/google/protobuf/descriptor.py,Descriptor.EnumValueName
1106,47,https://github.com/nion-software/nionswift/blob/d43693eaf057b8683b9638e575000f055fede452/nion/swift/model/NDataHandler.py#L469-L481,1,read properties file,"def read_properties(self):\n """"""\n Read properties from the ndata file reference\n\n :param reference: the reference from which to read\n :return: a tuple o...",nion-software/nionswift,nion/swift/model/NDataHandler.py,NDataHandler.read_properties
1107,8,https://github.com/materialsproject/pymatgen/blob/4ca558cf72f8d5f8a1f21dfdfc0181a971c186da/pymatgen/io/abinit/flows.py#L254-L266,2,set working directory,"def set_workdir(self, workdir, chroot=False):\n """"""\n Set the working directory. Cannot be set more than once unless chroot is True\n """"""\n if not chroot and hasattr(se...",materialsproject/pymatgen,pymatgen/io/abinit/flows.py,Flow.set_workdir
1108,10,https://github.com/tisimst/mcerp/blob/2bb8260c9ad2d58a806847f1b627b6451e407de1/mcerp/__init__.py#L1150-L1167,3,binomial distribution,"def Binomial(n, p, tag=None):\n """"""\n A Binomial random variate\n \n Parameters\n ----------\n n : int\n The number of trials\n p : scalar\n The probability of s...",tisimst/mcerp,mcerp/__init__.py,Binomial

In [13]:
# No sampling needed — use everything
calibration_df = documents_csn.copy()

calibration_df.to_csv('/kaggle/working/calibration_pool.csv', index=False)
print(f'Calibration pool: {len(calibration_df)} pairs')
print(calibration_df['human_relevance'].value_counts().sort_index())

Calibration pool: 1109 pairs
human_relevance
0    244
1    291
2    274
3    300
Name: count, dtype: int64

In [14]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

RELEVANCE_PROMPT = '''\
You are an expert code relevance assessor for information retrieval research.

Task: Rate the relevance of a code snippet to a natural language query on a scale of 0-3.

Relevance Scale:
- 0: Not relevant - The code has no relation to the query
- 1: Marginally relevant - The code is tangentially related but does not answer the query
- 2: Relevant - The code addresses the query or provides related functionality
- 3: Highly relevant - The code directly and completely answers the query

Query: {query}

Code Snippet:
{code}

Instructions:
1. Analyze the semantic relationship between the query and code
2. Consider functionality, intent, and implementation details
3. Provide ONLY a single digit (0, 1, 2, or 3) as your response

Relevance Score:'''

## Utility functions

In [32]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm.auto import tqdm
import time
import os, re, time

def load_llm(model_name):
    print(f'Loading {model_name}...')
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token    = tokenizer.eos_token
    tokenizer.padding_side = 'left'
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float16,
        device_map='auto',
    )
    print('  Loaded.')
    return tokenizer, model



def judge_batch(queries, codes, tokenizer, model, batch_size=8):
    '''Returns list of int scores 0-3 for each (query, code) pair.'''
    results = []
    batches = range(0, len(queries), batch_size)
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    for i in tqdm(batches, desc="Judging", unit="batch"):
        bq = queries[i:i+batch_size]
        bc = codes[i:i+batch_size]
        prompts = [RELEVANCE_PROMPT.format(query=q, code=c[:1000])
                   for q, c in zip(bq, bc)]
        inputs = tokenizer(
            prompts, return_tensors='pt', padding=True,
            truncation=True, max_length=2048, return_attention_mask=True
        )
        inputs = {k: v.to(device) for k, v in inputs.items()}
        with torch.no_grad():
            out = model.generate(
                input_ids=inputs['input_ids'],
                attention_mask=inputs['attention_mask'],
                max_new_tokens=5, do_sample=False,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id
            )
        for j, o in enumerate(out):
            gen = tokenizer.decode(
                o[inputs['input_ids'][j].shape[0]:],
                skip_special_tokens=True
            ).strip()
            try:
                score = int(gen[0])
                if score not in [0, 1, 2, 3]: score = 0
            except:
                score = 0
            results.append(score)
    return results

In [16]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()

HF_TOKEN=user_secrets.get_secret("HF_TOKEN")

In [17]:
from huggingface_hub import login
import os


login(token=HF_TOKEN)

In [36]:
# ── Judge with Llama-3.1-8B-Instruct ──
tok8b, mdl8b = load_llm('meta-llama/Llama-3.1-8B-Instruct')
calibration_df = pd.read_csv('/kaggle/working/calibration_pool.csv')
calibration_df['llama8b'] = judge_batch(
    calibration_df['query'].tolist(),
    calibration_df['code'].tolist(),
    tok8b, mdl8b, batch_size=16
)
calibration_df.to_csv('/kaggle/working/calibration_llama8b.csv', index=False)
print('Llama-8B done.')
print(calibration_df['llama8b'].value_counts().sort_index())

#=---- cleanup memory
mdl8b= None
tok8b= None
gc.collect()
for i in range(torch.cuda.device_count()):
    with torch.cuda.device(i):
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()
for i in range(torch.cuda.device_count()):
    print(f"GPU {i} → {torch.cuda.memory_allocated(i)/1e9:.2f} GB")

Loading meta-llama/Llama-3.1-8B-Instruct...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

  Loaded.

Judging:   0%|          | 0/70 [00:00<?, ?batch/s]

Llama-8B done.
llama8b
0    235
1     21
2    379
3    474
Name: count, dtype: int64
GPU 0 → 0.01 GB
GPU 1 → 0.01 GB

In [39]:
# ── Judge with Qwen2.5-3B-Instruct ──
tok_qwen, mdl_qwen = load_llm('Qwen/Qwen2.5-3B-Instruct')
calibration_df = pd.read_csv('/kaggle/working/calibration_llama8b.csv')
calibration_df['qwen3b'] = judge_batch(
    calibration_df['query'].tolist(),
    calibration_df['code'].tolist(),
    tok_qwen, mdl_qwen, batch_size=16
)
calibration_df.to_csv('/kaggle/working/calibration_qwen3b.csv', index=False)
print('Qwen-3B done.')
print(calibration_df['qwen3b'].value_counts().sort_index())

## clear loaded model
mdl_qwen= None
tok_qwen = None
gc.collect()
for i in range(torch.cuda.device_count()):
    with torch.cuda.device(i):
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()
for i in range(torch.cuda.device_count()):
    print(f"GPU {i} → {torch.cuda.memory_allocated(i)/1e9:.2f} GB")

Loading Qwen/Qwen2.5-3B-Instruct...

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

  Loaded.

Judging:   0%|          | 0/70 [00:00<?, ?batch/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Qwen-3B done.
qwen3b
0    122
1    352
2    625
3     10
Name: count, dtype: int64
GPU 0 → 0.01 GB
GPU 1 → 0.01 GB

In [40]:
tok_coder, mdl_coder = load_llm('Qwen/Qwen2.5-Coder-7B-Instruct')
calibration_df = pd.read_csv('/kaggle/working/calibration_qwen3b.csv')
calibration_df['qwen_coder7b'] = judge_batch(
    calibration_df['query'].tolist(),
    calibration_df['code'].tolist(),
    tok_coder, mdl_coder,
    batch_size=16    # fits easily on 2×T4
)
calibration_df.to_csv('/kaggle/working/calibration_all_models.csv', index=False)
print(calibration_df['qwen_coder7b'].value_counts().sort_index())
## clear loaded model
mdl_coder = None
tok_coder = None
gc.collect()
for i in range(torch.cuda.device_count()):
    with torch.cuda.device(i):
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()
for i in range(torch.cuda.device_count()):
    print(f"GPU {i} → {torch.cuda.memory_allocated(i)/1e9:.2f} GB")

Loading Qwen/Qwen2.5-Coder-7B-Instruct...

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.33G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.88G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

  Loaded.

Judging:   0%|          | 0/70 [00:00<?, ?batch/s]

qwen_coder7b done.
qwen_coder7b
0    608
1      4
2    327
3    170
Name: count, dtype: int64
GPU 0 → 0.01 GB
GPU 1 → 0.01 GB

In [41]:
# CSN Calibration Metrics: Quadratic Weighted Kappa + Kendall-tau
calibration_df = pd.read_csv('/kaggle/working/calibration_all_models.csv')
human_scores   = calibration_df['human_relevance'].tolist()

model_cols = ['llama8b', 'qwen3b', 'qwen_coder7b']
rows = []
for m in model_cols:
    llm_scores = calibration_df[m].tolist()
    qwk = cohen_kappa_score(human_scores, llm_scores, weights='quadratic')
    kt  = kendalltau(human_scores, llm_scores).statistic
    rows.append({'model': m, 'QWK': round(qwk, 4), 'Kendall_tau': round(kt, 4)})

calibration_result = pd.DataFrame(rows).sort_values('QWK', ascending=False)
print('=== CSN Calibration Results ===')
display(calibration_result)

=== CSN Calibration Results ===

          model     QWK  Kendall_tau
2  qwen_coder7b  0.4369       0.4254
0       llama8b  0.4008       0.3957
1        qwen3b  0.3275       0.3312

# Phase 0B — CoSQA Binary Calibration
Binary human labels (0/1) vs LLM scores (0–3).  
**Cohen's κ** (binary): binarize LLM ≥ 2 → 1  
**Kendall-τ**: rank correlation between raw LLM 0-3 and binary 0/1 label (valid — τ is rank-based)

In [42]:
# Download CoSQA (200 pairs: 100 positive + 100 negative)
cosqa_url ='https://raw.githubusercontent.com/Jun-jie-Huang/CoCLR/refs/heads/main/data/qa/cosqa-all.json'
resp = requests.get(cosqa_url, timeout=60)
cosqa_raw = resp.json()
cosqa_full = pd.DataFrame(cosqa_raw).rename(columns={'doc': 'query', 'label': 'cosqa_label'})
print(f'CoSQA total: {len(cosqa_full)}')
print(cosqa_full['cosqa_label'].value_counts())

CoSQA total: 20604
cosqa_label
0    10584
1    10020
Name: count, dtype: int64

In [43]:
cosqa_full

,idx,query,code,code_tokens,docstring_tokens,cosqa_label
0,cosqa-train-18103,python remove all empty items in list,"def remove_empty_text(utterances: List[Utterance]) -> List[Utterance]:\n """"""Remove empty utterances from a list of utterances\n Args:\n utterances: The list of utterance we are proces...","def remove_empty_text ( utterances : List [ Utterance ] ) -> List [ Utterance ] : return [ utter for utter in utterances if utter . text . strip ( ) != """" ]",Remove empty utterances from a list of utterances Args : utterances : The list of utterance we are processing,0
1,cosqa-train-11841,python return property objectno not value,"def value(self):\n """"""Value of property.""""""\n if self._prop.fget is None:\n raise AttributeError('Unable to read attribute')\n return self._prop.fget(self._obj)",def value ( self ) : if self . _prop . fget is None : raise AttributeError ( 'Unable to read attribute' ) return self . _prop . fget ( self . _obj ),Value of property .,1
2,cosqa-train-3015,python not null dict,"def purge_dict(idict):\n """"""Remove null items from a dictionary """"""\n odict = {}\n for key, val in idict.items():\n if is_null(val):\n continue\n odict[key] = val...","def purge_dict ( idict ) : odict = { } for key , val in idict . items ( ) : if is_null ( val ) : continue odict [ key ] = val return odict",Remove null items from a dictionary,0
3,cosqa-train-5561,how to turn of traceback in python,"def format_exception(e):\n """"""Returns a string containing the type and text of the exception.\n\n """"""\n from .utils.printing import fill\n return '\n'.join(fill(line) for line in trace...","def format_exception ( e ) : from . utils . printing import fill return '\n' . join ( fill ( line ) for line in traceback . format_exception_only ( type ( e ) , e ) )",Returns a string containing the type and text of the exception .,0
4,cosqa-train-9028,generate list of fixed size python,"def batch(items, size):\n """"""Batches a list into a list of lists, with sub-lists sized by a specified\n batch size.""""""\n return [items[x:x + size] for x in xrange(0, len(items), size)]","def batch ( items , size ) : return [ items [ x : x + size ] for x in xrange ( 0 , len ( items ) , size ) ]",Batches a list into a list of lists with sub - lists sized by a specified batch size .,1
...,...,...,...,...,...,...
20599,cosqa-train-10131,multiple text files word count for each file python,"def count_words(file):\n """""" Counts the word frequences in a list of sentences.\n\n Note:\n This is a helper function for parallel execution of `Vocabulary.from_text`\n method.\n """"""\n c...","def count_words ( file ) : c = Counter ( ) with open ( file , 'r' ) as f : for l in f : words = l . strip ( ) . split ( ) c . update ( words ) return c",Counts the word frequences in a list of sentences .,1
20600,cosqa-train-19367,how to check a file is empty in python,"def _cnx_is_empty(in_file):\n """"""Check if cnr or cns files are empty (only have a header)\n """"""\n with open(in_file) as in_handle:\n for i, line in enumerate(in_handle):\n ...","def _cnx_is_empty ( in_file ) : with open ( in_file ) as in_handle : for i , line in enumerate ( in_handle ) : if i > 0 : return False return True",Check if cnr or cns files are empty ( only have a header ),1
20601,cosqa-dev-344,python rpy2 robjects not found,"def setup_detect_python2():\n """"""\n Call this before using the refactoring tools to create them on demand\n if needed.\n """"""\n if None in [RTs._rt_py2_detect, RT...","def setup_detect_python2 ( ) : if None in [ RTs . _rt_py2_detect , RTs . _rtp_py2_detect ] : RTs . _rt_py2_detect = RefactoringTool ( py2_detect_fixers ) RTs . _rtp_py2_detect = RefactoringTool ( ...",Call this before using the refactoring tools to create them on demand if needed .,0
20602,cosqa-train-4318,ask if a method can see a variable python,"def is_parameter(self):\n """"""Whether this is a function parameter.""""""\n return (isinstance(self.scope, CodeFunction)\n and self in self.scope.parameters)","def is_parameter ( self ) : return ( isinstance ( self . scope , CodeFunction ) and self in self . scope . parameters )",Whether this is a function parameter .,1
20603,cosqa-train-3517,python sshclient to check if directory exists on server,"def exists(self, filepath):\n """"""Determines if the specified file/folder exists, even if it\n is on a remote server.""""""\n if self.is_ssh(filepath):\n self._check_ft...","def exists ( self , filepath ) : if self . is_ssh ( filepath ) : self . _check_ftp ( ) remotepath = self . _get_remote ( filepath ) try : self . ftp . stat ( remotepath ) except IOError as e : if ...",Determines if the specified file / folder exists even if it is on a remote server .,0

In [44]:
cosqa_sample = pd.concat([
    cosqa_full[cosqa_full['cosqa_label'] == 1].sample(100, random_state=42),
    cosqa_full[cosqa_full['cosqa_label'] == 0].sample(100, random_state=42),
]).reset_index(drop=True)
print(f'\nSampled {len(cosqa_sample)} pairs (100 pos + 100 neg)')
cosqa_sample.to_csv('/kaggle/working/cosqa_sample.csv', index=False)

Sampled 200 pairs (100 pos + 100 neg)

In [46]:
# Judge CoSQA with all 3 LLMs (fast — only 200 pairs each)
cosqa_sample = pd.read_csv('/kaggle/working/cosqa_sample.csv')

for model_name, hf_name, use_4bit, col in [
    ('llama8b',  'meta-llama/Llama-3.1-8B-Instruct',  False, 'llama8b_raw'),
    ('qwen3b',   'Qwen/Qwen2.5-3B-Instruct',          False, 'qwen3b_raw'),
    ('qwen_coder7b', 'Qwen/Qwen2.5-Coder-7B-Instruct', True,  'qwen_coder7b_raw'),
]:
    
    tok, mdl = load_llm(hf_name)
    cosqa_sample[col] = judge_batch(
        cosqa_sample['query'].tolist(),
        cosqa_sample['code'].tolist(),
        tok, mdl,
        batch_size=16
    )
    ## unload llm-----
    mdl = None
    tok = None
    gc.collect()
    for i in range(torch.cuda.device_count()):
        with torch.cuda.device(i):
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i} → {torch.cuda.memory_allocated(i)/1e9:.2f} GB")
    cosqa_sample.to_csv('/kaggle/working/cosqa_judged.csv', index=False)
    print(cosqa_sample[col].value_counts().sort_index())

Loading meta-llama/Llama-3.1-8B-Instruct...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

  Loaded.

Judging:   0%|          | 0/13 [00:00<?, ?batch/s]

GPU 0 → 0.01 GB
GPU 1 → 0.01 GB
llama8b_raw
0    20
1     4
2    77
3    99
Name: count, dtype: int64
Loading Qwen/Qwen2.5-3B-Instruct...

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

  Loaded.

Judging:   0%|          | 0/13 [00:00<?, ?batch/s]

GPU 0 → 0.01 GB
GPU 1 → 0.01 GB
qwen3b_raw
0     10
1     47
2    140
3      3
Name: count, dtype: int64
Loading Qwen/Qwen2.5-Coder-7B-Instruct...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

  Loaded.

Judging:   0%|          | 0/13 [00:00<?, ?batch/s]

GPU 0 → 0.01 GB
GPU 1 → 0.01 GB
qwen_coder7b_raw
0    99
1     2
2    72
3    27
Name: count, dtype: int64

In [47]:
# CoSQA Metrics: binary Cohen's κ + Kendall-τ (ordinal vs binary)
cosqa_sample = pd.read_csv('/kaggle/working/cosqa_judged.csv')
human_bin    = cosqa_sample['cosqa_label'].tolist()

def binarize(scores, threshold=2):
    # Justification: 0-3 scale; 2='Relevant' maps to positive (1)
    return [1 if s >= threshold else 0 for s in scores]

cosqa_rows = []
for col, label in [('llama8b_raw','llama8b'),('qwen3b_raw','qwen3b'),('qwen_coder7b_raw','qwen_coder7b')]:
    raw   = cosqa_sample[col].tolist()
    llm_b = binarize(raw)
    kappa = cohen_kappa_score(human_bin, llm_b)
    # Kendall-tau: rank correlation between ordinal LLM scores and binary human labels
    kt    = kendalltau(human_bin, raw).statistic
    cosqa_rows.append({
        'model': label,
        'Binary_Cohen_Kappa': round(kappa, 4),
        'Kendall_tau_ordinal': round(kt, 4)
    })

cosqa_result = pd.DataFrame(cosqa_rows)
print('=== CoSQA Calibration Results ===')
display(cosqa_result)

=== CoSQA Calibration Results ===

          model  Binary_Cohen_Kappa  Kendall_tau_ordinal
0       llama8b               -0.02              -0.0016
1        qwen3b                0.03               0.0280
2  qwen_coder7b               -0.01              -0.0034

In [48]:
# ── Master Judge Selection Table ──
summary = calibration_result.merge(cosqa_result, on='model', how='left')
summary['mean_score'] = summary[['QWK','Kendall_tau','Binary_Cohen_Kappa','Kendall_tau_ordinal']].mean(axis=1)
summary = summary.sort_values('mean_score', ascending=False).reset_index(drop=True)

print('=== FULL CALIBRATION SUMMARY (higher = better judge) ===')
display(summary)

# MODEL_MAP = {
#     'llama8b':  'meta-llama/Llama-3.1-8B-Instruct',
#     'qwen3b':   'Qwen/Qwen2.5-3B-Instruct',
#     'qwen_coder7b': 'Qwen/Qwen2.5-Coder-7B-Instruct',
# }
# BEST_JUDGE       = summary.iloc[0]['model']
# BEST_JUDGE_HF    = MODEL_MAP[BEST_JUDGE]
# BEST_JUDGE_4BIT  = (BEST_JUDGE == 'llama70b')
# print(f'\nBEST JUDGE: {BEST_JUDGE}  →  {BEST_JUDGE_HF}')
# summary.to_csv('/kaggle/working/judge_selection.csv', index=False)

=== FULL CALIBRATION SUMMARY (higher = better judge) ===

,model,QWK,Kendall_tau,Binary_Cohen_Kappa,Kendall_tau_ordinal,mean_score
0,qwen_coder7b,0.4369,0.4254,-0.01,-0.0034,0.212225
1,llama8b,0.4008,0.3957,-0.02,-0.0016,0.193725
2,qwen3b,0.3275,0.3312,0.03,0.0280,0.179175

# Phase 1 — Custom GenAI Corpus (5 repos)
Load `positive_pairs.json`, build corpus (~1000 docs) and 21 topics.

In [49]:
import numpy as np
import pandas as pd

df=pd.read_json('/kaggle/input/corpus/positive_pairs.json')
df.head(10)

,document_id,anchor,positive,framework,source
0,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,How does has_nested_base_model work in Python?,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...,autogen,synthetic_positive_v2
1,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,Explain the has_nested_base_model logic,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...,autogen,synthetic_positive_v2
2,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,Example usage of has_nested_base_model,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...,autogen,synthetic_positive_v2
3,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,Best practices for has_nested_base_model,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...,autogen,synthetic_positive_v2
4,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,How to implement has_nested_base_model?,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...,autogen,synthetic_positive_v2
5,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,Explain the async create_mcp_websocket_connection logic,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server...",autogen,synthetic_positive_v2
6,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,Best practices for async create_mcp_websocket_connection,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server...",autogen,synthetic_positive_v2
7,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,How to implement async create_mcp_websocket_connection?,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server...",autogen,synthetic_positive_v2
8,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,Example usage of async create_mcp_websocket_connection,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server...",autogen,synthetic_positive_v2
9,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,How does async create_mcp_websocket_connection work in Python?,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server...",autogen,synthetic_positive_v2

In [50]:
## drop column
df.drop(['framework','source'], axis=1, inplace=True)

In [51]:
## replace document_id with docid and numeric number for docid instead of string 
df.rename(columns = {'document_id':'docid'}, inplace = True)
df.head(10)

,docid,anchor,positive
0,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,How does has_nested_base_model work in Python?,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
1,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,Explain the has_nested_base_model logic,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
2,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,Example usage of has_nested_base_model,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
3,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,Best practices for has_nested_base_model,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
4,doc_c73087bba37c14c1e003ab940014b8a6d59c2356,How to implement has_nested_base_model?,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
5,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,Explain the async create_mcp_websocket_connection logic,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."
6,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,Best practices for async create_mcp_websocket_connection,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."
7,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,How to implement async create_mcp_websocket_connection?,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."
8,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,Example usage of async create_mcp_websocket_connection,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."
9,doc_492e3d54a077116002387cd2ee7de8581e8c82d7,How does async create_mcp_websocket_connection work in Python?,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."

# Generating Corpus

Main corpus is usually consists of unique query and answers

In [52]:
# Remove duplicates based on docid (keeps first occurrence)
df_unique = df.drop_duplicates(subset=['docid'], keep='first')

In [53]:
# Reset docid to numeric starting from 0
df_unique['docid'] = range(len(df_unique))

/tmp/ipykernel_54/555291703.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unique['docid'] = range(len(df_unique))

In [54]:
# Reset index if needed
df_unique = df_unique.reset_index(drop=True)
df_unique

,docid,anchor,positive
0,0,How does has_nested_base_model work in Python?,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
1,1,Explain the async create_mcp_websocket_connection logic,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."
2,2,Example usage of test_stop_bridge,"def test_stop_bridge(self, bridge):\n """"""Test stopping the bridge""""""\n assert bridge._running is True\n \n bridge.stop()\n \n assert bridge._running is False"
3,3,How does _put work in Python?,"def _put(self, item: T) -> None:\n self._queue.append(item)"
4,4,How to implement DataclassNestedUnionSyntaxNewMessage:\n message: str | int?,class DataclassNestedUnionSyntaxNewMessage:\n message: str | int
...,...,...,...
995,995,How does test_normalize_shell_output_handles_timeout work in Python?,"def test_normalize_shell_output_handles_timeout() -> None:\n entry = {\n ""stdout"": """",\n ""stderr"": """",\n ""outcome"": {""type"": ""timeout""},\n ""provider_data"": {""truncat..."
996,996,Explain the greet logic,"def greet(name: str) -> str:\n return f""Hello, {name}!"""
997,997,How to implement __init__?,def __init__(self):\n self.responses = DummyResponses()
998,998,Best practices for async _get_screenshot_async,"async def _get_screenshot_async(\n cls,\n computer: AsyncComputer,\n tool_call: ResponseComputerToolCall,\n ) -> str:\n action = tool_call.action\n if isinsta..."
999,999,Best practices for main,"def main():\n parser = argparse.ArgumentParser(description=""Translate documentation files"")\n parser.add_argument(\n ""--file"", type=str, help=""Specific file to translate (relative to ..."

In [55]:
## create a corpus with docid and positive(rename to text)
corpus=df_unique[['docid','positive']]
## rename positive to text and docid to docno
corpus.rename(columns = {'positive':'text','docid':'docno'}, inplace = True)
corpus

/tmp/ipykernel_54/4063860936.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corpus.rename(columns = {'positive':'text','docid':'docno'}, inplace = True)

,docno,text
0,0,def has_nested_base_model(cls: type[IsDataclass]) -> bool:\n for f in fields(cls):\n field_type = f.type\n # Resolve forward references and other annotations\n origin = get...
1,1,"async def create_mcp_websocket_connection(request: CreateWebSocketConnectionRequest):\n """"""Create WebSocket connection URL""""""\n try:\n session_id = str(uuid.uuid4())\n\n server..."
2,2,"def test_stop_bridge(self, bridge):\n """"""Test stopping the bridge""""""\n assert bridge._running is True\n \n bridge.stop()\n \n assert bridge._running is False"
3,3,"def _put(self, item: T) -> None:\n self._queue.append(item)"
4,4,class DataclassNestedUnionSyntaxNewMessage:\n message: str | int
...,...,...
995,995,"def test_normalize_shell_output_handles_timeout() -> None:\n entry = {\n ""stdout"": """",\n ""stderr"": """",\n ""outcome"": {""type"": ""timeout""},\n ""provider_data"": {""truncat..."
996,996,"def greet(name: str) -> str:\n return f""Hello, {name}!"""
997,997,def __init__(self):\n self.responses = DummyResponses()
998,998,"async def _get_screenshot_async(\n cls,\n computer: AsyncComputer,\n tool_call: ResponseComputerToolCall,\n ) -> str:\n action = tool_call.action\n if isinsta..."
999,999,"def main():\n parser = argparse.ArgumentParser(description=""Translate documentation files"")\n parser.add_argument(\n ""--file"", type=str, help=""Specific file to translate (relative to ..."

our corpus is ready

In [56]:
## make it a tsv file but remove extra index
corpus.to_csv('/kaggle/working/corpus.tsv',sep='\t',index=False)

# Generating Topics

In [57]:
# Get unique anchors (queries)
unique_queries = df['anchor'].unique()

In [58]:
# Randomly sample 69 queries
import random
random.seed(42)  # For reproducibility
sampled_queries = random.sample(list(unique_queries), 21)

In [59]:
# Create topics dataframe
topics_df = pd.DataFrame({
    'qid': [f'q{i+1}' for i in range(21)],
    'query': sampled_queries
})

In [60]:
topics_df

,qid,query
0,q1,Example usage of LangGraphAgentAdapter
1,q2,Explain the capabilities logic
2,q3,Example usage of serve
3,q4,Best practices for ChatGroq
4,q5,"How does TestResponseRewriting:\n """"""Test response content rewriting with wrap_model_call.""""""\n\n test_uppercase_response work in Python?"
5,q6,Example usage of truncate_messages
6,q7,Explain the async test_cache_streaming_list_without_create_result logic
7,q8,How does async test_selector_group_chat work in Python?
8,q9,Example usage of async test_pretty_run_result_streaming
9,q10,Explain the StreamArgs logic
10,q11,Best practices for page_down
11,q12,How to implement async test_buffered_model_context?
12,q13,Example usage of RoboflowProviderSpec
13,q14,"How to implement TestRedactStrategy:\n """"""Test redact strategy.""""""\n\n test_redact_email?"
14,q15,Example usage of async test_api_failure_during_add_items
15,q16,How to implement subscription_to_proto?
16,q17,Best practices for test_create_search_index
17,q18,Example usage of test_dynamic_model_basic
18,q19,How to implement task_output?
19,q20,Example usage of async test_forcing_tool_use_behaviors_align_with_example
20,q21,Example usage of generate_prompt

In [61]:
# Save to TSV
topics_df.to_csv('/kaggle/working/topics.tsv', sep='\t', index=False)

In [62]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm

In [63]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()

HF_TOKEN=user_secrets.get_secret("HF_TOKEN")

In [64]:
from huggingface_hub import login
import os


login(token=HF_TOKEN)

- we will try to do it with llama-3.1-8b model first then will do it with llama-3.1-70b model

# Phase 2 — Depth-100 Pooling + LLM Judging
BM25 + Jina + CodeBERT each retrieve top-100 → union → judge only the pooled pairs.
This is standard TREC pooling methodology.

In [67]:
# Before indexing, force string type
corpus['docno'] = corpus['docno'].astype(str)

/tmp/ipykernel_54/3188760592.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corpus['docno'] = corpus['docno'].astype(str)

In [98]:
# BM25 Index
BM25_INDEX_PATH = '/kaggle/working/custom_bm25_index'
indexer   = pt.IterDictIndexer(BM25_INDEX_PATH, overwrite=True)
index_ref = indexer.index(corpus.to_dict('records'))
bm25 = pt.BatchRetrieve(index_ref, wmodel='BM25', num_results=100)
print('BM25 index built.')
bm25(topics_df.head(2)).head(3)

BM25 index built.

/tmp/ipykernel_54/3352110468.py:5: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  bm25 = pt.BatchRetrieve(index_ref, wmodel='BM25', num_results=100)

  qid  docid docno  rank     score                                   query
0  q1    633   633     0  9.737878  Example usage of LangGraphAgentAdapter
1  q1    394   394     1  9.377459  Example usage of LangGraphAgentAdapter
2  q1    700   700     2  9.357109  Example usage of LangGraphAgentAdapter

In [99]:
# ── GraphCodeBERT dense index (Jina replacement) ──
graphcb       = pyterrier_dr.SBertBiEncoder('microsoft/graphcodebert-base', batch_size=64)
graphcb_index = pyterrier_dr.FlexIndex('/kaggle/working/custom_graphcb.flex')
(graphcb >> graphcb_index).index(corpus.to_dict('records'))
graphcb_retr  = graphcb >> graphcb_index.np_retriever()
print('GraphCodeBERT index built.')

# ── free before next model ──
gc.collect()
for i in range(torch.cuda.device_count()):
    with torch.cuda.device(i):
        torch.cuda.empty_cache()

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name microsoft/graphcodebert-base. Creating a new one with mean pooling.
Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
indexing: 1000dvec [00:23, 42.97dvec/s]

GraphCodeBERT index built.

In [102]:
# CodeBERT dense index
codebert       = pyterrier_dr.SBertBiEncoder('microsoft/codebert-base')
codebert_index = pyterrier_dr.FlexIndex('/kaggle/working/custom_codebert.flex')
(codebert >> codebert_index).index(corpus.to_dict('records'))
codebert_retr  = codebert >> codebert_index.np_retriever()
print('CodeBERT index built.')

gc.collect()
for i in range(torch.cuda.device_count()):
    with torch.cuda.device(i):
        torch.cuda.empty_cache()

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name microsoft/codebert-base. Creating a new one with mean pooling.
indexing: 1000dvec [00:20, 48.19dvec/s]

CodeBERT index built.

In [104]:
# ── Depth-100 Pool ──
POOL_DEPTH = 100
bm25 = pt.BatchRetrieve(index_ref, wmodel='BM25', num_results=100)
graphcb_retr  = graphcb >> graphcb_index.np_retriever()
codebert_retr  = codebert >> codebert_index.np_retriever()

print('Running BM25...')
bm25_res = bm25(topics_df).query('rank < @POOL_DEPTH')
print('Running graphcodebert...')
graphcb_res = graphcb_retr(topics_df).query('rank < @POOL_DEPTH')
print('Running CodeBERT...')
cb_res   = codebert_retr(topics_df).query('rank < @POOL_DEPTH')

pool = (
    pd.concat([bm25_res, graphcb_res, cb_res], ignore_index=True)
    .drop_duplicates(subset=['qid', 'docno'])
    [['qid', 'docno']]
    .reset_index(drop=True)
)

# Attach code text + query text
pool = pool.merge(corpus.rename(columns={'text': 'code'}), on='docno', how='left')
pool = pool.merge(topics_df, on='qid', how='left')
pool = pool.dropna(subset=['code', 'query'])

print(f'Pool: {len(pool)} unique (query, doc) pairs')
print(f'Avg per query: {len(pool)/len(topics_df):.1f}')
pool.to_csv('/kaggle/working/pool.csv', index=False)

/tmp/ipykernel_54/486042576.py:3: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  bm25 = pt.BatchRetrieve(index_ref, wmodel='BM25', num_results=100)

Running BM25...
Running graphcodebert...

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 247.44docbatch/s]

Running CodeBERT...

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 644.78docbatch/s]

Pool: 4871 unique (query, doc) pairs
Avg per query: 232.0

In [105]:
# Judge pooled pairs with best judge from Phase 0
# (If kernel restarted, set BEST_JUDGE_HF and BEST_JUDGE_4BIT manually)
# BEST_JUDGE_HF   = 'meta-llama/Llama-3.1-70B-Instruct'
# BEST_JUDGE_4BIT = True

pool = pd.read_csv('/kaggle/working/pool.csv')
judge_tok, judge_mdl = load_llm('Qwen/Qwen2.5-Coder-7B-Instruct')

pool_judged = []
CHECKPOINT_EVERY = 3

for i, (qid, group) in enumerate(tqdm(pool.groupby('qid'), desc='Judging queries')):
    scores = judge_batch(
        group['query'].tolist(), group['code'].tolist(),
        judge_tok, judge_mdl, batch_size=4
    )
    for (_, row), sc in zip(group.iterrows(), scores):
        pool_judged.append({'qid': row['qid'], 'docno': row['docno'], 'relevance': sc})

    if (i + 1) % CHECKPOINT_EVERY == 0:
        pd.DataFrame(pool_judged).to_csv('/kaggle/working/pool_judged_ckpt.csv', index=False)
        print(f'  checkpoint @ query {i+1}')

pool_judged_df = pd.DataFrame(pool_judged)
pool_judged_df.to_csv('/kaggle/working/pool_judged.csv', index=False)
print(f'Judged {len(pool_judged_df)} pairs')
print(pool_judged_df['relevance'].value_counts().sort_index())
judge_mdl = None
judge_tok = None
gc.collect()
for i in range(torch.cuda.device_count()):
    with torch.cuda.device(i):
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()
for i in range(torch.cuda.device_count()):
    print(f"GPU {i} → {torch.cuda.memory_allocated(i)/1e9:.2f} GB")

Loading Qwen/Qwen2.5-Coder-7B-Instruct...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

  Loaded.

Judging queries:   0%|          | 0/21 [00:00<?, ?it/s]
Judging:   0%|          | 0/57 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/57 [00:01<01:29,  1.60s/batch]
Judging:   4%|▎         | 2/57 [00:03<01:28,  1.62s/batch]
Judging:   5%|▌         | 3/57 [00:04<01:24,  1.57s/batch]
Judging:   7%|▋         | 4/57 [00:06<01:22,  1.56s/batch]
Judging:   9%|▉         | 5/57 [00:07<01:22,  1.58s/batch]
Judging:  11%|█         | 6/57 [00:09<01:19,  1.55s/batch]
Judging:  12%|█▏        | 7/57 [00:11<01:22,  1.65s/batch]
Judging:  14%|█▍        | 8/57 [00:12<01:19,  1.61s/batch]
Judging:  16%|█▌        | 9/57 [00:14<01:17,  1.60s/batch]
Judging:  18%|█▊        | 10/57 [00:16<01:16,  1.63s/batch]
Judging:  19%|█▉        | 11/57 [00:17<01:14,  1.61s/batch]
Judging:  21%|██        | 12/57 [00:19<01:12,  1.61s/batch]
Judging:  23%|██▎       | 13/57 [00:21<01:13,  1.67s/batch]
Judging:  25%|██▍       | 14/57 [00:22<01:11,  1.65s/batch]
Judging:  26%|██▋       | 15/57 [00:24<01:09,  1.65s/batch]
Judging:  28%|██▊       | 16/57 [00:26<01:09,  1.68s/batch]
Judging:  30%|██▉       | 17/57 [00:27<01:06,  1.67s/batch]
Judging:  32%|███▏      | 18/57 [00:29<01:08,  1.74s/batch]
Judging:  33%|███▎      | 19/57 [00:31<01:05,  1.72s/batch]
Judging:  35%|███▌      | 20/57 [00:32<01:01,  1.66s/batch]
Judging:  37%|███▋      | 21/57 [00:33<00:52,  1.46s/batch]
Judging:  39%|███▊      | 22/57 [00:34<00:46,  1.32s/batch]
Judging:  40%|████      | 23/57 [00:35<00:41,  1.23s/batch]
Judging:  42%|████▏     | 24/57 [00:36<00:38,  1.16s/batch]
Judging:  44%|████▍     | 25/57 [00:37<00:35,  1.11s/batch]
Judging:  46%|████▌     | 26/57 [00:38<00:33,  1.08s/batch]
Judging:  47%|████▋     | 27/57 [00:39<00:31,  1.06s/batch]
Judging:  49%|████▉     | 28/57 [00:40<00:30,  1.04s/batch]
Judging:  51%|█████     | 29/57 [00:41<00:28,  1.03s/batch]
Judging:  53%|█████▎    | 30/57 [00:43<00:29,  1.09s/batch]
Judging:  54%|█████▍    | 31/57 [00:44<00:27,  1.07s/batch]
Judging:  56%|█████▌    | 32/57 [00:45<00:26,  1.04s/batch]
Judging:  58%|█████▊    | 33/57 [00:46<00:24,  1.04s/batch]
Judging:  60%|█████▉    | 34/57 [00:47<00:23,  1.03s/batch]
Judging:  61%|██████▏   | 35/57 [00:48<00:22,  1.02s/batch]
Judging:  63%|██████▎   | 36/57 [00:49<00:21,  1.02s/batch]
Judging:  65%|██████▍   | 37/57 [00:50<00:20,  1.02s/batch]
Judging:  67%|██████▋   | 38/57 [00:51<00:19,  1.02s/batch]
Judging:  68%|██████▊   | 39/57 [00:52<00:18,  1.02s/batch]
Judging:  70%|███████   | 40/57 [00:53<00:17,  1.02s/batch]
Judging:  72%|███████▏  | 41/57 [00:54<00:16,  1.02s/batch]
Judging:  74%|███████▎  | 42/57 [00:55<00:15,  1.02s/batch]
Judging:  75%|███████▌  | 43/57 [00:56<00:14,  1.02s/batch]
Judging:  77%|███████▋  | 44/57 [00:57<00:13,  1.01s/batch]
Judging:  79%|███████▉  | 45/57 [00:58<00:12,  1.01s/batch]
Judging:  81%|████████  | 46/57 [00:59<00:11,  1.02s/batch]
Judging:  82%|████████▏ | 47/57 [01:00<00:10,  1.10s/batch]
Judging:  84%|████████▍ | 48/57 [01:01<00:09,  1.07s/batch]
Judging:  86%|████████▌ | 49/57 [01:02<00:08,  1.06s/batch]
Judging:  88%|████████▊ | 50/57 [01:03<00:07,  1.05s/batch]
Judging:  89%|████████▉ | 51/57 [01:04<00:06,  1.03s/batch]
Judging:  91%|█████████ | 52/57 [01:05<00:05,  1.10s/batch]
Judging:  93%|█████████▎| 53/57 [01:06<00:04,  1.08s/batch]
Judging:  95%|█████████▍| 54/57 [01:07<00:03,  1.06s/batch]
Judging:  96%|█████████▋| 55/57 [01:08<00:02,  1.05s/batch]
Judging:  98%|█████████▊| 56/57 [01:09<00:01,  1.04s/batch]
Judging: 100%|██████████| 57/57 [01:10<00:00,  1.24s/batch]
Judging queries:   5%|▍         | 1/21 [01:10<23:31, 70.57s/it]
Judging:   0%|          | 0/43 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/43 [00:01<00:43,  1.03s/batch]
Judging:   5%|▍         | 2/43 [00:02<00:59,  1.44s/batch]
Judging:   7%|▋         | 3/43 [00:04<01:01,  1.54s/batch]
Judging:   9%|▉         | 4/43 [00:05<00:58,  1.51s/batch]
Judging:  12%|█▏        | 5/43 [00:06<00:50,  1.34s/batch]
Judging:  14%|█▍        | 6/43 [00:07<00:45,  1.23s/batch]
Judging:  16%|█▋        | 7/43 [00:08<00:41,  1.16s/batch]
Judging:  19%|█▊        | 8/43 [00:09<00:39,  1.12s/batch]
Judging:  21%|██        | 9/43 [00:11<00:36,  1.09s/batch]
Judging:  23%|██▎       | 10/43 [00:12<00:35,  1.07s/batch]
Judging:  26%|██▌       | 11/43 [00:13<00:34,  1.07s/batch]
Judging:  28%|██▊       | 12/43 [00:14<00:32,  1.06s/batch]
Judging:  30%|███       | 13/43 [00:15<00:31,  1.04s/batch]
Judging:  33%|███▎      | 14/43 [00:16<00:30,  1.05s/batch]
Judging:  35%|███▍      | 15/43 [00:17<00:29,  1.04s/batch]
Judging:  37%|███▋      | 16/43 [00:18<00:28,  1.04s/batch]
Judging:  40%|███▉      | 17/43 [00:19<00:27,  1.04s/batch]
Judging:  42%|████▏     | 18/43 [00:20<00:26,  1.04s/batch]
Judging:  44%|████▍     | 19/43 [00:21<00:25,  1.05s/batch]
Judging:  47%|████▋     | 20/43 [00:22<00:24,  1.05s/batch]
Judging:  49%|████▉     | 21/43 [00:23<00:23,  1.05s/batch]
Judging:  51%|█████     | 22/43 [00:24<00:22,  1.05s/batch]
Judging:  53%|█████▎    | 23/43 [00:25<00:21,  1.05s/batch]
Judging:  56%|█████▌    | 24/43 [00:26<00:20,  1.06s/batch]
Judging:  58%|█████▊    | 25/43 [00:27<00:19,  1.06s/batch]
Judging:  60%|██████    | 26/43 [00:28<00:18,  1.06s/batch]
Judging:  63%|██████▎   | 27/43 [00:29<00:16,  1.06s/batch]
Judging:  65%|██████▌   | 28/43 [00:30<00:15,  1.05s/batch]
Judging:  67%|██████▋   | 29/43 [00:31<00:14,  1.05s/batch]
Judging:  70%|██████▉   | 30/43 [00:33<00:14,  1.09s/batch]
Judging:  72%|███████▏  | 31/43 [00:34<00:13,  1.09s/batch]
Judging:  74%|███████▍  | 32/43 [00:35<00:12,  1.18s/batch]
Judging:  77%|███████▋  | 33/43 [00:36<00:11,  1.17s/batch]
Judging:  79%|███████▉  | 34/43 [00:37<00:10,  1.14s/batch]
Judging:  81%|████████▏ | 35/43 [00:39<00:09,  1.15s/batch]
Judging:  84%|████████▎ | 36/43 [00:40<00:07,  1.12s/batch]
Judging:  86%|████████▌ | 37/43 [00:41<00:06,  1.14s/batch]
Judging:  88%|████████▊ | 38/43 [00:42<00:05,  1.12s/batch]
Judging:  91%|█████████ | 39/43 [00:43<00:04,  1.10s/batch]
Judging:  93%|█████████▎| 40/43 [00:44<00:03,  1.09s/batch]
Judging:  95%|█████████▌| 41/43 [00:45<00:02,  1.17s/batch]
Judging:  98%|█████████▊| 42/43 [00:47<00:01,  1.17s/batch]
Judging: 100%|██████████| 43/43 [00:48<00:00,  1.12s/batch]
Judging queries:  10%|▉         | 2/21 [01:58<18:09, 57.35s/it]
Judging:   0%|          | 0/43 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/43 [00:02<01:24,  2.02s/batch]
Judging:   5%|▍         | 2/43 [00:03<01:00,  1.48s/batch]
Judging:   7%|▋         | 3/43 [00:04<00:51,  1.29s/batch]
Judging:   9%|▉         | 4/43 [00:05<00:46,  1.19s/batch]
Judging:  12%|█▏        | 5/43 [00:06<00:43,  1.15s/batch]
Judging:  14%|█▍        | 6/43 [00:07<00:44,  1.21s/batch]
Judging:  16%|█▋        | 7/43 [00:08<00:42,  1.17s/batch]
Judging:  19%|█▊        | 8/43 [00:09<00:39,  1.14s/batch]
Judging:  21%|██        | 9/43 [00:10<00:37,  1.12s/batch]
Judging:  23%|██▎       | 10/43 [00:11<00:36,  1.10s/batch]
Judging:  26%|██▌       | 11/43 [00:12<00:34,  1.08s/batch]
Judging:  28%|██▊       | 12/43 [00:14<00:33,  1.08s/batch]
Judging:  30%|███       | 13/43 [00:15<00:32,  1.07s/batch]
Judging:  33%|███▎      | 14/43 [00:16<00:30,  1.06s/batch]
Judging:  35%|███▍      | 15/43 [00:17<00:29,  1.06s/batch]
Judging:  37%|███▋      | 16/43 [00:18<00:28,  1.06s/batch]
Judging:  40%|███▉      | 17/43 [00:19<00:27,  1.06s/batch]
Judging:  42%|████▏     | 18/43 [00:20<00:26,  1.06s/batch]
Judging:  44%|████▍     | 19/43 [00:21<00:25,  1.06s/batch]
Judging:  47%|████▋     | 20/43 [00:22<00:24,  1.06s/batch]
Judging:  49%|████▉     | 21/43 [00:23<00:23,  1.06s/batch]
Judging:  51%|█████     | 22/43 [00:24<00:22,  1.06s/batch]
Judging:  53%|█████▎    | 23/43 [00:25<00:21,  1.07s/batch]
Judging:  56%|█████▌    | 24/43 [00:26<00:20,  1.07s/batch]
Judging:  58%|█████▊    | 25/43 [00:28<00:20,  1.15s/batch]
Judging:  60%|██████    | 26/43 [00:29<00:19,  1.13s/batch]
Judging:  63%|██████▎   | 27/43 [00:30<00:17,  1.09s/batch]
Judging:  65%|██████▌   | 28/43 [00:31<00:16,  1.07s/batch]
Judging:  67%|██████▋   | 29/43 [00:32<00:15,  1.09s/batch]
Judging:  70%|██████▉   | 30/43 [00:33<00:14,  1.08s/batch]
Judging:  72%|███████▏  | 31/43 [00:34<00:12,  1.07s/batch]
Judging:  74%|███████▍  | 32/43 [00:35<00:12,  1.14s/batch]
Judging:  77%|███████▋  | 33/43 [00:36<00:11,  1.11s/batch]
Judging:  79%|███████▉  | 34/43 [00:37<00:10,  1.12s/batch]
Judging:  81%|████████▏ | 35/43 [00:39<00:09,  1.13s/batch]
Judging:  84%|████████▎ | 36/43 [00:40<00:07,  1.11s/batch]
Judging:  86%|████████▌ | 37/43 [00:41<00:06,  1.10s/batch]
Judging:  88%|████████▊ | 38/43 [00:42<00:05,  1.08s/batch]
Judging:  91%|█████████ | 39/43 [00:43<00:04,  1.07s/batch]
Judging:  93%|█████████▎| 40/43 [00:44<00:03,  1.09s/batch]
Judging:  95%|█████████▌| 41/43 [00:45<00:02,  1.08s/batch]
Judging:  98%|█████████▊| 42/43 [00:46<00:01,  1.09s/batch]
Judging: 100%|██████████| 43/43 [00:47<00:00,  1.10s/batch]
Judging queries:  14%|█▍        | 3/21 [02:46<15:51, 52.87s/it]

  checkpoint @ query 3

Judging:   0%|          | 0/67 [00:00<?, ?batch/s]
Judging:   1%|▏         | 1/67 [00:01<01:51,  1.69s/batch]
Judging:   3%|▎         | 2/67 [00:03<01:54,  1.76s/batch]
Judging:   4%|▍         | 3/67 [00:05<01:50,  1.73s/batch]
Judging:   6%|▌         | 4/67 [00:07<01:55,  1.83s/batch]
Judging:   7%|▋         | 5/67 [00:08<01:50,  1.79s/batch]
Judging:   9%|▉         | 6/67 [00:10<01:46,  1.75s/batch]
Judging:  10%|█         | 7/67 [00:12<01:43,  1.73s/batch]
Judging:  12%|█▏        | 8/67 [00:13<01:41,  1.72s/batch]
Judging:  13%|█▎        | 9/67 [00:15<01:38,  1.70s/batch]
Judging:  15%|█▍        | 10/67 [00:17<01:36,  1.70s/batch]
Judging:  16%|█▋        | 11/67 [00:19<01:35,  1.71s/batch]
Judging:  18%|█▊        | 12/67 [00:20<01:31,  1.66s/batch]
Judging:  19%|█▉        | 13/67 [00:22<01:30,  1.68s/batch]
Judging:  21%|██        | 14/67 [00:24<01:31,  1.72s/batch]
Judging:  22%|██▏       | 15/67 [00:25<01:30,  1.74s/batch]
Judging:  24%|██▍       | 16/67 [00:27<01:23,  1.64s/batch]
Judging:  25%|██▌       | 17/67 [00:28<01:13,  1.47s/batch]
Judging:  27%|██▋       | 18/67 [00:29<01:13,  1.50s/batch]
Judging:  28%|██▊       | 19/67 [00:31<01:14,  1.56s/batch]
Judging:  30%|██▉       | 20/67 [00:33<01:16,  1.63s/batch]
Judging:  31%|███▏      | 21/67 [00:35<01:17,  1.69s/batch]
Judging:  33%|███▎      | 22/67 [00:37<01:17,  1.72s/batch]
Judging:  34%|███▍      | 23/67 [00:38<01:15,  1.72s/batch]
Judging:  36%|███▌      | 24/67 [00:40<01:11,  1.67s/batch]
Judging:  37%|███▋      | 25/67 [00:42<01:12,  1.71s/batch]
Judging:  39%|███▉      | 26/67 [00:43<01:05,  1.60s/batch]
Judging:  40%|████      | 27/67 [00:44<01:00,  1.52s/batch]
Judging:  42%|████▏     | 28/67 [00:45<00:55,  1.42s/batch]
Judging:  43%|████▎     | 29/67 [00:47<00:52,  1.39s/batch]
Judging:  45%|████▍     | 30/67 [00:48<00:47,  1.29s/batch]
Judging:  46%|████▋     | 31/67 [00:49<00:44,  1.22s/batch]
Judging:  48%|████▊     | 32/67 [00:50<00:41,  1.18s/batch]
Judging:  49%|████▉     | 33/67 [00:51<00:38,  1.14s/batch]
Judging:  51%|█████     | 34/67 [00:52<00:40,  1.21s/batch]
Judging:  52%|█████▏    | 35/67 [00:54<00:37,  1.17s/batch]
Judging:  54%|█████▎    | 36/67 [00:55<00:35,  1.13s/batch]
Judging:  55%|█████▌    | 37/67 [00:56<00:35,  1.20s/batch]
Judging:  57%|█████▋    | 38/67 [00:57<00:33,  1.16s/batch]
Judging:  58%|█████▊    | 39/67 [00:58<00:31,  1.13s/batch]
Judging:  60%|█████▉    | 40/67 [00:59<00:32,  1.20s/batch]
Judging:  61%|██████    | 41/67 [01:00<00:29,  1.15s/batch]
Judging:  63%|██████▎   | 42/67 [01:02<00:28,  1.12s/batch]
Judging:  64%|██████▍   | 43/67 [01:03<00:26,  1.11s/batch]
Judging:  66%|██████▌   | 44/67 [01:04<00:25,  1.09s/batch]
Judging:  67%|██████▋   | 45/67 [01:05<00:26,  1.20s/batch]
Judging:  69%|██████▊   | 46/67 [01:06<00:24,  1.15s/batch]
Judging:  70%|███████   | 47/67 [01:07<00:22,  1.13s/batch]
Judging:  72%|███████▏  | 48/67 [01:08<00:21,  1.12s/batch]
Judging:  73%|███████▎  | 49/67 [01:10<00:21,  1.18s/batch]
Judging:  75%|███████▍  | 50/67 [01:11<00:19,  1.14s/batch]
Judging:  76%|███████▌  | 51/67 [01:12<00:17,  1.11s/batch]
Judging:  78%|███████▊  | 52/67 [01:13<00:16,  1.09s/batch]
Judging:  79%|███████▉  | 53/67 [01:14<00:16,  1.17s/batch]
Judging:  81%|████████  | 54/67 [01:15<00:14,  1.13s/batch]
Judging:  82%|████████▏ | 55/67 [01:16<00:13,  1.10s/batch]
Judging:  84%|████████▎ | 56/67 [01:17<00:11,  1.09s/batch]
Judging:  85%|████████▌ | 57/67 [01:18<00:10,  1.08s/batch]
Judging:  87%|████████▋ | 58/67 [01:19<00:09,  1.07s/batch]
Judging:  88%|████████▊ | 59/67 [01:20<00:08,  1.07s/batch]
Judging:  90%|████████▉ | 60/67 [01:21<00:07,  1.06s/batch]
Judging:  91%|█████████ | 61/67 [01:23<00:06,  1.06s/batch]
Judging:  93%|█████████▎| 62/67 [01:24<00:05,  1.06s/batch]
Judging:  94%|█████████▍| 63/67 [01:25<00:04,  1.05s/batch]
Judging:  96%|█████████▌| 64/67 [01:26<00:03,  1.15s/batch]
Judging:  97%|█████████▋| 65/67 [01:27<00:02,  1.20s/batch]
Judging:  99%|█████████▊| 66/67 [01:29<00:01,  1.25s/batch]
Judging: 100%|██████████| 67/67 [01:29<00:00,  1.34s/batch]
Judging queries:  19%|█▉        | 4/21 [04:16<19:07, 67.48s/it]
Judging:   0%|          | 0/56 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/56 [00:01<01:31,  1.67s/batch]
Judging:   4%|▎         | 2/56 [00:03<01:29,  1.65s/batch]
Judging:   5%|▌         | 3/56 [00:05<01:30,  1.71s/batch]
Judging:   7%|▋         | 4/56 [00:06<01:28,  1.70s/batch]
Judging:   9%|▉         | 5/56 [00:08<01:27,  1.71s/batch]
Judging:  11%|█         | 6/56 [00:10<01:22,  1.66s/batch]
Judging:  12%|█▎        | 7/56 [00:12<01:26,  1.77s/batch]
Judging:  14%|█▍        | 8/56 [00:13<01:22,  1.73s/batch]
Judging:  16%|█▌        | 9/56 [00:15<01:20,  1.71s/batch]
Judging:  18%|█▊        | 10/56 [00:17<01:19,  1.73s/batch]
Judging:  20%|█▉        | 11/56 [00:18<01:16,  1.71s/batch]
Judging:  21%|██▏       | 12/56 [00:20<01:15,  1.70s/batch]
Judging:  23%|██▎       | 13/56 [00:22<01:11,  1.66s/batch]
Judging:  25%|██▌       | 14/56 [00:23<01:12,  1.74s/batch]
Judging:  27%|██▋       | 15/56 [00:25<01:11,  1.73s/batch]
Judging:  29%|██▊       | 16/56 [00:27<01:10,  1.76s/batch]
Judging:  30%|███       | 17/56 [00:29<01:08,  1.75s/batch]
Judging:  32%|███▏      | 18/56 [00:30<01:05,  1.73s/batch]
Judging:  34%|███▍      | 19/56 [00:32<01:07,  1.82s/batch]
Judging:  36%|███▌      | 20/56 [00:34<01:03,  1.77s/batch]
Judging:  38%|███▊      | 21/56 [00:35<00:54,  1.55s/batch]
Judging:  39%|███▉      | 22/56 [00:36<00:47,  1.41s/batch]
Judging:  41%|████      | 23/56 [00:37<00:42,  1.30s/batch]
Judging:  43%|████▎     | 24/56 [00:38<00:39,  1.22s/batch]
Judging:  45%|████▍     | 25/56 [00:40<00:39,  1.26s/batch]
Judging:  46%|████▋     | 26/56 [00:41<00:36,  1.21s/batch]
Judging:  48%|████▊     | 27/56 [00:42<00:33,  1.17s/batch]
Judging:  50%|█████     | 28/56 [00:43<00:31,  1.14s/batch]
Judging:  52%|█████▏    | 29/56 [00:44<00:30,  1.11s/batch]
Judging:  54%|█████▎    | 30/56 [00:45<00:28,  1.11s/batch]
Judging:  55%|█████▌    | 31/56 [00:46<00:27,  1.10s/batch]
Judging:  57%|█████▋    | 32/56 [00:47<00:28,  1.17s/batch]
Judging:  59%|█████▉    | 33/56 [00:49<00:26,  1.15s/batch]
Judging:  61%|██████    | 34/56 [00:50<00:24,  1.13s/batch]
Judging:  62%|██████▎   | 35/56 [00:51<00:23,  1.11s/batch]
Judging:  64%|██████▍   | 36/56 [00:52<00:22,  1.10s/batch]
Judging:  66%|██████▌   | 37/56 [00:53<00:22,  1.18s/batch]
Judging:  68%|██████▊   | 38/56 [00:54<00:20,  1.15s/batch]
Judging:  70%|██████▉   | 39/56 [00:55<00:19,  1.12s/batch]
Judging:  71%|███████▏  | 40/56 [00:56<00:18,  1.13s/batch]
Judging:  73%|███████▎  | 41/56 [00:57<00:16,  1.11s/batch]
Judging:  75%|███████▌  | 42/56 [00:59<00:15,  1.09s/batch]
Judging:  77%|███████▋  | 43/56 [01:00<00:14,  1.08s/batch]
Judging:  79%|███████▊  | 44/56 [01:01<00:12,  1.08s/batch]
Judging:  80%|████████  | 45/56 [01:02<00:11,  1.08s/batch]
Judging:  82%|████████▏ | 46/56 [01:03<00:10,  1.07s/batch]
Judging:  84%|████████▍ | 47/56 [01:04<00:10,  1.16s/batch]
Judging:  86%|████████▌ | 48/56 [01:05<00:09,  1.13s/batch]
Judging:  88%|████████▊ | 49/56 [01:06<00:07,  1.11s/batch]
Judging:  89%|████████▉ | 50/56 [01:08<00:07,  1.17s/batch]
Judging:  91%|█████████ | 51/56 [01:09<00:05,  1.14s/batch]
Judging:  93%|█████████▎| 52/56 [01:10<00:04,  1.11s/batch]
Judging:  95%|█████████▍| 53/56 [01:11<00:03,  1.09s/batch]
Judging:  96%|█████████▋| 54/56 [01:12<00:02,  1.08s/batch]
Judging:  98%|█████████▊| 55/56 [01:13<00:01,  1.08s/batch]
Judging: 100%|██████████| 56/56 [01:14<00:00,  1.33s/batch]
Judging queries:  24%|██▍       | 5/21 [05:30<18:39, 70.00s/it]
Judging:   0%|          | 0/69 [00:00<?, ?batch/s]
Judging:   1%|▏         | 1/69 [00:01<01:54,  1.69s/batch]
Judging:   3%|▎         | 2/69 [00:03<01:56,  1.74s/batch]
Judging:   4%|▍         | 3/69 [00:05<01:55,  1.75s/batch]
Judging:   6%|▌         | 4/69 [00:06<01:49,  1.68s/batch]
Judging:   7%|▋         | 5/69 [00:08<01:51,  1.74s/batch]
Judging:   9%|▊         | 6/69 [00:10<01:51,  1.76s/batch]
Judging:  10%|█         | 7/69 [00:12<01:47,  1.73s/batch]
Judging:  12%|█▏        | 8/69 [00:13<01:42,  1.68s/batch]
Judging:  13%|█▎        | 9/69 [00:15<01:42,  1.71s/batch]
Judging:  14%|█▍        | 10/69 [00:17<01:40,  1.70s/batch]
Judging:  16%|█▌        | 11/69 [00:18<01:37,  1.69s/batch]
Judging:  17%|█▋        | 12/69 [00:20<01:36,  1.69s/batch]
Judging:  19%|█▉        | 13/69 [00:22<01:34,  1.69s/batch]
Judging:  20%|██        | 14/69 [00:23<01:29,  1.62s/batch]
Judging:  22%|██▏       | 15/69 [00:25<01:30,  1.68s/batch]
Judging:  23%|██▎       | 16/69 [00:27<01:29,  1.68s/batch]
Judging:  25%|██▍       | 17/69 [00:28<01:23,  1.60s/batch]
Judging:  26%|██▌       | 18/69 [00:30<01:23,  1.63s/batch]
Judging:  28%|██▊       | 19/69 [00:31<01:22,  1.64s/batch]
Judging:  29%|██▉       | 20/69 [00:33<01:20,  1.65s/batch]
Judging:  30%|███       | 21/69 [00:35<01:17,  1.61s/batch]
Judging:  32%|███▏      | 22/69 [00:36<01:18,  1.66s/batch]
Judging:  33%|███▎      | 23/69 [00:38<01:17,  1.67s/batch]
Judging:  35%|███▍      | 24/69 [00:40<01:13,  1.64s/batch]
Judging:  36%|███▌      | 25/69 [00:42<01:15,  1.71s/batch]
Judging:  38%|███▊      | 26/69 [00:43<01:05,  1.52s/batch]
Judging:  39%|███▉      | 27/69 [00:44<00:58,  1.38s/batch]
Judging:  41%|████      | 28/69 [00:45<00:53,  1.29s/batch]
Judging:  42%|████▏     | 29/69 [00:46<00:49,  1.23s/batch]
Judging:  43%|████▎     | 30/69 [00:47<00:46,  1.18s/batch]
Judging:  45%|████▍     | 31/69 [00:48<00:43,  1.15s/batch]
Judging:  46%|████▋     | 32/69 [00:49<00:41,  1.12s/batch]
Judging:  48%|████▊     | 33/69 [00:50<00:39,  1.11s/batch]
Judging:  49%|████▉     | 34/69 [00:52<00:41,  1.19s/batch]
Judging:  51%|█████     | 35/69 [00:53<00:39,  1.15s/batch]
Judging:  52%|█████▏    | 36/69 [00:54<00:38,  1.16s/batch]
Judging:  54%|█████▎    | 37/69 [00:55<00:36,  1.13s/batch]
Judging:  55%|█████▌    | 38/69 [00:56<00:37,  1.20s/batch]
Judging:  57%|█████▋    | 39/69 [00:58<00:37,  1.25s/batch]
Judging:  58%|█████▊    | 40/69 [00:59<00:34,  1.19s/batch]
Judging:  59%|█████▉    | 41/69 [01:00<00:34,  1.24s/batch]
Judging:  61%|██████    | 42/69 [01:01<00:32,  1.19s/batch]
Judging:  62%|██████▏   | 43/69 [01:02<00:30,  1.16s/batch]
Judging:  64%|██████▍   | 44/69 [01:03<00:30,  1.21s/batch]
Judging:  65%|██████▌   | 45/69 [01:05<00:29,  1.24s/batch]
Judging:  67%|██████▋   | 46/69 [01:06<00:28,  1.22s/batch]
Judging:  68%|██████▊   | 47/69 [01:07<00:27,  1.24s/batch]
Judging:  70%|██████▉   | 48/69 [01:09<00:26,  1.27s/batch]
Judging:  71%|███████   | 49/69 [01:10<00:24,  1.21s/batch]
Judging:  72%|███████▏  | 50/69 [01:11<00:23,  1.24s/batch]
Judging:  74%|███████▍  | 51/69 [01:12<00:21,  1.19s/batch]
Judging:  75%|███████▌  | 52/69 [01:13<00:19,  1.15s/batch]
Judging:  77%|███████▋  | 53/69 [01:14<00:17,  1.12s/batch]
Judging:  78%|███████▊  | 54/69 [01:15<00:16,  1.10s/batch]
Judging:  80%|███████▉  | 55/69 [01:16<00:16,  1.16s/batch]
Judging:  81%|████████  | 56/69 [01:18<00:15,  1.22s/batch]
Judging:  83%|████████▎ | 57/69 [01:19<00:15,  1.25s/batch]
Judging:  84%|████████▍ | 58/69 [01:20<00:13,  1.19s/batch]
Judging:  86%|████████▌ | 59/69 [01:22<00:12,  1.24s/batch]
Judging:  87%|████████▋ | 60/69 [01:23<00:11,  1.28s/batch]
Judging:  88%|████████▊ | 61/69 [01:24<00:09,  1.22s/batch]
Judging:  90%|████████▉ | 62/69 [01:25<00:08,  1.27s/batch]
Judging:  91%|█████████▏| 63/69 [01:26<00:07,  1.20s/batch]
Judging:  93%|█████████▎| 64/69 [01:28<00:05,  1.16s/batch]
Judging:  94%|█████████▍| 65/69 [01:29<00:04,  1.13s/batch]
Judging:  96%|█████████▌| 66/69 [01:30<00:03,  1.20s/batch]
Judging:  97%|█████████▋| 67/69 [01:31<00:02,  1.26s/batch]
Judging:  99%|█████████▊| 68/69 [01:32<00:01,  1.21s/batch]
Judging: 100%|██████████| 69/69 [01:34<00:00,  1.37s/batch]
Judging queries:  29%|██▊       | 6/21 [07:04<19:34, 78.31s/it]

  checkpoint @ query 6

Judging:   0%|          | 0/66 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/66 [00:01<01:59,  1.83s/batch]
Judging:   3%|▎         | 2/66 [00:03<01:50,  1.73s/batch]
Judging:   5%|▍         | 3/66 [00:05<01:51,  1.76s/batch]
Judging:   6%|▌         | 4/66 [00:06<01:47,  1.73s/batch]
Judging:   8%|▊         | 5/66 [00:08<01:44,  1.71s/batch]
Judging:   9%|▉         | 6/66 [00:10<01:42,  1.71s/batch]
Judging:  11%|█         | 7/66 [00:11<01:35,  1.62s/batch]
Judging:  12%|█▏        | 8/66 [00:13<01:34,  1.64s/batch]
Judging:  14%|█▎        | 9/66 [00:15<01:39,  1.75s/batch]
Judging:  15%|█▌        | 10/66 [00:17<01:38,  1.76s/batch]
Judging:  17%|█▋        | 11/66 [00:19<01:38,  1.79s/batch]
Judging:  18%|█▊        | 12/66 [00:20<01:35,  1.76s/batch]
Judging:  20%|█▉        | 13/66 [00:22<01:35,  1.81s/batch]
Judging:  21%|██        | 14/66 [00:24<01:32,  1.78s/batch]
Judging:  23%|██▎       | 15/66 [00:26<01:29,  1.75s/batch]
Judging:  24%|██▍       | 16/66 [00:27<01:27,  1.74s/batch]
Judging:  26%|██▌       | 17/66 [00:29<01:25,  1.74s/batch]
Judging:  27%|██▋       | 18/66 [00:31<01:23,  1.73s/batch]
Judging:  29%|██▉       | 19/66 [00:33<01:22,  1.76s/batch]
Judging:  30%|███       | 20/66 [00:34<01:21,  1.78s/batch]
Judging:  32%|███▏      | 21/66 [00:36<01:18,  1.74s/batch]
Judging:  33%|███▎      | 22/66 [00:38<01:17,  1.76s/batch]
Judging:  35%|███▍      | 23/66 [00:40<01:15,  1.75s/batch]
Judging:  36%|███▋      | 24/66 [00:41<01:13,  1.74s/batch]
Judging:  38%|███▊      | 25/66 [00:43<01:12,  1.77s/batch]
Judging:  39%|███▉      | 26/66 [00:44<01:05,  1.64s/batch]
Judging:  41%|████      | 27/66 [00:46<00:58,  1.50s/batch]
Judging:  42%|████▏     | 28/66 [00:47<00:55,  1.45s/batch]
Judging:  44%|████▍     | 29/66 [00:48<00:49,  1.33s/batch]
Judging:  45%|████▌     | 30/66 [00:49<00:44,  1.25s/batch]
Judging:  47%|████▋     | 31/66 [00:50<00:41,  1.19s/batch]
Judging:  48%|████▊     | 32/66 [00:52<00:43,  1.27s/batch]
Judging:  50%|█████     | 33/66 [00:53<00:39,  1.20s/batch]
Judging:  52%|█████▏    | 34/66 [00:54<00:42,  1.33s/batch]
Judging:  53%|█████▎    | 35/66 [00:56<00:42,  1.36s/batch]
Judging:  55%|█████▍    | 36/66 [00:57<00:41,  1.37s/batch]
Judging:  56%|█████▌    | 37/66 [00:59<00:40,  1.39s/batch]
Judging:  58%|█████▊    | 38/66 [01:00<00:38,  1.38s/batch]
Judging:  59%|█████▉    | 39/66 [01:01<00:34,  1.28s/batch]
Judging:  61%|██████    | 40/66 [01:02<00:34,  1.31s/batch]
Judging:  62%|██████▏   | 41/66 [01:04<00:33,  1.36s/batch]
Judging:  64%|██████▎   | 42/66 [01:05<00:31,  1.30s/batch]
Judging:  65%|██████▌   | 43/66 [01:06<00:31,  1.36s/batch]
Judging:  67%|██████▋   | 44/66 [01:08<00:30,  1.39s/batch]
Judging:  68%|██████▊   | 45/66 [01:09<00:29,  1.38s/batch]
Judging:  70%|██████▉   | 46/66 [01:11<00:27,  1.40s/batch]
Judging:  71%|███████   | 47/66 [01:12<00:26,  1.38s/batch]
Judging:  73%|███████▎  | 48/66 [01:13<00:24,  1.36s/batch]
Judging:  74%|███████▍  | 49/66 [01:14<00:21,  1.27s/batch]
Judging:  76%|███████▌  | 50/66 [01:16<00:20,  1.28s/batch]
Judging:  77%|███████▋  | 51/66 [01:17<00:18,  1.21s/batch]
Judging:  79%|███████▉  | 52/66 [01:18<00:16,  1.19s/batch]
Judging:  80%|████████  | 53/66 [01:19<00:14,  1.15s/batch]
Judging:  82%|████████▏ | 54/66 [01:20<00:13,  1.12s/batch]
Judging:  83%|████████▎ | 55/66 [01:21<00:12,  1.10s/batch]
Judging:  85%|████████▍ | 56/66 [01:22<00:10,  1.09s/batch]
Judging:  86%|████████▋ | 57/66 [01:23<00:09,  1.08s/batch]
Judging:  88%|████████▊ | 58/66 [01:24<00:08,  1.07s/batch]
Judging:  89%|████████▉ | 59/66 [01:25<00:07,  1.06s/batch]
Judging:  91%|█████████ | 60/66 [01:26<00:06,  1.06s/batch]
Judging:  92%|█████████▏| 61/66 [01:28<00:05,  1.17s/batch]
Judging:  94%|█████████▍| 62/66 [01:29<00:04,  1.23s/batch]
Judging:  95%|█████████▌| 63/66 [01:31<00:03,  1.27s/batch]
Judging:  97%|█████████▋| 64/66 [01:32<00:02,  1.31s/batch]
Judging:  98%|█████████▊| 65/66 [01:33<00:01,  1.23s/batch]
Judging: 100%|██████████| 66/66 [01:34<00:00,  1.43s/batch]
Judging queries:  33%|███▎      | 7/21 [08:39<19:28, 83.49s/it]
Judging:   0%|          | 0/50 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/50 [00:01<01:21,  1.67s/batch]
Judging:   4%|▍         | 2/50 [00:03<01:11,  1.49s/batch]
Judging:   6%|▌         | 3/50 [00:04<01:14,  1.59s/batch]
Judging:   8%|▊         | 4/50 [00:06<01:17,  1.68s/batch]
Judging:  10%|█         | 5/50 [00:08<01:14,  1.66s/batch]
Judging:  12%|█▏        | 6/50 [00:09<01:14,  1.69s/batch]
Judging:  14%|█▍        | 7/50 [00:11<01:12,  1.68s/batch]
Judging:  16%|█▌        | 8/50 [00:12<01:05,  1.57s/batch]
Judging:  18%|█▊        | 9/50 [00:13<00:57,  1.41s/batch]
Judging:  20%|██        | 10/50 [00:15<00:55,  1.38s/batch]
Judging:  22%|██▏       | 11/50 [00:16<00:49,  1.28s/batch]
Judging:  24%|██▍       | 12/50 [00:17<00:46,  1.22s/batch]
Judging:  26%|██▌       | 13/50 [00:18<00:43,  1.17s/batch]
Judging:  28%|██▊       | 14/50 [00:19<00:40,  1.13s/batch]
Judging:  30%|███       | 15/50 [00:20<00:41,  1.19s/batch]
Judging:  32%|███▏      | 16/50 [00:21<00:39,  1.15s/batch]
Judging:  34%|███▍      | 17/50 [00:22<00:37,  1.12s/batch]
Judging:  36%|███▌      | 18/50 [00:24<00:35,  1.11s/batch]
Judging:  38%|███▊      | 19/50 [00:25<00:33,  1.09s/batch]
Judging:  40%|████      | 20/50 [00:26<00:32,  1.08s/batch]
Judging:  42%|████▏     | 21/50 [00:27<00:30,  1.06s/batch]
Judging:  44%|████▍     | 22/50 [00:28<00:29,  1.06s/batch]
Judging:  46%|████▌     | 23/50 [00:29<00:28,  1.07s/batch]
Judging:  48%|████▊     | 24/50 [00:30<00:27,  1.07s/batch]
Judging:  50%|█████     | 25/50 [00:31<00:26,  1.06s/batch]
Judging:  52%|█████▏    | 26/50 [00:32<00:25,  1.06s/batch]
Judging:  54%|█████▍    | 27/50 [00:33<00:24,  1.06s/batch]
Judging:  56%|█████▌    | 28/50 [00:34<00:23,  1.06s/batch]
Judging:  58%|█████▊    | 29/50 [00:35<00:22,  1.06s/batch]
Judging:  60%|██████    | 30/50 [00:36<00:21,  1.06s/batch]
Judging:  62%|██████▏   | 31/50 [00:38<00:22,  1.16s/batch]
Judging:  64%|██████▍   | 32/50 [00:39<00:20,  1.13s/batch]
Judging:  66%|██████▌   | 33/50 [00:40<00:19,  1.14s/batch]
Judging:  68%|██████▊   | 34/50 [00:41<00:17,  1.12s/batch]
Judging:  70%|███████   | 35/50 [00:42<00:16,  1.10s/batch]
Judging:  72%|███████▏  | 36/50 [00:43<00:15,  1.09s/batch]
Judging:  74%|███████▍  | 37/50 [00:44<00:15,  1.17s/batch]
Judging:  76%|███████▌  | 38/50 [00:45<00:13,  1.13s/batch]
Judging:  78%|███████▊  | 39/50 [00:47<00:12,  1.11s/batch]
Judging:  80%|████████  | 40/50 [00:48<00:10,  1.09s/batch]
Judging:  82%|████████▏ | 41/50 [00:49<00:10,  1.11s/batch]
Judging:  84%|████████▍ | 42/50 [00:50<00:08,  1.10s/batch]
Judging:  86%|████████▌ | 43/50 [00:51<00:08,  1.17s/batch]
Judging:  88%|████████▊ | 44/50 [00:52<00:06,  1.14s/batch]
Judging:  90%|█████████ | 45/50 [00:53<00:05,  1.14s/batch]
Judging:  92%|█████████▏| 46/50 [00:54<00:04,  1.12s/batch]
Judging:  94%|█████████▍| 47/50 [00:56<00:03,  1.13s/batch]
Judging:  96%|█████████▌| 48/50 [00:57<00:02,  1.11s/batch]
Judging:  98%|█████████▊| 49/50 [00:58<00:01,  1.10s/batch]
Judging: 100%|██████████| 50/50 [00:59<00:00,  1.19s/batch]
Judging queries:  38%|███▊      | 8/21 [09:38<16:25, 75.79s/it]
Judging:   0%|          | 0/44 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/44 [00:01<01:25,  1.99s/batch]
Judging:   5%|▍         | 2/44 [00:03<01:06,  1.58s/batch]
Judging:   7%|▋         | 3/44 [00:04<00:59,  1.45s/batch]
Judging:   9%|▉         | 4/44 [00:05<00:56,  1.41s/batch]
Judging:  11%|█▏        | 5/44 [00:06<00:50,  1.28s/batch]
Judging:  14%|█▎        | 6/44 [00:08<00:45,  1.21s/batch]
Judging:  16%|█▌        | 7/44 [00:09<00:42,  1.16s/batch]
Judging:  18%|█▊        | 8/44 [00:10<00:40,  1.12s/batch]
Judging:  20%|██        | 9/44 [00:11<00:41,  1.18s/batch]
Judging:  23%|██▎       | 10/44 [00:12<00:42,  1.25s/batch]
Judging:  25%|██▌       | 11/44 [00:13<00:39,  1.19s/batch]
Judging:  27%|██▋       | 12/44 [00:15<00:39,  1.25s/batch]
Judging:  30%|██▉       | 13/44 [00:16<00:36,  1.19s/batch]
Judging:  32%|███▏      | 14/44 [00:17<00:37,  1.26s/batch]
Judging:  34%|███▍      | 15/44 [00:18<00:34,  1.19s/batch]
Judging:  36%|███▋      | 16/44 [00:20<00:34,  1.23s/batch]
Judging:  39%|███▊      | 17/44 [00:21<00:33,  1.25s/batch]
Judging:  41%|████      | 18/44 [00:22<00:33,  1.29s/batch]
Judging:  43%|████▎     | 19/44 [00:24<00:33,  1.34s/batch]
Judging:  45%|████▌     | 20/44 [00:25<00:29,  1.25s/batch]
Judging:  48%|████▊     | 21/44 [00:26<00:27,  1.20s/batch]
Judging:  50%|█████     | 22/44 [00:27<00:27,  1.26s/batch]
Judging:  52%|█████▏    | 23/44 [00:28<00:25,  1.19s/batch]
Judging:  55%|█████▍    | 24/44 [00:29<00:23,  1.15s/batch]
Judging:  57%|█████▋    | 25/44 [00:31<00:23,  1.24s/batch]
Judging:  59%|█████▉    | 26/44 [00:32<00:21,  1.18s/batch]
Judging:  61%|██████▏   | 27/44 [00:33<00:19,  1.14s/batch]
Judging:  64%|██████▎   | 28/44 [00:34<00:17,  1.11s/batch]
Judging:  66%|██████▌   | 29/44 [00:35<00:16,  1.10s/batch]
Judging:  68%|██████▊   | 30/44 [00:36<00:15,  1.09s/batch]
Judging:  70%|███████   | 31/44 [00:37<00:14,  1.08s/batch]
Judging:  73%|███████▎  | 32/44 [00:38<00:13,  1.16s/batch]
Judging:  75%|███████▌  | 33/44 [00:40<00:12,  1.13s/batch]
Judging:  77%|███████▋  | 34/44 [00:41<00:11,  1.11s/batch]
Judging:  80%|███████▉  | 35/44 [00:42<00:09,  1.10s/batch]
Judging:  82%|████████▏ | 36/44 [00:43<00:08,  1.08s/batch]
Judging:  84%|████████▍ | 37/44 [00:44<00:07,  1.08s/batch]
Judging:  86%|████████▋ | 38/44 [00:45<00:06,  1.08s/batch]
Judging:  89%|████████▊ | 39/44 [00:46<00:05,  1.08s/batch]
Judging:  91%|█████████ | 40/44 [00:47<00:04,  1.16s/batch]
Judging:  93%|█████████▎| 41/44 [00:48<00:03,  1.14s/batch]
Judging:  95%|█████████▌| 42/44 [00:50<00:02,  1.23s/batch]
Judging:  98%|█████████▊| 43/44 [00:51<00:01,  1.17s/batch]
Judging: 100%|██████████| 44/44 [00:52<00:00,  1.20s/batch]
Judging queries:  43%|████▎     | 9/21 [10:31<13:43, 68.58s/it]

  checkpoint @ query 9

Judging:   0%|          | 0/62 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/62 [00:01<01:43,  1.70s/batch]
Judging:   3%|▎         | 2/62 [00:03<01:46,  1.78s/batch]
Judging:   5%|▍         | 3/62 [00:05<01:42,  1.73s/batch]
Judging:   6%|▋         | 4/62 [00:06<01:39,  1.72s/batch]
Judging:   8%|▊         | 5/62 [00:08<01:39,  1.74s/batch]
Judging:  10%|▉         | 6/62 [00:10<01:34,  1.68s/batch]
Judging:  11%|█▏        | 7/62 [00:12<01:38,  1.78s/batch]
Judging:  13%|█▎        | 8/62 [00:13<01:33,  1.74s/batch]
Judging:  15%|█▍        | 9/62 [00:15<01:31,  1.72s/batch]
Judging:  16%|█▌        | 10/62 [00:17<01:30,  1.74s/batch]
Judging:  18%|█▊        | 11/62 [00:19<01:27,  1.71s/batch]
Judging:  19%|█▉        | 12/62 [00:20<01:25,  1.71s/batch]
Judging:  21%|██        | 13/62 [00:22<01:26,  1.76s/batch]
Judging:  23%|██▎       | 14/62 [00:24<01:23,  1.74s/batch]
Judging:  24%|██▍       | 15/62 [00:25<01:21,  1.73s/batch]
Judging:  26%|██▌       | 16/62 [00:27<01:20,  1.76s/batch]
Judging:  27%|██▋       | 17/62 [00:29<01:18,  1.74s/batch]
Judging:  29%|██▉       | 18/62 [00:31<01:20,  1.82s/batch]
Judging:  31%|███       | 19/62 [00:33<01:16,  1.79s/batch]
Judging:  32%|███▏      | 20/62 [00:34<01:12,  1.73s/batch]
Judging:  34%|███▍      | 21/62 [00:36<01:06,  1.62s/batch]
Judging:  35%|███▌      | 22/62 [00:37<00:57,  1.45s/batch]
Judging:  37%|███▋      | 23/62 [00:38<00:54,  1.41s/batch]
Judging:  39%|███▊      | 24/62 [00:39<00:49,  1.30s/batch]
Judging:  40%|████      | 25/62 [00:40<00:45,  1.23s/batch]
Judging:  42%|████▏     | 26/62 [00:41<00:45,  1.25s/batch]
Judging:  44%|████▎     | 27/62 [00:43<00:41,  1.19s/batch]
Judging:  45%|████▌     | 28/62 [00:44<00:42,  1.26s/batch]
Judging:  47%|████▋     | 29/62 [00:45<00:43,  1.31s/batch]
Judging:  48%|████▊     | 30/62 [00:47<00:42,  1.31s/batch]
Judging:  50%|█████     | 31/62 [00:48<00:40,  1.32s/batch]
Judging:  52%|█████▏    | 32/62 [00:49<00:37,  1.25s/batch]
Judging:  53%|█████▎    | 33/62 [00:51<00:38,  1.33s/batch]
Judging:  55%|█████▍    | 34/62 [00:52<00:37,  1.34s/batch]
Judging:  56%|█████▋    | 35/62 [00:53<00:36,  1.36s/batch]
Judging:  58%|█████▊    | 36/62 [00:55<00:35,  1.37s/batch]
Judging:  60%|█████▉    | 37/62 [00:56<00:34,  1.39s/batch]
Judging:  61%|██████▏   | 38/62 [00:58<00:32,  1.36s/batch]
Judging:  63%|██████▎   | 39/62 [00:59<00:29,  1.27s/batch]
Judging:  65%|██████▍   | 40/62 [01:00<00:26,  1.21s/batch]
Judging:  66%|██████▌   | 41/62 [01:01<00:26,  1.25s/batch]
Judging:  68%|██████▊   | 42/62 [01:02<00:25,  1.28s/batch]
Judging:  69%|██████▉   | 43/62 [01:04<00:25,  1.33s/batch]
Judging:  71%|███████   | 44/62 [01:05<00:24,  1.35s/batch]
Judging:  73%|███████▎  | 45/62 [01:06<00:21,  1.26s/batch]
Judging:  74%|███████▍  | 46/62 [01:07<00:19,  1.20s/batch]
Judging:  76%|███████▌  | 47/62 [01:08<00:17,  1.15s/batch]
Judging:  77%|███████▋  | 48/62 [01:09<00:15,  1.13s/batch]
Judging:  79%|███████▉  | 49/62 [01:11<00:15,  1.20s/batch]
Judging:  81%|████████  | 50/62 [01:12<00:13,  1.15s/batch]
Judging:  82%|████████▏ | 51/62 [01:13<00:12,  1.13s/batch]
Judging:  84%|████████▍ | 52/62 [01:14<00:11,  1.11s/batch]
Judging:  85%|████████▌ | 53/62 [01:15<00:09,  1.09s/batch]
Judging:  87%|████████▋ | 54/62 [01:16<00:08,  1.08s/batch]
Judging:  89%|████████▊ | 55/62 [01:17<00:07,  1.11s/batch]
Judging:  90%|█████████ | 56/62 [01:18<00:06,  1.09s/batch]
Judging:  92%|█████████▏| 57/62 [01:20<00:05,  1.17s/batch]
Judging:  94%|█████████▎| 58/62 [01:21<00:04,  1.13s/batch]
Judging:  95%|█████████▌| 59/62 [01:22<00:03,  1.23s/batch]
Judging:  97%|█████████▋| 60/62 [01:23<00:02,  1.16s/batch]
Judging:  98%|█████████▊| 61/62 [01:25<00:01,  1.22s/batch]
Judging: 100%|██████████| 62/62 [01:25<00:00,  1.38s/batch]
Judging queries:  48%|████▊     | 10/21 [11:56<13:31, 73.76s/it]
Judging:   0%|          | 0/69 [00:00<?, ?batch/s]
Judging:   1%|▏         | 1/69 [00:01<01:52,  1.66s/batch]
Judging:   3%|▎         | 2/69 [00:03<01:51,  1.67s/batch]
Judging:   4%|▍         | 3/69 [00:05<01:50,  1.67s/batch]
Judging:   6%|▌         | 4/69 [00:06<01:45,  1.62s/batch]
Judging:   7%|▋         | 5/69 [00:08<01:45,  1.65s/batch]
Judging:   9%|▊         | 6/69 [00:10<01:46,  1.69s/batch]
Judging:  10%|█         | 7/69 [00:11<01:44,  1.68s/batch]
Judging:  12%|█▏        | 8/69 [00:13<01:40,  1.64s/batch]
Judging:  13%|█▎        | 9/69 [00:14<01:39,  1.66s/batch]
Judging:  14%|█▍        | 10/69 [00:16<01:37,  1.65s/batch]
Judging:  16%|█▌        | 11/69 [00:18<01:38,  1.71s/batch]
Judging:  17%|█▋        | 12/69 [00:20<01:37,  1.70s/batch]
Judging:  19%|█▉        | 13/69 [00:21<01:34,  1.69s/batch]
Judging:  20%|██        | 14/69 [00:23<01:33,  1.69s/batch]
Judging:  22%|██▏       | 15/69 [00:24<01:28,  1.65s/batch]
Judging:  23%|██▎       | 16/69 [00:26<01:28,  1.67s/batch]
Judging:  25%|██▍       | 17/69 [00:28<01:25,  1.64s/batch]
Judging:  26%|██▌       | 18/69 [00:30<01:24,  1.66s/batch]
Judging:  28%|██▊       | 19/69 [00:31<01:23,  1.67s/batch]
Judging:  29%|██▉       | 20/69 [00:33<01:21,  1.67s/batch]
Judging:  30%|███       | 21/69 [00:35<01:21,  1.70s/batch]
Judging:  32%|███▏      | 22/69 [00:36<01:21,  1.73s/batch]
Judging:  33%|███▎      | 23/69 [00:38<01:18,  1.72s/batch]
Judging:  35%|███▍      | 24/69 [00:40<01:13,  1.64s/batch]
Judging:  36%|███▌      | 25/69 [00:41<01:10,  1.60s/batch]
Judging:  38%|███▊      | 26/69 [00:42<01:01,  1.44s/batch]
Judging:  39%|███▉      | 27/69 [00:43<00:55,  1.32s/batch]
Judging:  41%|████      | 28/69 [00:44<00:50,  1.24s/batch]
Judging:  42%|████▏     | 29/69 [00:45<00:47,  1.18s/batch]
Judging:  43%|████▎     | 30/69 [00:46<00:44,  1.14s/batch]
Judging:  45%|████▍     | 31/69 [00:48<00:45,  1.19s/batch]
Judging:  46%|████▋     | 32/69 [00:49<00:42,  1.15s/batch]
Judging:  48%|████▊     | 33/69 [00:50<00:40,  1.11s/batch]
Judging:  49%|████▉     | 34/69 [00:51<00:38,  1.09s/batch]
Judging:  51%|█████     | 35/69 [00:52<00:36,  1.08s/batch]
Judging:  52%|█████▏    | 36/69 [00:53<00:35,  1.07s/batch]
Judging:  54%|█████▎    | 37/69 [00:54<00:34,  1.07s/batch]
Judging:  55%|█████▌    | 38/69 [00:55<00:33,  1.07s/batch]
Judging:  57%|█████▋    | 39/69 [00:56<00:31,  1.06s/batch]
Judging:  58%|█████▊    | 40/69 [00:57<00:30,  1.07s/batch]
Judging:  59%|█████▉    | 41/69 [00:58<00:31,  1.14s/batch]
Judging:  61%|██████    | 42/69 [01:00<00:30,  1.12s/batch]
Judging:  62%|██████▏   | 43/69 [01:01<00:28,  1.11s/batch]
Judging:  64%|██████▍   | 44/69 [01:02<00:29,  1.18s/batch]
Judging:  65%|██████▌   | 45/69 [01:03<00:27,  1.14s/batch]
Judging:  67%|██████▋   | 46/69 [01:04<00:25,  1.12s/batch]
Judging:  68%|██████▊   | 47/69 [01:05<00:24,  1.09s/batch]
Judging:  70%|██████▉   | 48/69 [01:06<00:22,  1.08s/batch]
Judging:  71%|███████   | 49/69 [01:07<00:21,  1.08s/batch]
Judging:  72%|███████▏  | 50/69 [01:08<00:20,  1.07s/batch]
Judging:  74%|███████▍  | 51/69 [01:09<00:19,  1.06s/batch]
Judging:  75%|███████▌  | 52/69 [01:10<00:18,  1.09s/batch]
Judging:  77%|███████▋  | 53/69 [01:11<00:17,  1.08s/batch]
Judging:  78%|███████▊  | 54/69 [01:13<00:16,  1.07s/batch]
Judging:  80%|███████▉  | 55/69 [01:14<00:14,  1.07s/batch]
Judging:  81%|████████  | 56/69 [01:15<00:13,  1.06s/batch]
Judging:  83%|████████▎ | 57/69 [01:16<00:12,  1.06s/batch]
Judging:  84%|████████▍ | 58/69 [01:17<00:11,  1.06s/batch]
Judging:  86%|████████▌ | 59/69 [01:18<00:10,  1.09s/batch]
Judging:  87%|████████▋ | 60/69 [01:19<00:09,  1.11s/batch]
Judging:  88%|████████▊ | 61/69 [01:20<00:09,  1.17s/batch]
Judging:  90%|████████▉ | 62/69 [01:21<00:07,  1.14s/batch]
Judging:  91%|█████████▏| 63/69 [01:23<00:06,  1.12s/batch]
Judging:  93%|█████████▎| 64/69 [01:24<00:05,  1.10s/batch]
Judging:  94%|█████████▍| 65/69 [01:25<00:04,  1.09s/batch]
Judging:  96%|█████████▌| 66/69 [01:26<00:03,  1.10s/batch]
Judging:  97%|█████████▋| 67/69 [01:27<00:02,  1.09s/batch]
Judging:  99%|█████████▊| 68/69 [01:28<00:01,  1.08s/batch]
Judging: 100%|██████████| 69/69 [01:28<00:00,  1.29s/batch]
Judging queries:  52%|█████▏    | 11/21 [13:25<13:03, 78.39s/it]
Judging:   0%|          | 0/48 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/48 [00:01<00:49,  1.04s/batch]
Judging:   4%|▍         | 2/48 [00:02<01:08,  1.49s/batch]
Judging:   6%|▋         | 3/48 [00:04<01:13,  1.63s/batch]
Judging:   8%|▊         | 4/48 [00:06<01:13,  1.66s/batch]
Judging:  10%|█         | 5/48 [00:08<01:11,  1.66s/batch]
Judging:  12%|█▎        | 6/48 [00:09<01:00,  1.45s/batch]
Judging:  15%|█▍        | 7/48 [00:10<00:53,  1.32s/batch]
Judging:  17%|█▋        | 8/48 [00:11<00:49,  1.23s/batch]
Judging:  19%|█▉        | 9/48 [00:12<00:45,  1.17s/batch]
Judging:  21%|██        | 10/48 [00:13<00:43,  1.13s/batch]
Judging:  23%|██▎       | 11/48 [00:14<00:41,  1.11s/batch]
Judging:  25%|██▌       | 12/48 [00:15<00:39,  1.09s/batch]
Judging:  27%|██▋       | 13/48 [00:16<00:37,  1.08s/batch]
Judging:  29%|██▉       | 14/48 [00:17<00:36,  1.07s/batch]
Judging:  31%|███▏      | 15/48 [00:18<00:35,  1.06s/batch]
Judging:  33%|███▎      | 16/48 [00:19<00:34,  1.07s/batch]
Judging:  35%|███▌      | 17/48 [00:20<00:32,  1.06s/batch]
Judging:  38%|███▊      | 18/48 [00:21<00:32,  1.07s/batch]
Judging:  40%|███▉      | 19/48 [00:22<00:31,  1.08s/batch]
Judging:  42%|████▏     | 20/48 [00:23<00:30,  1.09s/batch]
Judging:  44%|████▍     | 21/48 [00:24<00:28,  1.07s/batch]
Judging:  46%|████▌     | 22/48 [00:25<00:27,  1.06s/batch]
Judging:  48%|████▊     | 23/48 [00:27<00:26,  1.06s/batch]
Judging:  50%|█████     | 24/48 [00:28<00:25,  1.05s/batch]
Judging:  52%|█████▏    | 25/48 [00:29<00:24,  1.05s/batch]
Judging:  54%|█████▍    | 26/48 [00:30<00:23,  1.05s/batch]
Judging:  56%|█████▋    | 27/48 [00:31<00:22,  1.06s/batch]
Judging:  58%|█████▊    | 28/48 [00:32<00:21,  1.06s/batch]
Judging:  60%|██████    | 29/48 [00:33<00:20,  1.06s/batch]
Judging:  62%|██████▎   | 30/48 [00:34<00:19,  1.06s/batch]
Judging:  65%|██████▍   | 31/48 [00:35<00:17,  1.06s/batch]
Judging:  67%|██████▋   | 32/48 [00:36<00:17,  1.09s/batch]
Judging:  69%|██████▉   | 33/48 [00:37<00:16,  1.09s/batch]
Judging:  71%|███████   | 34/48 [00:38<00:15,  1.08s/batch]
Judging:  73%|███████▎  | 35/48 [00:39<00:14,  1.08s/batch]
Judging:  75%|███████▌  | 36/48 [00:41<00:13,  1.16s/batch]
Judging:  77%|███████▋  | 37/48 [00:42<00:12,  1.16s/batch]
Judging:  79%|███████▉  | 38/48 [00:43<00:11,  1.17s/batch]
Judging:  81%|████████▏ | 39/48 [00:44<00:10,  1.14s/batch]
Judging:  83%|████████▎ | 40/48 [00:45<00:08,  1.11s/batch]
Judging:  85%|████████▌ | 41/48 [00:46<00:07,  1.10s/batch]
Judging:  88%|████████▊ | 42/48 [00:47<00:06,  1.11s/batch]
Judging:  90%|████████▉ | 43/48 [00:48<00:05,  1.10s/batch]
Judging:  92%|█████████▏| 44/48 [00:50<00:04,  1.09s/batch]
Judging:  94%|█████████▍| 45/48 [00:51<00:03,  1.08s/batch]
Judging:  96%|█████████▌| 46/48 [00:52<00:02,  1.07s/batch]
Judging:  98%|█████████▊| 47/48 [00:53<00:01,  1.15s/batch]
Judging: 100%|██████████| 48/48 [00:54<00:00,  1.13s/batch]
Judging queries:  57%|█████▋    | 12/21 [14:19<10:39, 71.02s/it]

  checkpoint @ query 12

Judging:   0%|          | 0/65 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/65 [00:01<01:58,  1.85s/batch]
Judging:   3%|▎         | 2/65 [00:03<01:50,  1.75s/batch]
Judging:   5%|▍         | 3/65 [00:05<01:49,  1.76s/batch]
Judging:   6%|▌         | 4/65 [00:06<01:45,  1.73s/batch]
Judging:   8%|▊         | 5/65 [00:08<01:42,  1.71s/batch]
Judging:   9%|▉         | 6/65 [00:10<01:42,  1.74s/batch]
Judging:  11%|█         | 7/65 [00:11<01:35,  1.65s/batch]
Judging:  12%|█▏        | 8/65 [00:13<01:34,  1.65s/batch]
Judging:  14%|█▍        | 9/65 [00:15<01:38,  1.76s/batch]
Judging:  15%|█▌        | 10/65 [00:17<01:37,  1.77s/batch]
Judging:  17%|█▋        | 11/65 [00:19<01:37,  1.81s/batch]
Judging:  18%|█▊        | 12/65 [00:20<01:34,  1.77s/batch]
Judging:  20%|██        | 13/65 [00:22<01:34,  1.83s/batch]
Judging:  22%|██▏       | 14/65 [00:24<01:31,  1.79s/batch]
Judging:  23%|██▎       | 15/65 [00:26<01:28,  1.76s/batch]
Judging:  25%|██▍       | 16/65 [00:27<01:25,  1.74s/batch]
Judging:  26%|██▌       | 17/65 [00:29<01:23,  1.73s/batch]
Judging:  28%|██▊       | 18/65 [00:31<01:21,  1.73s/batch]
Judging:  29%|██▉       | 19/65 [00:33<01:20,  1.75s/batch]
Judging:  31%|███       | 20/65 [00:35<01:19,  1.77s/batch]
Judging:  32%|███▏      | 21/65 [00:36<01:16,  1.74s/batch]
Judging:  34%|███▍      | 22/65 [00:38<01:15,  1.75s/batch]
Judging:  35%|███▌      | 23/65 [00:40<01:12,  1.73s/batch]
Judging:  37%|███▋      | 24/65 [00:41<01:10,  1.73s/batch]
Judging:  38%|███▊      | 25/65 [00:43<01:11,  1.78s/batch]
Judging:  40%|████      | 26/65 [00:45<01:03,  1.64s/batch]
Judging:  42%|████▏     | 27/65 [00:46<00:58,  1.55s/batch]
Judging:  43%|████▎     | 28/65 [00:47<00:52,  1.43s/batch]
Judging:  45%|████▍     | 29/65 [00:48<00:50,  1.41s/batch]
Judging:  46%|████▌     | 30/65 [00:50<00:45,  1.31s/batch]
Judging:  48%|████▊     | 31/65 [00:51<00:41,  1.24s/batch]
Judging:  49%|████▉     | 32/65 [00:52<00:42,  1.28s/batch]
Judging:  51%|█████     | 33/65 [00:53<00:42,  1.33s/batch]
Judging:  52%|█████▏    | 34/65 [00:54<00:38,  1.25s/batch]
Judging:  54%|█████▍    | 35/65 [00:56<00:39,  1.31s/batch]
Judging:  55%|█████▌    | 36/65 [00:58<00:40,  1.41s/batch]
Judging:  57%|█████▋    | 37/65 [00:59<00:39,  1.40s/batch]
Judging:  58%|█████▊    | 38/65 [01:00<00:34,  1.30s/batch]
Judging:  60%|██████    | 39/65 [01:01<00:31,  1.23s/batch]
Judging:  62%|██████▏   | 40/65 [01:02<00:29,  1.18s/batch]
Judging:  63%|██████▎   | 41/65 [01:04<00:30,  1.29s/batch]
Judging:  65%|██████▍   | 42/65 [01:05<00:30,  1.32s/batch]
Judging:  66%|██████▌   | 43/65 [01:07<00:29,  1.36s/batch]
Judging:  68%|██████▊   | 44/65 [01:08<00:29,  1.39s/batch]
Judging:  69%|██████▉   | 45/65 [01:09<00:25,  1.29s/batch]
Judging:  71%|███████   | 46/65 [01:10<00:23,  1.22s/batch]
Judging:  72%|███████▏  | 47/65 [01:12<00:22,  1.28s/batch]
Judging:  74%|███████▍  | 48/65 [01:13<00:22,  1.31s/batch]
Judging:  75%|███████▌  | 49/65 [01:14<00:19,  1.23s/batch]
Judging:  77%|███████▋  | 50/65 [01:15<00:17,  1.18s/batch]
Judging:  78%|███████▊  | 51/65 [01:16<00:17,  1.23s/batch]
Judging:  80%|████████  | 52/65 [01:17<00:15,  1.18s/batch]
Judging:  82%|████████▏ | 53/65 [01:19<00:14,  1.23s/batch]
Judging:  83%|████████▎ | 54/65 [01:20<00:12,  1.18s/batch]
Judging:  85%|████████▍ | 55/65 [01:21<00:12,  1.22s/batch]
Judging:  86%|████████▌ | 56/65 [01:22<00:10,  1.18s/batch]
Judging:  88%|████████▊ | 57/65 [01:23<00:09,  1.14s/batch]
Judging:  89%|████████▉ | 58/65 [01:24<00:08,  1.15s/batch]
Judging:  91%|█████████ | 59/65 [01:26<00:07,  1.24s/batch]
Judging:  92%|█████████▏| 60/65 [01:27<00:05,  1.19s/batch]
Judging:  94%|█████████▍| 61/65 [01:28<00:04,  1.24s/batch]
Judging:  95%|█████████▌| 62/65 [01:29<00:03,  1.19s/batch]
Judging:  97%|█████████▋| 63/65 [01:30<00:02,  1.15s/batch]
Judging:  98%|█████████▊| 64/65 [01:32<00:01,  1.21s/batch]
Judging: 100%|██████████| 65/65 [01:33<00:00,  1.43s/batch]
Judging queries:  62%|██████▏   | 13/21 [15:52<10:21, 77.73s/it]
Judging:   0%|          | 0/61 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/61 [00:01<01:34,  1.58s/batch]
Judging:   3%|▎         | 2/61 [00:03<01:40,  1.71s/batch]
Judging:   5%|▍         | 3/61 [00:04<01:35,  1.65s/batch]
Judging:   7%|▋         | 4/61 [00:06<01:34,  1.66s/batch]
Judging:   8%|▊         | 5/61 [00:08<01:35,  1.70s/batch]
Judging:  10%|▉         | 6/61 [00:09<01:31,  1.66s/batch]
Judging:  11%|█▏        | 7/61 [00:11<01:35,  1.77s/batch]
Judging:  13%|█▎        | 8/61 [00:13<01:30,  1.71s/batch]
Judging:  15%|█▍        | 9/61 [00:15<01:28,  1.70s/batch]
Judging:  16%|█▋        | 10/61 [00:16<01:26,  1.71s/batch]
Judging:  18%|█▊        | 11/61 [00:18<01:24,  1.69s/batch]
Judging:  20%|█▉        | 12/61 [00:20<01:22,  1.69s/batch]
Judging:  21%|██▏       | 13/61 [00:22<01:24,  1.76s/batch]
Judging:  23%|██▎       | 14/61 [00:23<01:21,  1.74s/batch]
Judging:  25%|██▍       | 15/61 [00:25<01:19,  1.73s/batch]
Judging:  26%|██▌       | 16/61 [00:27<01:19,  1.77s/batch]
Judging:  28%|██▊       | 17/61 [00:29<01:17,  1.75s/batch]
Judging:  30%|██▉       | 18/61 [00:31<01:18,  1.83s/batch]
Judging:  31%|███       | 19/61 [00:32<01:15,  1.79s/batch]
Judging:  33%|███▎      | 20/61 [00:34<01:11,  1.74s/batch]
Judging:  34%|███▍      | 21/61 [00:35<01:04,  1.62s/batch]
Judging:  36%|███▌      | 22/61 [00:36<00:56,  1.45s/batch]
Judging:  38%|███▊      | 23/61 [00:37<00:50,  1.33s/batch]
Judging:  39%|███▉      | 24/61 [00:39<00:46,  1.25s/batch]
Judging:  41%|████      | 25/61 [00:40<00:45,  1.27s/batch]
Judging:  43%|████▎     | 26/61 [00:41<00:42,  1.20s/batch]
Judging:  44%|████▍     | 27/61 [00:42<00:39,  1.16s/batch]
Judging:  46%|████▌     | 28/61 [00:43<00:37,  1.12s/batch]
Judging:  48%|████▊     | 29/61 [00:44<00:38,  1.19s/batch]
Judging:  49%|████▉     | 30/61 [00:45<00:35,  1.15s/batch]
Judging:  51%|█████     | 31/61 [00:46<00:33,  1.12s/batch]
Judging:  52%|█████▏    | 32/61 [00:47<00:31,  1.10s/batch]
Judging:  54%|█████▍    | 33/61 [00:49<00:30,  1.09s/batch]
Judging:  56%|█████▌    | 34/61 [00:50<00:29,  1.09s/batch]
Judging:  57%|█████▋    | 35/61 [00:51<00:30,  1.19s/batch]
Judging:  59%|█████▉    | 36/61 [00:52<00:31,  1.26s/batch]
Judging:  61%|██████    | 37/61 [00:54<00:28,  1.19s/batch]
Judging:  62%|██████▏   | 38/61 [00:55<00:26,  1.16s/batch]
Judging:  64%|██████▍   | 39/61 [00:56<00:24,  1.14s/batch]
Judging:  66%|██████▌   | 40/61 [00:57<00:23,  1.11s/batch]
Judging:  67%|██████▋   | 41/61 [00:58<00:22,  1.12s/batch]
Judging:  69%|██████▉   | 42/61 [00:59<00:22,  1.18s/batch]
Judging:  70%|███████   | 43/61 [01:00<00:20,  1.15s/batch]
Judging:  72%|███████▏  | 44/61 [01:01<00:19,  1.12s/batch]
Judging:  74%|███████▍  | 45/61 [01:02<00:17,  1.09s/batch]
Judging:  75%|███████▌  | 46/61 [01:03<00:16,  1.08s/batch]
Judging:  77%|███████▋  | 47/61 [01:04<00:15,  1.07s/batch]
Judging:  79%|███████▊  | 48/61 [01:06<00:14,  1.09s/batch]
Judging:  80%|████████  | 49/61 [01:07<00:12,  1.07s/batch]
Judging:  82%|████████▏ | 50/61 [01:08<00:11,  1.08s/batch]
Judging:  84%|████████▎ | 51/61 [01:09<00:10,  1.08s/batch]
Judging:  85%|████████▌ | 52/61 [01:10<00:09,  1.06s/batch]
Judging:  87%|████████▋ | 53/61 [01:11<00:09,  1.15s/batch]
Judging:  89%|████████▊ | 54/61 [01:12<00:07,  1.12s/batch]
Judging:  90%|█████████ | 55/61 [01:14<00:07,  1.18s/batch]
Judging:  92%|█████████▏| 56/61 [01:15<00:05,  1.14s/batch]
Judging:  93%|█████████▎| 57/61 [01:16<00:04,  1.14s/batch]
Judging:  95%|█████████▌| 58/61 [01:17<00:03,  1.15s/batch]
Judging:  97%|█████████▋| 59/61 [01:18<00:02,  1.12s/batch]
Judging:  98%|█████████▊| 60/61 [01:19<00:01,  1.10s/batch]
Judging: 100%|██████████| 61/61 [01:20<00:00,  1.31s/batch]
Judging queries:  67%|██████▋   | 14/21 [17:12<09:09, 78.48s/it]
Judging:   0%|          | 0/60 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/60 [00:01<01:33,  1.59s/batch]
Judging:   3%|▎         | 2/60 [00:03<01:31,  1.58s/batch]
Judging:   5%|▌         | 3/60 [00:04<01:35,  1.68s/batch]
Judging:   7%|▋         | 4/60 [00:06<01:34,  1.68s/batch]
Judging:   8%|▊         | 5/60 [00:08<01:33,  1.70s/batch]
Judging:  10%|█         | 6/60 [00:09<01:29,  1.65s/batch]
Judging:  12%|█▏        | 7/60 [00:11<01:31,  1.73s/batch]
Judging:  13%|█▎        | 8/60 [00:13<01:26,  1.67s/batch]
Judging:  15%|█▌        | 9/60 [00:15<01:25,  1.67s/batch]
Judging:  17%|█▋        | 10/60 [00:16<01:24,  1.68s/batch]
Judging:  18%|█▊        | 11/60 [00:18<01:21,  1.67s/batch]
Judging:  20%|██        | 12/60 [00:20<01:20,  1.68s/batch]
Judging:  22%|██▏       | 13/60 [00:21<01:17,  1.64s/batch]
Judging:  23%|██▎       | 14/60 [00:23<01:18,  1.72s/batch]
Judging:  25%|██▌       | 15/60 [00:25<01:17,  1.72s/batch]
Judging:  27%|██▋       | 16/60 [00:27<01:17,  1.76s/batch]
Judging:  28%|██▊       | 17/60 [00:28<01:15,  1.75s/batch]
Judging:  30%|███       | 18/60 [00:30<01:11,  1.70s/batch]
Judging:  32%|███▏      | 19/60 [00:32<01:13,  1.80s/batch]
Judging:  33%|███▎      | 20/60 [00:34<01:09,  1.75s/batch]
Judging:  35%|███▌      | 21/60 [00:35<01:00,  1.54s/batch]
Judging:  37%|███▋      | 22/60 [00:36<00:52,  1.39s/batch]
Judging:  38%|███▊      | 23/60 [00:37<00:50,  1.37s/batch]
Judging:  40%|████      | 24/60 [00:38<00:45,  1.28s/batch]
Judging:  42%|████▏     | 25/60 [00:39<00:42,  1.21s/batch]
Judging:  43%|████▎     | 26/60 [00:40<00:39,  1.17s/batch]
Judging:  45%|████▌     | 27/60 [00:41<00:37,  1.14s/batch]
Judging:  47%|████▋     | 28/60 [00:42<00:35,  1.11s/batch]
Judging:  48%|████▊     | 29/60 [00:44<00:36,  1.18s/batch]
Judging:  50%|█████     | 30/60 [00:45<00:34,  1.14s/batch]
Judging:  52%|█████▏    | 31/60 [00:46<00:32,  1.12s/batch]
Judging:  53%|█████▎    | 32/60 [00:47<00:30,  1.09s/batch]
Judging:  55%|█████▌    | 33/60 [00:48<00:31,  1.17s/batch]
Judging:  57%|█████▋    | 34/60 [00:49<00:29,  1.13s/batch]
Judging:  58%|█████▊    | 35/60 [00:50<00:28,  1.13s/batch]
Judging:  60%|██████    | 36/60 [00:51<00:26,  1.10s/batch]
Judging:  62%|██████▏   | 37/60 [00:52<00:24,  1.09s/batch]
Judging:  63%|██████▎   | 38/60 [00:53<00:23,  1.08s/batch]
Judging:  65%|██████▌   | 39/60 [00:55<00:24,  1.15s/batch]
Judging:  67%|██████▋   | 40/60 [00:56<00:22,  1.12s/batch]
Judging:  68%|██████▊   | 41/60 [00:57<00:22,  1.18s/batch]
Judging:  70%|███████   | 42/60 [00:58<00:20,  1.14s/batch]
Judging:  72%|███████▏  | 43/60 [00:59<00:18,  1.11s/batch]
Judging:  73%|███████▎  | 44/60 [01:00<00:17,  1.10s/batch]
Judging:  75%|███████▌  | 45/60 [01:01<00:16,  1.07s/batch]
Judging:  77%|███████▋  | 46/60 [01:02<00:14,  1.06s/batch]
Judging:  78%|███████▊  | 47/60 [01:03<00:13,  1.06s/batch]
Judging:  80%|████████  | 48/60 [01:05<00:13,  1.09s/batch]
Judging:  82%|████████▏ | 49/60 [01:06<00:11,  1.08s/batch]
Judging:  83%|████████▎ | 50/60 [01:07<00:10,  1.08s/batch]
Judging:  85%|████████▌ | 51/60 [01:08<00:10,  1.16s/batch]
Judging:  87%|████████▋ | 52/60 [01:09<00:09,  1.14s/batch]
Judging:  88%|████████▊ | 53/60 [01:10<00:07,  1.12s/batch]
Judging:  90%|█████████ | 54/60 [01:11<00:06,  1.11s/batch]
Judging:  92%|█████████▏| 55/60 [01:12<00:05,  1.10s/batch]
Judging:  93%|█████████▎| 56/60 [01:13<00:04,  1.09s/batch]
Judging:  95%|█████████▌| 57/60 [01:15<00:03,  1.11s/batch]
Judging:  97%|█████████▋| 58/60 [01:16<00:02,  1.10s/batch]
Judging:  98%|█████████▊| 59/60 [01:17<00:01,  1.08s/batch]
Judging: 100%|██████████| 60/60 [01:17<00:00,  1.29s/batch]
Judging queries:  71%|███████▏  | 15/21 [18:30<07:49, 78.21s/it]

  checkpoint @ query 15

Judging:   0%|          | 0/40 [00:00<?, ?batch/s]
Judging:   2%|▎         | 1/40 [00:02<01:19,  2.03s/batch]
Judging:   5%|▌         | 2/40 [00:03<00:55,  1.45s/batch]
Judging:   8%|▊         | 3/40 [00:04<00:46,  1.26s/batch]
Judging:  10%|█         | 4/40 [00:05<00:42,  1.18s/batch]
Judging:  12%|█▎        | 5/40 [00:06<00:39,  1.13s/batch]
Judging:  15%|█▌        | 6/40 [00:07<00:37,  1.10s/batch]
Judging:  18%|█▊        | 7/40 [00:08<00:35,  1.08s/batch]
Judging:  20%|██        | 8/40 [00:09<00:34,  1.07s/batch]
Judging:  22%|██▎       | 9/40 [00:10<00:33,  1.07s/batch]
Judging:  25%|██▌       | 10/40 [00:11<00:32,  1.07s/batch]
Judging:  28%|██▊       | 11/40 [00:12<00:31,  1.09s/batch]
Judging:  30%|███       | 12/40 [00:13<00:30,  1.08s/batch]
Judging:  32%|███▎      | 13/40 [00:14<00:29,  1.08s/batch]
Judging:  35%|███▌      | 14/40 [00:15<00:27,  1.07s/batch]
Judging:  38%|███▊      | 15/40 [00:16<00:26,  1.06s/batch]
Judging:  40%|████      | 16/40 [00:17<00:25,  1.06s/batch]
Judging:  42%|████▎     | 17/40 [00:18<00:24,  1.06s/batch]
Judging:  45%|████▌     | 18/40 [00:19<00:23,  1.05s/batch]
Judging:  48%|████▊     | 19/40 [00:21<00:22,  1.05s/batch]
Judging:  50%|█████     | 20/40 [00:22<00:21,  1.06s/batch]
Judging:  52%|█████▎    | 21/40 [00:23<00:20,  1.06s/batch]
Judging:  55%|█████▌    | 22/40 [00:24<00:20,  1.15s/batch]
Judging:  57%|█████▊    | 23/40 [00:25<00:19,  1.12s/batch]
Judging:  60%|██████    | 24/40 [00:26<00:17,  1.10s/batch]
Judging:  62%|██████▎   | 25/40 [00:27<00:16,  1.09s/batch]
Judging:  65%|██████▌   | 26/40 [00:28<00:15,  1.08s/batch]
Judging:  68%|██████▊   | 27/40 [00:29<00:14,  1.08s/batch]
Judging:  70%|███████   | 28/40 [00:30<00:12,  1.07s/batch]
Judging:  72%|███████▎  | 29/40 [00:32<00:12,  1.16s/batch]
Judging:  75%|███████▌  | 30/40 [00:33<00:11,  1.13s/batch]
Judging:  78%|███████▊  | 31/40 [00:34<00:10,  1.14s/batch]
Judging:  80%|████████  | 32/40 [00:35<00:08,  1.11s/batch]
Judging:  82%|████████▎ | 33/40 [00:36<00:07,  1.10s/batch]
Judging:  85%|████████▌ | 34/40 [00:37<00:06,  1.08s/batch]
Judging:  88%|████████▊ | 35/40 [00:38<00:05,  1.16s/batch]
Judging:  90%|█████████ | 36/40 [00:40<00:04,  1.13s/batch]
Judging:  92%|█████████▎| 37/40 [00:41<00:03,  1.13s/batch]
Judging:  95%|█████████▌| 38/40 [00:42<00:02,  1.11s/batch]
Judging:  98%|█████████▊| 39/40 [00:43<00:01,  1.09s/batch]
Judging: 100%|██████████| 40/40 [00:43<00:00,  1.10s/batch]
Judging queries:  76%|███████▌  | 16/21 [19:14<05:39, 67.91s/it]
Judging:   0%|          | 0/69 [00:00<?, ?batch/s]
Judging:   1%|▏         | 1/69 [00:01<02:01,  1.79s/batch]
Judging:   3%|▎         | 2/69 [00:03<01:59,  1.78s/batch]
Judging:   4%|▍         | 3/69 [00:05<01:58,  1.80s/batch]
Judging:   6%|▌         | 4/69 [00:07<01:57,  1.80s/batch]
Judging:   7%|▋         | 5/69 [00:08<01:53,  1.77s/batch]
Judging:   9%|▊         | 6/69 [00:10<01:52,  1.79s/batch]
Judging:  10%|█         | 7/69 [00:12<01:49,  1.77s/batch]
Judging:  12%|█▏        | 8/69 [00:14<01:48,  1.78s/batch]
Judging:  13%|█▎        | 9/69 [00:15<01:45,  1.76s/batch]
Judging:  14%|█▍        | 10/69 [00:17<01:42,  1.74s/batch]
Judging:  16%|█▌        | 11/69 [00:19<01:44,  1.80s/batch]
Judging:  17%|█▋        | 12/69 [00:21<01:43,  1.81s/batch]
Judging:  19%|█▉        | 13/69 [00:23<01:40,  1.79s/batch]
Judging:  20%|██        | 14/69 [00:25<01:39,  1.81s/batch]
Judging:  22%|██▏       | 15/69 [00:26<01:38,  1.82s/batch]
Judging:  23%|██▎       | 16/69 [00:28<01:36,  1.82s/batch]
Judging:  25%|██▍       | 17/69 [00:30<01:32,  1.78s/batch]
Judging:  26%|██▌       | 18/69 [00:32<01:32,  1.82s/batch]
Judging:  28%|██▊       | 19/69 [00:34<01:29,  1.78s/batch]
Judging:  29%|██▉       | 20/69 [00:35<01:28,  1.80s/batch]
Judging:  30%|███       | 21/69 [00:37<01:26,  1.80s/batch]
Judging:  32%|███▏      | 22/69 [00:39<01:24,  1.80s/batch]
Judging:  33%|███▎      | 23/69 [00:41<01:24,  1.83s/batch]
Judging:  35%|███▍      | 24/69 [00:43<01:21,  1.82s/batch]
Judging:  36%|███▌      | 25/69 [00:44<01:19,  1.80s/batch]
Judging:  38%|███▊      | 26/69 [00:45<01:07,  1.58s/batch]
Judging:  39%|███▉      | 27/69 [00:46<00:59,  1.42s/batch]
Judging:  41%|████      | 28/69 [00:48<00:53,  1.31s/batch]
Judging:  42%|████▏     | 29/69 [00:49<00:49,  1.24s/batch]
Judging:  43%|████▎     | 30/69 [00:50<00:46,  1.18s/batch]
Judging:  45%|████▍     | 31/69 [00:51<00:46,  1.24s/batch]
Judging:  46%|████▋     | 32/69 [00:52<00:43,  1.19s/batch]
Judging:  48%|████▊     | 33/69 [00:53<00:41,  1.15s/batch]
Judging:  49%|████▉     | 34/69 [00:54<00:39,  1.13s/batch]
Judging:  51%|█████     | 35/69 [00:56<00:40,  1.20s/batch]
Judging:  52%|█████▏    | 36/69 [00:57<00:38,  1.17s/batch]
Judging:  54%|█████▎    | 37/69 [00:58<00:36,  1.14s/batch]
Judging:  55%|█████▌    | 38/69 [00:59<00:35,  1.16s/batch]
Judging:  57%|█████▋    | 39/69 [01:00<00:36,  1.21s/batch]
Judging:  58%|█████▊    | 40/69 [01:02<00:37,  1.29s/batch]
Judging:  59%|█████▉    | 41/69 [01:03<00:34,  1.23s/batch]
Judging:  61%|██████    | 42/69 [01:04<00:31,  1.18s/batch]
Judging:  62%|██████▏   | 43/69 [01:05<00:32,  1.23s/batch]
Judging:  64%|██████▍   | 44/69 [01:06<00:29,  1.19s/batch]
Judging:  65%|██████▌   | 45/69 [01:08<00:29,  1.25s/batch]
Judging:  67%|██████▋   | 46/69 [01:09<00:29,  1.28s/batch]
Judging:  68%|██████▊   | 47/69 [01:11<00:29,  1.32s/batch]
Judging:  70%|██████▉   | 48/69 [01:12<00:27,  1.33s/batch]
Judging:  71%|███████   | 49/69 [01:13<00:27,  1.35s/batch]
Judging:  72%|███████▏  | 50/69 [01:14<00:24,  1.30s/batch]
Judging:  74%|███████▍  | 51/69 [01:16<00:23,  1.31s/batch]
Judging:  75%|███████▌  | 52/69 [01:17<00:22,  1.31s/batch]
Judging:  77%|███████▋  | 53/69 [01:18<00:21,  1.31s/batch]
Judging:  78%|███████▊  | 54/69 [01:20<00:18,  1.24s/batch]
Judging:  80%|███████▉  | 55/69 [01:21<00:17,  1.27s/batch]
Judging:  81%|████████  | 56/69 [01:22<00:15,  1.21s/batch]
Judging:  83%|████████▎ | 57/69 [01:23<00:13,  1.16s/batch]
Judging:  84%|████████▍ | 58/69 [01:24<00:13,  1.22s/batch]
Judging:  86%|████████▌ | 59/69 [01:25<00:11,  1.17s/batch]
Judging:  87%|████████▋ | 60/69 [01:26<00:10,  1.14s/batch]
Judging:  88%|████████▊ | 61/69 [01:28<00:09,  1.21s/batch]
Judging:  90%|████████▉ | 62/69 [01:29<00:08,  1.26s/batch]
Judging:  91%|█████████▏| 63/69 [01:31<00:07,  1.28s/batch]
Judging:  93%|█████████▎| 64/69 [01:32<00:06,  1.25s/batch]
Judging:  94%|█████████▍| 65/69 [01:33<00:04,  1.20s/batch]
Judging:  96%|█████████▌| 66/69 [01:34<00:03,  1.26s/batch]
Judging:  97%|█████████▋| 67/69 [01:36<00:02,  1.29s/batch]
Judging:  99%|█████████▊| 68/69 [01:37<00:01,  1.34s/batch]
Judging: 100%|██████████| 69/69 [01:38<00:00,  1.43s/batch]
Judging queries:  81%|████████  | 17/21 [20:52<05:08, 77.07s/it]
Judging:   0%|          | 0/61 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/61 [00:01<01:36,  1.60s/batch]
Judging:   3%|▎         | 2/61 [00:03<01:41,  1.72s/batch]
Judging:   5%|▍         | 3/61 [00:04<01:36,  1.66s/batch]
Judging:   7%|▋         | 4/61 [00:06<01:35,  1.67s/batch]
Judging:   8%|▊         | 5/61 [00:08<01:35,  1.70s/batch]
Judging:  10%|▉         | 6/61 [00:10<01:31,  1.66s/batch]
Judging:  11%|█▏        | 7/61 [00:11<01:35,  1.76s/batch]
Judging:  13%|█▎        | 8/61 [00:13<01:30,  1.70s/batch]
Judging:  15%|█▍        | 9/61 [00:15<01:28,  1.70s/batch]
Judging:  16%|█▋        | 10/61 [00:16<01:26,  1.70s/batch]
Judging:  18%|█▊        | 11/61 [00:18<01:24,  1.68s/batch]
Judging:  20%|█▉        | 12/61 [00:20<01:22,  1.69s/batch]
Judging:  21%|██▏       | 13/61 [00:22<01:23,  1.75s/batch]
Judging:  23%|██▎       | 14/61 [00:23<01:21,  1.73s/batch]
Judging:  25%|██▍       | 15/61 [00:25<01:19,  1.73s/batch]
Judging:  26%|██▌       | 16/61 [00:27<01:19,  1.77s/batch]
Judging:  28%|██▊       | 17/61 [00:29<01:16,  1.75s/batch]
Judging:  30%|██▉       | 18/61 [00:31<01:18,  1.83s/batch]
Judging:  31%|███       | 19/61 [00:32<01:15,  1.80s/batch]
Judging:  33%|███▎      | 20/61 [00:34<01:11,  1.74s/batch]
Judging:  34%|███▍      | 21/61 [00:35<01:01,  1.54s/batch]
Judging:  36%|███▌      | 22/61 [00:36<00:54,  1.39s/batch]
Judging:  38%|███▊      | 23/61 [00:37<00:49,  1.29s/batch]
Judging:  39%|███▉      | 24/61 [00:38<00:45,  1.22s/batch]
Judging:  41%|████      | 25/61 [00:40<00:44,  1.25s/batch]
Judging:  43%|████▎     | 26/61 [00:41<00:41,  1.19s/batch]
Judging:  44%|████▍     | 27/61 [00:42<00:39,  1.15s/batch]
Judging:  46%|████▌     | 28/61 [00:43<00:36,  1.12s/batch]
Judging:  48%|████▊     | 29/61 [00:44<00:35,  1.10s/batch]
Judging:  49%|████▉     | 30/61 [00:45<00:33,  1.09s/batch]
Judging:  51%|█████     | 31/61 [00:46<00:32,  1.07s/batch]
Judging:  52%|█████▏    | 32/61 [00:47<00:30,  1.06s/batch]
Judging:  54%|█████▍    | 33/61 [00:48<00:32,  1.17s/batch]
Judging:  56%|█████▌    | 34/61 [00:50<00:33,  1.25s/batch]
Judging:  57%|█████▋    | 35/61 [00:51<00:31,  1.19s/batch]
Judging:  59%|█████▉    | 36/61 [00:52<00:28,  1.15s/batch]
Judging:  61%|██████    | 37/61 [00:53<00:29,  1.21s/batch]
Judging:  62%|██████▏   | 38/61 [00:54<00:26,  1.17s/batch]
Judging:  64%|██████▍   | 39/61 [00:55<00:25,  1.14s/batch]
Judging:  66%|██████▌   | 40/61 [00:57<00:24,  1.14s/batch]
Judging:  67%|██████▋   | 41/61 [00:58<00:24,  1.21s/batch]
Judging:  69%|██████▉   | 42/61 [00:59<00:22,  1.17s/batch]
Judging:  70%|███████   | 43/61 [01:00<00:20,  1.14s/batch]
Judging:  72%|███████▏  | 44/61 [01:01<00:18,  1.11s/batch]
Judging:  74%|███████▍  | 45/61 [01:02<00:17,  1.10s/batch]
Judging:  75%|███████▌  | 46/61 [01:03<00:16,  1.08s/batch]
Judging:  77%|███████▋  | 47/61 [01:04<00:14,  1.07s/batch]
Judging:  79%|███████▊  | 48/61 [01:05<00:14,  1.09s/batch]
Judging:  80%|████████  | 49/61 [01:06<00:12,  1.07s/batch]
Judging:  82%|████████▏ | 50/61 [01:07<00:11,  1.07s/batch]
Judging:  84%|████████▎ | 51/61 [01:09<00:11,  1.14s/batch]
Judging:  85%|████████▌ | 52/61 [01:10<00:10,  1.12s/batch]
Judging:  87%|████████▋ | 53/61 [01:11<00:09,  1.17s/batch]
Judging:  89%|████████▊ | 54/61 [01:12<00:07,  1.14s/batch]
Judging:  90%|█████████ | 55/61 [01:13<00:06,  1.14s/batch]
Judging:  92%|█████████▏| 56/61 [01:14<00:05,  1.11s/batch]
Judging:  93%|█████████▎| 57/61 [01:16<00:04,  1.12s/batch]
Judging:  95%|█████████▌| 58/61 [01:17<00:03,  1.11s/batch]
Judging:  97%|█████████▋| 59/61 [01:18<00:02,  1.09s/batch]
Judging:  98%|█████████▊| 60/61 [01:19<00:01,  1.09s/batch]
Judging: 100%|██████████| 61/61 [01:20<00:00,  1.32s/batch]
Judging queries:  86%|████████▌ | 18/21 [22:13<03:54, 78.05s/it]

  checkpoint @ query 18

Judging:   0%|          | 0/64 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/64 [00:01<01:36,  1.53s/batch]
Judging:   3%|▎         | 2/64 [00:03<01:45,  1.70s/batch]
Judging:   5%|▍         | 3/64 [00:04<01:40,  1.64s/batch]
Judging:   6%|▋         | 4/64 [00:06<01:42,  1.71s/batch]
Judging:   8%|▊         | 5/64 [00:08<01:42,  1.74s/batch]
Judging:   9%|▉         | 6/64 [00:10<01:39,  1.72s/batch]
Judging:  11%|█         | 7/64 [00:12<01:40,  1.76s/batch]
Judging:  12%|█▎        | 8/64 [00:13<01:37,  1.75s/batch]
Judging:  14%|█▍        | 9/64 [00:15<01:35,  1.74s/batch]
Judging:  16%|█▌        | 10/64 [00:17<01:36,  1.79s/batch]
Judging:  17%|█▋        | 11/64 [00:19<01:32,  1.74s/batch]
Judging:  19%|█▉        | 12/64 [00:20<01:26,  1.67s/batch]
Judging:  20%|██        | 13/64 [00:22<01:27,  1.71s/batch]
Judging:  22%|██▏       | 14/64 [00:23<01:20,  1.60s/batch]
Judging:  23%|██▎       | 15/64 [00:25<01:18,  1.61s/batch]
Judging:  25%|██▌       | 16/64 [00:26<01:17,  1.62s/batch]
Judging:  27%|██▋       | 17/64 [00:28<01:13,  1.57s/batch]
Judging:  28%|██▊       | 18/64 [00:30<01:13,  1.60s/batch]
Judging:  30%|██▉       | 19/64 [00:31<01:11,  1.58s/batch]
Judging:  31%|███▏      | 20/64 [00:33<01:10,  1.61s/batch]
Judging:  33%|███▎      | 21/64 [00:34<01:08,  1.59s/batch]
Judging:  34%|███▍      | 22/64 [00:36<01:07,  1.61s/batch]
Judging:  36%|███▌      | 23/64 [00:37<01:04,  1.57s/batch]
Judging:  38%|███▊      | 24/64 [00:39<01:02,  1.56s/batch]
Judging:  39%|███▉      | 25/64 [00:41<01:03,  1.63s/batch]
Judging:  41%|████      | 26/64 [00:42<00:58,  1.54s/batch]
Judging:  42%|████▏     | 27/64 [00:43<00:51,  1.40s/batch]
Judging:  44%|████▍     | 28/64 [00:45<00:49,  1.38s/batch]
Judging:  45%|████▌     | 29/64 [00:46<00:45,  1.29s/batch]
Judging:  47%|████▋     | 30/64 [00:47<00:44,  1.31s/batch]
Judging:  48%|████▊     | 31/64 [00:48<00:40,  1.23s/batch]
Judging:  50%|█████     | 32/64 [00:49<00:40,  1.26s/batch]
Judging:  52%|█████▏    | 33/64 [00:50<00:37,  1.20s/batch]
Judging:  53%|█████▎    | 34/64 [00:51<00:34,  1.17s/batch]
Judging:  55%|█████▍    | 35/64 [00:53<00:32,  1.13s/batch]
Judging:  56%|█████▋    | 36/64 [00:54<00:34,  1.22s/batch]
Judging:  58%|█████▊    | 37/64 [00:55<00:32,  1.20s/batch]
Judging:  59%|█████▉    | 38/64 [00:57<00:32,  1.27s/batch]
Judging:  61%|██████    | 39/64 [00:58<00:30,  1.21s/batch]
Judging:  62%|██████▎   | 40/64 [00:59<00:30,  1.26s/batch]
Judging:  64%|██████▍   | 41/64 [01:00<00:27,  1.20s/batch]
Judging:  66%|██████▌   | 42/64 [01:01<00:27,  1.24s/batch]
Judging:  67%|██████▋   | 43/64 [01:03<00:27,  1.29s/batch]
Judging:  69%|██████▉   | 44/64 [01:04<00:26,  1.33s/batch]
Judging:  70%|███████   | 45/64 [01:06<00:26,  1.37s/batch]
Judging:  72%|███████▏  | 46/64 [01:07<00:24,  1.38s/batch]
Judging:  73%|███████▎  | 47/64 [01:08<00:21,  1.28s/batch]
Judging:  75%|███████▌  | 48/64 [01:09<00:19,  1.21s/batch]
Judging:  77%|███████▋  | 49/64 [01:10<00:17,  1.16s/batch]
Judging:  78%|███████▊  | 50/64 [01:12<00:16,  1.20s/batch]
Judging:  80%|███████▉  | 51/64 [01:13<00:15,  1.16s/batch]
Judging:  81%|████████▏ | 52/64 [01:14<00:14,  1.21s/batch]
Judging:  83%|████████▎ | 53/64 [01:15<00:12,  1.17s/batch]
Judging:  84%|████████▍ | 54/64 [01:16<00:11,  1.14s/batch]
Judging:  86%|████████▌ | 55/64 [01:17<00:10,  1.11s/batch]
Judging:  88%|████████▊ | 56/64 [01:18<00:08,  1.10s/batch]
Judging:  89%|████████▉ | 57/64 [01:19<00:07,  1.09s/batch]
Judging:  91%|█████████ | 58/64 [01:20<00:06,  1.08s/batch]
Judging:  92%|█████████▏| 59/64 [01:21<00:05,  1.07s/batch]
Judging:  94%|█████████▍| 60/64 [01:22<00:04,  1.08s/batch]
Judging:  95%|█████████▌| 61/64 [01:24<00:03,  1.17s/batch]
Judging:  97%|█████████▋| 62/64 [01:25<00:02,  1.22s/batch]
Judging:  98%|█████████▊| 63/64 [01:26<00:01,  1.17s/batch]
Judging: 100%|██████████| 64/64 [01:27<00:00,  1.36s/batch]
Judging queries:  90%|█████████ | 19/21 [23:40<02:41, 80.78s/it]
Judging:   0%|          | 0/67 [00:00<?, ?batch/s]
Judging:   1%|▏         | 1/67 [00:01<01:57,  1.78s/batch]
Judging:   3%|▎         | 2/67 [00:03<01:56,  1.79s/batch]
Judging:   4%|▍         | 3/67 [00:05<01:54,  1.78s/batch]
Judging:   6%|▌         | 4/67 [00:07<01:50,  1.75s/batch]
Judging:   7%|▋         | 5/67 [00:08<01:47,  1.73s/batch]
Judging:   9%|▉         | 6/67 [00:10<01:44,  1.71s/batch]
Judging:  10%|█         | 7/67 [00:12<01:44,  1.74s/batch]
Judging:  12%|█▏        | 8/67 [00:13<01:41,  1.73s/batch]
Judging:  13%|█▎        | 9/67 [00:15<01:39,  1.72s/batch]
Judging:  15%|█▍        | 10/67 [00:17<01:35,  1.67s/batch]
Judging:  16%|█▋        | 11/67 [00:18<01:33,  1.68s/batch]
Judging:  18%|█▊        | 12/67 [00:20<01:28,  1.62s/batch]
Judging:  19%|█▉        | 13/67 [00:21<01:26,  1.59s/batch]
Judging:  21%|██        | 14/67 [00:23<01:27,  1.65s/batch]
Judging:  22%|██▏       | 15/67 [00:25<01:26,  1.65s/batch]
Judging:  24%|██▍       | 16/67 [00:27<01:25,  1.67s/batch]
Judging:  25%|██▌       | 17/67 [00:28<01:22,  1.64s/batch]
Judging:  27%|██▋       | 18/67 [00:30<01:21,  1.66s/batch]
Judging:  28%|██▊       | 19/67 [00:32<01:20,  1.67s/batch]
Judging:  30%|██▉       | 20/67 [00:33<01:20,  1.70s/batch]
Judging:  31%|███▏      | 21/67 [00:35<01:21,  1.77s/batch]
Judging:  33%|███▎      | 22/67 [00:37<01:18,  1.75s/batch]
Judging:  34%|███▍      | 23/67 [00:39<01:18,  1.78s/batch]
Judging:  36%|███▌      | 24/67 [00:41<01:16,  1.78s/batch]
Judging:  37%|███▋      | 25/67 [00:42<01:13,  1.75s/batch]
Judging:  39%|███▉      | 26/67 [00:44<01:06,  1.62s/batch]
Judging:  40%|████      | 27/67 [00:45<01:01,  1.53s/batch]
Judging:  42%|████▏     | 28/67 [00:46<00:54,  1.39s/batch]
Judging:  43%|████▎     | 29/67 [00:47<00:50,  1.32s/batch]
Judging:  45%|████▍     | 30/67 [00:48<00:45,  1.24s/batch]
Judging:  46%|████▋     | 31/67 [00:50<00:45,  1.27s/batch]
Judging:  48%|████▊     | 32/67 [00:51<00:42,  1.21s/batch]
Judging:  49%|████▉     | 33/67 [00:52<00:39,  1.17s/batch]
Judging:  51%|█████     | 34/67 [00:53<00:37,  1.13s/batch]
Judging:  52%|█████▏    | 35/67 [00:54<00:35,  1.11s/batch]
Judging:  54%|█████▎    | 36/67 [00:55<00:33,  1.09s/batch]
Judging:  55%|█████▌    | 37/67 [00:56<00:32,  1.09s/batch]
Judging:  57%|█████▋    | 38/67 [00:57<00:31,  1.08s/batch]
Judging:  58%|█████▊    | 39/67 [00:58<00:32,  1.17s/batch]
Judging:  60%|█████▉    | 40/67 [01:00<00:32,  1.22s/batch]
Judging:  61%|██████    | 41/67 [01:01<00:30,  1.17s/batch]
Judging:  63%|██████▎   | 42/67 [01:02<00:29,  1.17s/batch]
Judging:  64%|██████▍   | 43/67 [01:03<00:27,  1.14s/batch]
Judging:  66%|██████▌   | 44/67 [01:04<00:25,  1.12s/batch]
Judging:  67%|██████▋   | 45/67 [01:05<00:24,  1.10s/batch]
Judging:  69%|██████▊   | 46/67 [01:06<00:22,  1.09s/batch]
Judging:  70%|███████   | 47/67 [01:07<00:23,  1.16s/batch]
Judging:  72%|███████▏  | 48/67 [01:09<00:21,  1.13s/batch]
Judging:  73%|███████▎  | 49/67 [01:10<00:19,  1.11s/batch]
Judging:  75%|███████▍  | 50/67 [01:11<00:18,  1.09s/batch]
Judging:  76%|███████▌  | 51/67 [01:12<00:17,  1.08s/batch]
Judging:  78%|███████▊  | 52/67 [01:13<00:16,  1.07s/batch]
Judging:  79%|███████▉  | 53/67 [01:14<00:14,  1.07s/batch]
Judging:  81%|████████  | 54/67 [01:15<00:14,  1.09s/batch]
Judging:  82%|████████▏ | 55/67 [01:16<00:12,  1.08s/batch]
Judging:  84%|████████▎ | 56/67 [01:17<00:11,  1.07s/batch]
Judging:  85%|████████▌ | 57/67 [01:18<00:10,  1.07s/batch]
Judging:  87%|████████▋ | 58/67 [01:19<00:09,  1.07s/batch]
Judging:  88%|████████▊ | 59/67 [01:20<00:08,  1.06s/batch]
Judging:  90%|████████▉ | 60/67 [01:21<00:07,  1.06s/batch]
Judging:  91%|█████████ | 61/67 [01:22<00:06,  1.06s/batch]
Judging:  93%|█████████▎| 62/67 [01:24<00:05,  1.17s/batch]
Judging:  94%|█████████▍| 63/67 [01:25<00:04,  1.14s/batch]
Judging:  96%|█████████▌| 64/67 [01:26<00:03,  1.12s/batch]
Judging:  97%|█████████▋| 65/67 [01:27<00:02,  1.20s/batch]
Judging:  99%|█████████▊| 66/67 [01:29<00:01,  1.27s/batch]
Judging: 100%|██████████| 67/67 [01:29<00:00,  1.34s/batch]
Judging queries:  95%|█████████▌| 20/21 [25:09<01:23, 83.41s/it]
Judging:   0%|          | 0/65 [00:00<?, ?batch/s]
Judging:   2%|▏         | 1/65 [00:01<01:57,  1.83s/batch]
Judging:   3%|▎         | 2/65 [00:03<01:49,  1.74s/batch]
Judging:   5%|▍         | 3/65 [00:05<01:49,  1.77s/batch]
Judging:   6%|▌         | 4/65 [00:07<01:45,  1.74s/batch]
Judging:   8%|▊         | 5/65 [00:08<01:42,  1.72s/batch]
Judging:   9%|▉         | 6/65 [00:10<01:41,  1.72s/batch]
Judging:  11%|█         | 7/65 [00:11<01:34,  1.64s/batch]
Judging:  12%|█▏        | 8/65 [00:13<01:34,  1.65s/batch]
Judging:  14%|█▍        | 9/65 [00:15<01:38,  1.76s/batch]
Judging:  15%|█▌        | 10/65 [00:17<01:37,  1.77s/batch]
Judging:  17%|█▋        | 11/65 [00:19<01:37,  1.80s/batch]
Judging:  18%|█▊        | 12/65 [00:20<01:33,  1.77s/batch]
Judging:  20%|██        | 13/65 [00:22<01:34,  1.81s/batch]
Judging:  22%|██▏       | 14/65 [00:24<01:30,  1.78s/batch]
Judging:  23%|██▎       | 15/65 [00:26<01:27,  1.75s/batch]
Judging:  25%|██▍       | 16/65 [00:27<01:24,  1.73s/batch]
Judging:  26%|██▌       | 17/65 [00:29<01:22,  1.72s/batch]
Judging:  28%|██▊       | 18/65 [00:31<01:20,  1.71s/batch]
Judging:  29%|██▉       | 19/65 [00:33<01:20,  1.74s/batch]
Judging:  31%|███       | 20/65 [00:34<01:18,  1.75s/batch]
Judging:  32%|███▏      | 21/65 [00:36<01:15,  1.73s/batch]
Judging:  34%|███▍      | 22/65 [00:38<01:15,  1.75s/batch]
Judging:  35%|███▌      | 23/65 [00:40<01:12,  1.74s/batch]
Judging:  37%|███▋      | 24/65 [00:41<01:11,  1.74s/batch]
Judging:  38%|███▊      | 25/65 [00:43<01:11,  1.78s/batch]
Judging:  40%|████      | 26/65 [00:45<01:04,  1.65s/batch]
Judging:  42%|████▏     | 27/65 [00:46<00:59,  1.57s/batch]
Judging:  43%|████▎     | 28/65 [00:47<00:55,  1.50s/batch]
Judging:  45%|████▍     | 29/65 [00:48<00:49,  1.37s/batch]
Judging:  46%|████▌     | 30/65 [00:49<00:44,  1.28s/batch]
Judging:  48%|████▊     | 31/65 [00:50<00:41,  1.22s/batch]
Judging:  49%|████▉     | 32/65 [00:52<00:39,  1.18s/batch]
Judging:  51%|█████     | 33/65 [00:53<00:36,  1.15s/batch]
Judging:  52%|█████▏    | 34/65 [00:54<00:37,  1.21s/batch]
Judging:  54%|█████▍    | 35/65 [00:55<00:38,  1.28s/batch]
Judging:  55%|█████▌    | 36/65 [00:56<00:35,  1.22s/batch]
Judging:  57%|█████▋    | 37/65 [00:58<00:32,  1.17s/batch]
Judging:  58%|█████▊    | 38/65 [00:59<00:33,  1.25s/batch]
Judging:  60%|██████    | 39/65 [01:00<00:31,  1.22s/batch]
Judging:  62%|██████▏   | 40/65 [01:02<00:33,  1.34s/batch]
Judging:  63%|██████▎   | 41/65 [01:03<00:33,  1.38s/batch]
Judging:  65%|██████▍   | 42/65 [01:05<00:32,  1.43s/batch]
Judging:  66%|██████▌   | 43/65 [01:06<00:31,  1.42s/batch]
Judging:  68%|██████▊   | 44/65 [01:08<00:29,  1.41s/batch]
Judging:  69%|██████▉   | 45/65 [01:09<00:27,  1.39s/batch]
Judging:  71%|███████   | 46/65 [01:10<00:26,  1.39s/batch]
Judging:  72%|███████▏  | 47/65 [01:11<00:23,  1.29s/batch]
Judging:  74%|███████▍  | 48/65 [01:12<00:20,  1.22s/batch]
Judging:  75%|███████▌  | 49/65 [01:13<00:18,  1.17s/batch]
Judging:  77%|███████▋  | 50/65 [01:15<00:17,  1.14s/batch]
Judging:  78%|███████▊  | 51/65 [01:16<00:16,  1.20s/batch]
Judging:  80%|████████  | 52/65 [01:17<00:15,  1.16s/batch]
Judging:  82%|████████▏ | 53/65 [01:18<00:14,  1.22s/batch]
Judging:  83%|████████▎ | 54/65 [01:19<00:12,  1.17s/batch]
Judging:  85%|████████▍ | 55/65 [01:20<00:11,  1.14s/batch]
Judging:  86%|████████▌ | 56/65 [01:21<00:10,  1.12s/batch]
Judging:  88%|████████▊ | 57/65 [01:23<00:08,  1.10s/batch]
Judging:  89%|████████▉ | 58/65 [01:24<00:07,  1.09s/batch]
Judging:  91%|█████████ | 59/65 [01:25<00:06,  1.08s/batch]
Judging:  92%|█████████▏| 60/65 [01:26<00:05,  1.08s/batch]
Judging:  94%|█████████▍| 61/65 [01:27<00:04,  1.07s/batch]
Judging:  95%|█████████▌| 62/65 [01:28<00:03,  1.17s/batch]
Judging:  97%|█████████▋| 63/65 [01:30<00:02,  1.24s/batch]
Judging:  98%|█████████▊| 64/65 [01:31<00:01,  1.19s/batch]
Judging: 100%|██████████| 65/65 [01:32<00:00,  1.42s/batch]
Judging queries: 100%|██████████| 21/21 [26:42<00:00, 76.29s/it]

  checkpoint @ query 21
Judged 4871 pairs
relevance
0    4805
2      49
3      17
Name: count, dtype: int64
GPU 0 → 1.01 GB
GPU 1 → 0.01 GB

In [106]:
# Build TREC-format qrels
pool_judged_df = pd.read_csv('/kaggle/working/pool_judged.csv')
pool_judged_df['qid']   = pool_judged_df['qid'].astype(str)
pool_judged_df['docno'] = pool_judged_df['docno'].astype(str)

# TREC format (no header)
trec_qrels = pool_judged_df.copy()
trec_qrels.insert(1, 'Q0', '0')
trec_qrels[['qid','Q0','docno','relevance']].to_csv(
    '/kaggle/working/custom_qrels.tsv', sep='\t', index=False, header=False
)
# PyTerrier format (with header)
pool_judged_df[['qid','docno','relevance']].to_csv(
    '/kaggle/working/custom_qrels_pt.tsv', sep='\t', index=False
)
print(f'QRELs saved: {len(pool_judged_df)} judgements')
print(f'Relevant (rel>=2): {(pool_judged_df["relevance"]>=2).sum()}')

QRELs saved: 4871 judgements
Relevant (rel>=2): 66

# Phase 3 — Full Retrieval Benchmark
**Models**: BM25, Jina-Code, CodeBERT, MRL-LangChain, MRL-Dense, TctColBERT  
**Metrics**: nDCG@10, nDCG@5, MAP(rel=2), Recall@10

In [108]:
# Reload data (safe for fresh kernel)
import pyterrier as pt
if not pt.started(): pt.init()
import pyterrier_dr

corpus    = pd.read_csv('/kaggle/working/corpus.tsv', sep='\t')
topics_df = pd.read_csv('/kaggle/working/topics.tsv', sep='\t')
qrels     = pd.read_csv('/kaggle/working/custom_qrels_pt.tsv', sep='\t')

corpus['docno']    = corpus['docno'].astype(str)
topics_df['qid']   = topics_df['qid'].astype(str)
qrels['qid']       = qrels['qid'].astype(str)
qrels['docno']     = qrels['docno'].astype(str)

print(f'Corpus: {len(corpus)}, Topics: {len(topics_df)}, Qrels: {len(qrels)}')
print(qrels['relevance'].value_counts().sort_index())

Corpus: 1000, Topics: 21, Qrels: 4871
relevance
0    4805
2      49
3      17
Name: count, dtype: int64

/tmp/ipykernel_54/1072864294.py:3: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started(): pt.init()

In [111]:
# Rebuild all retrieval pipelines
from pyterrier.measures import nDCG, MAP, Recall

# BM25 — load from existing index (no re-indexing needed)
index_ref = pt.IndexRef.of('/kaggle/working/custom_bm25_index/data.properties')
bm25 = pt.BatchRetrieve(index_ref, wmodel='BM25', num_results=100)

# GraphCodeBERT — index ALREADY BUILT, just load retriever
graphcb       = pyterrier_dr.SBertBiEncoder('microsoft/graphcodebert-base', batch_size=64)
graphcb_index = pyterrier_dr.FlexIndex('/kaggle/working/custom_graphcb.flex')
# NO re-indexing — index is already on disk ✅
graphcb_retr  = graphcb >> graphcb_index.np_retriever()

# CodeBERT (base) — check if index exists first
codebert        = pyterrier_dr.SBertBiEncoder('microsoft/codebert-base')
codebert_index  = pyterrier_dr.FlexIndex('/kaggle/working/custom_codebert.flex')
if not codebert_index.built():
    (codebert >> codebert_index).index(corpus.to_dict('records'))
codebert_retr   = codebert >> codebert_index.np_retriever()

# MRL fine-tuned LangChain
mrl             = pyterrier_dr.SBertBiEncoder('shubharuidas/codebert-base-code-embed-mrl-langchain-langgraph')
mrl_index       = pyterrier_dr.FlexIndex('/kaggle/working/custom_mrl.flex')
if not mrl_index.built():
    (mrl >> mrl_index).index(corpus.to_dict('records'))
mrl_retr        = mrl >> mrl_index.np_retriever()

# MRL Dense Retriever
mrl2            = pyterrier_dr.SBertBiEncoder('shubharuidas/codebert-embed-base-dense-retriever')
mrl2_index      = pyterrier_dr.FlexIndex('/kaggle/working/custom_mrl2.flex')
if not mrl2_index.built():
    (mrl2 >> mrl2_index).index(corpus.to_dict('records'))
mrl2_retr       = mrl2 >> mrl2_index.np_retriever()

# TctColBERT
tct             = pyterrier_dr.TctColBert()
tct_index       = pyterrier_dr.FlexIndex('/kaggle/working/custom_tct.flex')
if not tct_index.built():
    (tct >> tct_index).index(corpus.to_dict('records'))
tct_retr        = tct >> tct_index.np_retriever()

print('All pipelines ready.')

/tmp/ipykernel_54/2089326234.py:6: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  bm25 = pt.BatchRetrieve(index_ref, wmodel='BM25', num_results=100)
WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name microsoft/graphcodebert-base. Creating a new one with mean pooling.
Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name microsoft/codebert-base. Creating a new one with mean pooling.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/648 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

indexing: 1000dvec [00:19, 50.92dvec/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/648 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

indexing: 1000dvec [00:20, 47.84dvec/s]

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/441M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

indexing: 0dvec [00:00, ?dvec/s]
indexing: 1dvec [00:03,  3.64s/dvec]
indexing: 101dvec [00:07, 16.54dvec/s]
indexing: 201dvec [00:10, 21.41dvec/s]
indexing: 301dvec [00:14, 23.62dvec/s]
indexing: 401dvec [00:18, 24.50dvec/s]
indexing: 501dvec [00:22, 24.96dvec/s]
indexing: 601dvec [00:26, 25.09dvec/s]
indexing: 701dvec [00:30, 25.26dvec/s]
indexing: 801dvec [00:34, 25.40dvec/s]
indexing: 1000dvec [00:37, 26.50dvec/s][A

All pipelines ready.

In [113]:
# ── Combined pt.Experiment with stat-sig vs BM25 baseline ──
METRICS = [nDCG@10, nDCG@5, MAP(rel=2), Recall@10]

results = pt.Experiment(
    [bm25, graphcb_retr, codebert_retr, mrl_retr, mrl2_retr, tct_retr],
    topics_df,
    qrels,
    eval_metrics=METRICS,
    names=['BM25', 'GraphcodeBert', 'CodeBERT-base', 'MRL-LangChain', 'MRL-Dense', 'TctColBERT'],
    baseline=0,           # BM25 as baseline → adds p-value + delta columns
    filter_by_qrels=True, # TREC standard: unjudged docs treated as non-relevant
    verbose=True,
)

results.to_csv('/kaggle/working/benchmark_results.csv', index=False)
print('\n=== BENCHMARK RESULTS ===')
display(results)

pt.Experiment:   0%|          | 0/6 [00:00<?, ?system/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 295.31docbatch/s]
pt.Experiment:  33%|███▎      | 2/6 [00:00<00:00,  6.55system/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 815.06docbatch/s]
pt.Experiment:  50%|█████     | 3/6 [00:00<00:00,  5.43system/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 761.77docbatch/s]
pt.Experiment:  67%|██████▋   | 4/6 [00:00<00:00,  4.99system/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 806.29docbatch/s]
pt.Experiment:  83%|████████▎ | 5/6 [00:00<00:00,  4.77system/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 226.88docbatch/s]
pt.Experiment: 100%|██████████| 6/6 [00:01<00:00,  4.97system/s]

=== BENCHMARK RESULTS ===

,name,R@10,nDCG@5,nDCG@10,AP(rel=2),R@10 +,R@10 -,R@10 p-value,nDCG@5 +,nDCG@5 -,nDCG@5 p-value,nDCG@10 +,nDCG@10 -,nDCG@10 p-value,AP(rel=2) +,AP(rel=2) -,AP(rel=2) p-value
0,BM25,0.489466,0.346191,0.394799,0.325243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GraphcodeBert,0.096681,0.063770,0.064827,0.049686,1.0,14.0,0.002063,1.0,11.0,0.004454,1.0,14.0,0.000982,3.0,16.0,0.002944
2,CodeBERT-base,0.000000,0.000000,0.000000,0.005600,0.0,15.0,0.000025,0.0,12.0,0.000541,0.0,15.0,0.000091,3.0,16.0,0.000629
3,MRL-LangChain,0.526840,0.589829,0.584159,0.531909,4.0,8.0,0.745235,9.0,3.0,0.019652,9.0,7.0,0.087661,8.0,9.0,0.061966
4,MRL-Dense,0.526840,0.572254,0.566584,0.510433,4.0,8.0,0.745235,9.0,3.0,0.027869,9.0,7.0,0.115238,8.0,9.0,0.082957
5,TctColBERT,0.512554,0.472076,0.483066,0.428590,4.0,6.0,0.836681,7.0,5.0,0.196313,6.0,10.0,0.390620,6.0,12.0,0.300939

In [115]:
# Leaderboard Table
results_df = pd.read_csv('/kaggle/working/benchmark_results.csv')
num_cols = results_df.select_dtypes(include='number').columns
results_df[num_cols] = results_df[num_cols].round(4)
results_df = results_df.sort_values('nDCG@10', ascending=False).reset_index(drop=True)
results_df.insert(0, 'Rank', range(1, len(results_df)+1))

print('=== CODE RETRIEVAL BENCHMARK — Custom GenAI Corpus ===')
print(f'Queries: {len(topics_df)} | Corpus: {len(corpus)} docs')
print(f'QRELs: {len(qrels)}')
display(results_df[['Rank','name','nDCG@10','nDCG@5','AP(rel=2)','R@10']])

=== CODE RETRIEVAL BENCHMARK — Custom GenAI Corpus ===
Queries: 21 | Corpus: 1000 docs
QRELs: 4871

   Rank           name  nDCG@10  nDCG@5  AP(rel=2)    R@10
0     1  MRL-LangChain   0.5842  0.5898     0.5319  0.5268
1     2      MRL-Dense   0.5666  0.5723     0.5104  0.5268
2     3     TctColBERT   0.4831  0.4721     0.4286  0.5126
3     4           BM25   0.3948  0.3462     0.3252  0.4895
4     5  GraphcodeBert   0.0648  0.0638     0.0497  0.0967
5     6  CodeBERT-base   0.0000  0.0000     0.0056  0.0000

In [117]:
# ── RQ Answer Summary ──
print('=' * 60)
r = results_df.set_index('name')

print('RQ1 — MRL vs Base CodeBERT')
base  = r.loc['CodeBERT-base','nDCG@10']
mrl_s = r.loc['MRL-LangChain','nDCG@10']
print(f'  CodeBERT-base  nDCG@10: {base:.4f}')
print(f'  MRL-LangChain  nDCG@10: {mrl_s:.4f}')
print(f'  Relative gain: {(mrl_s-base)/(base+1e-9)*100:+.1f}%')

print('\nRQ2 — Late Interaction (TctColBERT) vs best Bi-Encoder')
tct_s   = r.loc['TctColBERT','nDCG@10']
bi_best = results_df[results_df['name']!='TctColBERT']['nDCG@10'].max()
bi_name = results_df.loc[results_df['nDCG@10']==bi_best,'name'].values[0]
print(f'  TctColBERT    nDCG@10: {tct_s:.4f}')
print(f'  Best bi-enc ({bi_name}): {bi_best:.4f}')
print(f'  Gap: {tct_s-bi_best:+.4f}')

============================================================
RQ1 — MRL vs Base CodeBERT
  CodeBERT-base  nDCG@10: 0.0000
  MRL-LangChain  nDCG@10: 0.5842
  Relative gain: +58420000000.0%

RQ2 — Late Interaction (TctColBERT) vs best Bi-Encoder
  TctColBERT    nDCG@10: 0.4831
  Best bi-enc (MRL-LangChain): 0.5842
  Gap: -0.1011

# RQ1 — MRL Embedding Dimension Sweep
Compares MRL-finetuned CodeBERT at dims 64/128/256/512/768 vs full-dim baseline.
Answers: *'Does MRL allow dimension reduction with minimal performance loss?'*

In [119]:
# ── RQ1 Setup: MRL Dimension Sweep ──
import pyterrier as pt

import pyterrier_dr
from pyterrier.measures import nDCG, MAP, Recall
import pandas as pd, numpy as np, gc, torch
from sentence_transformers import SentenceTransformer

# Load corpus and qrels (must have run Phase 1 & 2 first)
corpus    = pd.read_csv('/kaggle/working/corpus.tsv', sep='\t').astype(str)
topics_df = pd.read_csv('/kaggle/working/topics.tsv',           sep='\t').astype(str)
qrels_df  = pd.read_csv('/kaggle/working/custom_qrels_pt.tsv',  sep='\t').astype(str)
qrels_df['relevance'] = qrels_df['relevance'].astype(int)

MRL_MODEL = 'shubharuidas/codebert-base-code-embed-mrl-langchain-langgraph'
DIMS      = [64, 128, 256, 512, 768]   # 768 = full dim (baseline)
METRICS   = [nDCG @ 10, nDCG @ 5, MAP(rel=2), Recall @ 10]

print(f'Corpus: {len(corpus)} docs | Topics: {len(topics_df)} | Qrels: {len(qrels_df)}')

Corpus: 1000 docs | Topics: 21 | Qrels: 4871

In [124]:
from sentence_transformers import SentenceTransformer
import pyterrier as pt
import numpy as np

# ── Custom MRL Encoder (no internal attribute dependencies) ──
class MRLEncoder(pt.Transformer):
    """Wraps SentenceTransformer with truncate_dim for MRL inference."""
    def __init__(self, model_name, dim, batch_size=64):
        self.dim        = dim
        self.batch_size = batch_size
        self.model      = SentenceTransformer(model_name, truncate_dim=dim)
    
    def transform(self, inp):
        if 'query' in inp.columns:
            vecs = self.model.encode(
                inp['query'].tolist(), 
                batch_size=self.batch_size,
                normalize_embeddings=True,
                show_progress_bar=False
            )
            return inp.assign(query_vec=list(vecs))
        elif 'text' in inp.columns:
            vecs = self.model.encode(
                inp['text'].tolist(),
                batch_size=self.batch_size,
                normalize_embeddings=True,
                show_progress_bar=True
            )
            return inp.assign(doc_vec=list(vecs))
        return inp

print('MRLEncoder class ready.')

MRLEncoder class ready.

In [125]:
# ── Build MRL pipeline for each dimension ──
def build_mrl_pipeline(dim, model_name=MRL_MODEL):
    index_path = f'/kaggle/working/mrl_dim{dim}.flex'
    index      = pyterrier_dr.FlexIndex(index_path)
    encoder    = MRLEncoder(model_name, dim=dim, batch_size=64)
    
    if not index.built():
        print(f'  Indexing at dim={dim}...')
        (encoder >> index).index(corpus.to_dict('records'))
        print(f'  Done.')
    else:
        print(f'  Index at dim={dim} already exists, skipping.')
    
    # free GPU memory from encoder after indexing (keep index on disk)
    torch.cuda.empty_cache()
    
    return encoder >> index.np_retriever(num_results=100)

print('Building MRL indices for all dimensions...')
mrl_pipelines = {}

for dim in DIMS:
    print(f'\n[dim={dim}]')
    mrl_pipelines[dim] = build_mrl_pipeline(dim)
    gc.collect()
    torch.cuda.empty_cache()

print('\nAll indices built.')

Building MRL indices for all dimensions...

[dim=64]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

  Indexing at dim=64...

indexing: 0dvec [00:00, ?dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1dvec [00:02,  2.24s/dvec]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 101dvec [00:04, 27.03dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 201dvec [00:06, 34.59dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 301dvec [00:09, 37.65dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 401dvec [00:11, 40.06dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 501dvec [00:13, 41.15dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 601dvec [00:16, 41.46dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 701dvec [00:18, 40.98dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 801dvec [00:20, 41.27dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1000dvec [00:23, 43.03dvec/s]

  Done.

[dim=128]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

  Indexing at dim=128...

indexing: 0dvec [00:00, ?dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1dvec [00:02,  2.45s/dvec]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 101dvec [00:04, 24.82dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 201dvec [00:07, 31.69dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 301dvec [00:09, 34.32dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 401dvec [00:12, 36.30dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 501dvec [00:15, 37.13dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 601dvec [00:17, 37.26dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 701dvec [00:20, 36.79dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 801dvec [00:23, 36.99dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1000dvec [00:25, 38.80dvec/s]

  Done.

[dim=256]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

  Indexing at dim=256...

indexing: 0dvec [00:00, ?dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1dvec [00:02,  2.69s/dvec]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 101dvec [00:05, 22.36dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 201dvec [00:08, 28.80dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 301dvec [00:10, 31.63dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 401dvec [00:13, 33.89dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 501dvec [00:16, 35.18dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 601dvec [00:18, 35.98dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 701dvec [00:21, 36.16dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 801dvec [00:24, 37.01dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1000dvec [00:26, 37.63dvec/s]

  Done.

[dim=512]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

  Indexing at dim=512...

indexing: 0dvec [00:00, ?dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1dvec [00:02,  2.51s/dvec]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 101dvec [00:04, 24.21dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 201dvec [00:07, 31.26dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 301dvec [00:10, 34.32dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 401dvec [00:12, 36.58dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 501dvec [00:14, 37.72dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 601dvec [00:17, 38.34dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 701dvec [00:20, 38.20dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 801dvec [00:22, 38.78dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1000dvec [00:25, 39.92dvec/s]

  Done.

[dim=768]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

  Indexing at dim=768...

indexing: 0dvec [00:00, ?dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1dvec [00:02,  2.44s/dvec]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 101dvec [00:04, 24.54dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 201dvec [00:07, 31.45dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 301dvec [00:09, 34.30dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 401dvec [00:12, 36.32dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 501dvec [00:15, 37.32dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 601dvec [00:17, 37.78dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 701dvec [00:20, 37.51dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 801dvec [00:22, 38.01dvec/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

indexing: 1000dvec [00:25, 39.43dvec/s]

  Done.

All indices built.

In [130]:
# ── Run RQ1 Experiment: all dims in single pt.Experiment ──
print('Running RQ1 dimension sweep experiment...')

experiment_pipelines = [mrl_pipelines[d] for d in DIMS]
pipeline_names       = [f'MRL-{d}d' for d in DIMS]

rq1_results = pt.Experiment(
    experiment_pipelines,
    topics_df,
    qrels_df,
    eval_metrics=METRICS,
    names=pipeline_names,
    baseline=0,          # MRL-64d as baseline for significance vs full-dim
    correction='bonferroni',
)

rq1_results.to_csv('/kaggle/working/rq1_mrl_dims.csv', index=False)
print(rq1_results.to_string(index=False))
rq1_results

Running RQ1 dimension sweep experiment...

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 982.50docbatch/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 823.70docbatch/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 405.09docbatch/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 585.22docbatch/s]
NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 640.94docbatch/s]

    name    R@10   nDCG@5  nDCG@10  AP(rel=2)  R@10 +  R@10 -  R@10 p-value  R@10 reject  R@10 p-value corrected  nDCG@5 +  nDCG@5 -  nDCG@5 p-value  nDCG@5 reject  nDCG@5 p-value corrected  nDCG@10 +  nDCG@10 -  nDCG@10 p-value  nDCG@10 reject  nDCG@10 p-value corrected  AP(rel=2) +  AP(rel=2) -  AP(rel=2) p-value  AP(rel=2) reject  AP(rel=2) p-value corrected
 MRL-64d 0.52684 0.589829 0.584159   0.527920     NaN     NaN           NaN        False                     NaN       NaN       NaN             NaN          False                       NaN        NaN        NaN              NaN           False                        NaN          NaN          NaN                NaN             False                          NaN
MRL-128d 0.52684 0.589829 0.584159   0.532478     0.0     0.0           NaN        False                     NaN       0.0       0.0             NaN          False                       NaN        0.0        0.0              NaN           False                        NaN          2.0          2.0           0.308441             False                          1.0
MRL-256d 0.52684 0.589829 0.584159   0.529362     0.0     0.0           NaN        False                     NaN       0.0       0.0             NaN          False                       NaN        0.0        0.0              NaN           False                        NaN          2.0          2.0           0.406815             False                          1.0
MRL-512d 0.52684 0.589829 0.584159   0.529436     0.0     0.0           NaN        False                     NaN       0.0       0.0             NaN          False                       NaN        0.0        0.0              NaN           False                        NaN          2.0          2.0           0.295388             False                          1.0
MRL-768d 0.52684 0.589829 0.584159   0.528903     0.0     0.0           NaN        False                     NaN       0.0       0.0             NaN          False                       NaN        0.0        0.0              NaN           False                        NaN          3.0          1.0           0.426352             False                          1.0

,name,R@10,nDCG@5,nDCG@10,AP(rel=2),R@10 +,R@10 -,R@10 p-value,R@10 reject,R@10 p-value corrected,...,nDCG@10 +,nDCG@10 -,nDCG@10 p-value,nDCG@10 reject,nDCG@10 p-value corrected,AP(rel=2) +,AP(rel=2) -,AP(rel=2) p-value,AP(rel=2) reject,AP(rel=2) p-value corrected
0,MRL-64d,0.52684,0.589829,0.584159,0.527920,NaN,NaN,NaN,False,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,NaN
1,MRL-128d,0.52684,0.589829,0.584159,0.532478,0.0,0.0,NaN,False,NaN,...,0.0,0.0,NaN,False,NaN,2.0,2.0,0.308441,False,1.0
2,MRL-256d,0.52684,0.589829,0.584159,0.529362,0.0,0.0,NaN,False,NaN,...,0.0,0.0,NaN,False,NaN,2.0,2.0,0.406815,False,1.0
3,MRL-512d,0.52684,0.589829,0.584159,0.529436,0.0,0.0,NaN,False,NaN,...,0.0,0.0,NaN,False,NaN,2.0,2.0,0.295388,False,1.0
4,MRL-768d,0.52684,0.589829,0.584159,0.528903,0.0,0.0,NaN,False,NaN,...,0.0,0.0,NaN,False,NaN,3.0,1.0,0.426352,False,1.0

In [131]:
# ── RQ1 Table 6: MRL Dimensionality vs Performance ──
rq1_df = pd.read_csv('/kaggle/working/rq1_mrl_dims.csv')

print("Actual columns:", rq1_df.columns.tolist())  # debug: verify names

# Add storage column (% of full 768-dim)
rq1_df['dim']     = DIMS
rq1_df['storage'] = [f'{int(d/768*100)}%' for d in DIMS]

# Mark best row
best_ndcg = rq1_df['nDCG@10'].max()
rq1_df['best'] = rq1_df['nDCG@10'].apply(lambda x: '**' if x == best_ndcg else '')

print('\n=== TABLE 6: MRL Dimension Sweep ===')
# ← use actual column names from your CSV
print(rq1_df[['name','dim','nDCG@10','nDCG@5','AP(rel=2)','R@10','storage']].to_string(index=False))

rq1_df.to_csv('/kaggle/working/rq1_table6.csv', index=False)

Actual columns: ['name', 'R@10', 'nDCG@5', 'nDCG@10', 'AP(rel=2)', 'R@10 +', 'R@10 -', 'R@10 p-value', 'R@10 reject', 'R@10 p-value corrected', 'nDCG@5 +', 'nDCG@5 -', 'nDCG@5 p-value', 'nDCG@5 reject', 'nDCG@5 p-value corrected', 'nDCG@10 +', 'nDCG@10 -', 'nDCG@10 p-value', 'nDCG@10 reject', 'nDCG@10 p-value corrected', 'AP(rel=2) +', 'AP(rel=2) -', 'AP(rel=2) p-value', 'AP(rel=2) reject', 'AP(rel=2) p-value corrected']

=== TABLE 6: MRL Dimension Sweep ===
    name  dim  nDCG@10   nDCG@5  AP(rel=2)    R@10 storage
 MRL-64d   64 0.584159 0.589829   0.527920 0.52684      8%
MRL-128d  128 0.584159 0.589829   0.532478 0.52684     16%
MRL-256d  256 0.584159 0.589829   0.529362 0.52684     33%
MRL-512d  512 0.584159 0.589829   0.529436 0.52684     66%
MRL-768d  768 0.584159 0.589829   0.528903 0.52684    100%

In [133]:
# ── RQ1 Figure 1: nDCG@10 vs Embedding Dimension ──
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

rq1_df = pd.read_csv('/kaggle/working/rq1_table6.csv')

# Also load full CodeBERT (non-MRL) for flat reference line
# If you have it from Phase 3, load it; else use a placeholder
try:
    benchmark = pd.read_csv('/kaggle/working/benchmark_results.csv')
    codebert_ndcg = float(benchmark[benchmark['name']=='CodeBERT-base']['nDCG@10'].values[0])
except:
    codebert_ndcg = None   # skip reference line if not available

fig, ax = plt.subplots(figsize=(6, 4))

# MRL curve
ax.plot(rq1_df['dim'], rq1_df['nDCG@10'],
        marker='o', linewidth=2, color='#2ecc71', label='MRL-finetuned CodeBERT')

# CodeBERT-base flat reference line
if codebert_ndcg:
    ax.axhline(codebert_ndcg, linestyle='--', color='#e74c3c', linewidth=1.5,
               label=f'CodeBERT-base (768d) = {codebert_ndcg:.3f}')

# 5% drop zone
full_dim_ndcg = float(rq1_df[rq1_df['dim']==768]['nDCG@10'].values[0])
ax.axhspan(full_dim_ndcg * 0.95, full_dim_ndcg, alpha=0.08, color='green',
           label='<5% drop zone')

ax.set_xlabel('Embedding Dimension', fontsize=12)
ax.set_ylabel('nDCG@10', fontsize=12)
ax.set_title('RQ1: MRL Embedding Dimension vs Retrieval Performance', fontsize=11)
ax.set_xticks(rq1_df['dim'])
ax.legend(fontsize=9)
ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('/kaggle/working/rq1_figure1.pdf', bbox_inches='tight')
plt.savefig('/kaggle/working/rq1_figure1.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure saved to rq1_figure1.pdf and rq1_figure1.png')

Figure saved to rq1_figure1.pdf and rq1_figure1.png

In [132]:
# In the LaTeX table cell, change:
# MAP(rel=2) → AP(rel=2)
# Recall@10  → R@10

# In the RQ1 Answer cell, change:
rq1_df = pd.read_csv('/kaggle/working/rq1_table6.csv')
full   = rq1_df[rq1_df['dim']==768]['nDCG@10'].values[0]
best_reduced = rq1_df[rq1_df['dim']<768].sort_values('nDCG@10', ascending=False).iloc[0]

print(f"Full-dim (768d) nDCG@10  : {full:.4f}")
print(f"Best reduced dim         : {int(best_reduced['dim'])}d")
print(f"nDCG@10 at {int(best_reduced['dim'])}d          : {best_reduced['nDCG@10']:.4f}")
print(f"Performance retained     : {best_reduced['nDCG@10']/full*100:.1f}%")
print(f"Storage reduction        : {best_reduced['storage']}")

Full-dim (768d) nDCG@10  : 0.5842
Best reduced dim         : 64d
nDCG@10 at 64d          : 0.5842
Performance retained     : 100.0%
Storage reduction        : 8%

In [134]:
# ── RQ1 Answer ──
rq1_df = pd.read_csv('/kaggle/working/rq1_table6.csv')
full   = rq1_df[rq1_df['dim']==768]['nDCG@10'].values[0]
best_reduced = rq1_df[rq1_df['dim']<768].sort_values('nDCG@10', ascending=False).iloc[0]

print('='*55)
print('RQ1 ANSWER — MRL Embedding Efficiency')
print('='*55)
print(f"Full-dim (768d) nDCG@10  : {full:.4f}")
print(f"Best reduced dim         : {int(best_reduced['dim'])}d")
print(f"nDCG@10 at {int(best_reduced['dim'])}d          : {best_reduced['nDCG@10']:.4f}")
print(f"Performance retained     : {best_reduced['nDCG@10']/full*100:.1f}%")
print(f"Storage reduction        : {best_reduced['storage']}")
print()
print(f">> MRL retains {best_reduced['nDCG@10']/full*100:.1f}% of full-dim nDCG@10")
print(f"   at {int(best_reduced['dim'])}d ({best_reduced['storage']} storage), answering RQ1 affirmatively.")

=======================================================
RQ1 ANSWER — MRL Embedding Efficiency
=======================================================
Full-dim (768d) nDCG@10  : 0.5842
Best reduced dim         : 64d
nDCG@10 at 64d          : 0.5842
Performance retained     : 100.0%
Storage reduction        : 8%

>> MRL retains 100.0% of full-dim nDCG@10
   at 64d (8% storage), answering RQ1 affirmatively.

# Remaining Early works

In [21]:
model_name = "meta-llama/Llama-3.1-8B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token 
tokenizer.padding_side = "left"
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/826 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!
2026-03-28 18:40:24.480196: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774723224.877038      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774723224.978667      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774723225.863012      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774723225.863050      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774723225.863053      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774723225.863056      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

In [22]:
RELEVANCE_PROMPT = """You are an expert code relevance assessor for information retrieval research.

Task: Rate the relevance of a code snippet to a natural language query on a scale of 0-3.

Relevance Scale:
- 0: Not relevant - The code has no relation to the query
- 1: Marginally relevant - The code is tangentially related but does not answer the query
- 2: Relevant - The code partially addresses the query or provides related functionality
- 3: Highly relevant - The code directly and completely answers the query

Query: {query}

Code Snippet:
{code}

Instructions:
1. Analyze the semantic relationship between the query and code
2. Consider functionality, intent, and implementation details
3. Provide ONLY a single digit (0, 1, 2, or 3) as your response

Relevance Score:"""

In [23]:
def judge_relevance(queries, codes, batch_size=8):
    """Judge multiple query-code pairs in parallel"""
    
    results = []
    
    for i in range(0, len(queries), batch_size):
        batch_queries = queries[i:i+batch_size]
        batch_codes = codes[i:i+batch_size]
        
        prompts = [
            RELEVANCE_PROMPT.format(query=q, code=c[:1000])
            for q, c in zip(batch_queries, batch_codes)
        ]
        
        # Tokenize with padding
        inputs = tokenizer(
            prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=2048,
            return_attention_mask=True
        )
        
        # Move to device
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        
        # Generate
        with torch.no_grad():
            outputs = model.generate(
                input_ids=inputs['input_ids'],
                attention_mask=inputs['attention_mask'],
                max_new_tokens=5,
                temperature=0.1,
                do_sample=False,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id
            )
        
        # Decode
        for j, output in enumerate(outputs):
            input_length = inputs['input_ids'][j].shape[0]
            generated = output[input_length:]
            response = tokenizer.decode(generated, skip_special_tokens=True)
            
            try:
                score = int(response.strip()[0])
                if score not in [0, 1, 2, 3]:
                    score = 0
            except:
                score = 0
            
            results.append(score)
    
    return results

In [ ]:
qrels_8b = []
batch_size = 16  # Larger batch size for dual GPU

# Process each query
for idx, topic in tqdm(topics_df.iterrows(), total=len(topics_df), desc="Processing queries"):
    qid = topic['qid']
    query = topic['query']
    
    # Prepare batch: all documents for this query
    queries_batch = [query] * len(corpus)
    codes_batch = corpus['text'].tolist()
    
    # Judge all documents for this query in batches
    relevance_scores = judge_relevance(queries_batch, codes_batch, batch_size)
    
    # Store results
    for docno, relevance in zip(corpus['docno'], relevance_scores):
        qrels_8b.append({
            'qid': qid,
            'docno': docno,
            'relevance': relevance
        })
    
    # Save checkpoint every 10 queries
    if (idx + 1) % 10 == 0:
        checkpoint_df = pd.DataFrame(qrels_8b)
        checkpoint_df.to_csv(f'qrels_checkpoint_{idx+1}.csv', index=False)

print(f"\n Generated {len(qrels_8b)} relevance judgments")

Processing queries:  38%|███▊      | 8/21 [48:41<1:19:23, 366.44s/it]

In [24]:
qrels_df = pd.DataFrame(qrels_8b)

# TREC format: qid Q0 docno relevance
qrels_df['Q0'] = 0
qrels_df = qrels_df[['qid', 'Q0', 'docno', 'relevance']]
qrels_df

       qid  Q0  docno  relevance
0       q1   0      0          3
1       q1   0      1          2
2       q1   0      2          0
3       q1   0      3          0
4       q1   0      4          3
...    ...  ..    ...        ...
20995  q21   0    995          2
20996  q21   0    996          2
20997  q21   0    997          2
20998  q21   0    998          3
20999  q21   0    999          3

[21000 rows x 4 columns]

In [25]:
qrels_df.to_csv('/kaggle/working/qrels_8b.tsv', sep='\t', index=False, header=False)

- Now we will do it with 70b parameters

In [ ]:
model_name = "meta-llama/Llama-3.1-8B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token 
tokenizer.padding_side = "left"
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
)

In [ ]:
RELEVANCE_PROMPT = """You are an expert code relevance assessor for information retrieval research.

Task: Rate the relevance of a code snippet to a natural language query on a scale of 0-3.

Relevance Scale:
- 0: Not relevant - The code has no relation to the query
- 1: Marginally relevant - The code is tangentially related but does not answer the query
- 2: Relevant - The code partially addresses the query or provides related functionality
- 3: Highly relevant - The code directly and completely answers the query

Query: {query}

Code Snippet:
{code}

Instructions:
1. Analyze the semantic relationship between the query and code
2. Consider functionality, intent, and implementation details
3. Provide ONLY a single digit (0, 1, 2, or 3) as your response

Relevance Score:"""

In [ ]:
qrels_70b = []
batch_size = 16  # Larger batch size for dual GPU

# Process each query
for idx, topic in tqdm(topics_df.iterrows(), total=len(topics_df), desc="Processing queries"):
    qid = topic['qid']
    query = topic['query']
    
    # Prepare batch: all documents for this query
    queries_batch = [query] * len(corpus)
    codes_batch = corpus['text'].tolist()
    
    # Judge all documents for this query in batches
    relevance_scores = judge_relevance(queries_batch, codes_batch, batch_size)
    
    # Store results
    for docno, relevance in zip(corpus['docno'], relevance_scores):
        qrels_70b.append({
            'qid': qid,
            'docno': docno,
            'relevance': relevance
        })
    
    # Save checkpoint every 10 queries
    if (idx + 1) % 10 == 0:
        checkpoint_df = pd.DataFrame(qrels_70b)
        checkpoint_df.to_csv(f'qrels_checkpoint_{idx+1}.csv', index=False)

print(f"\n Generated {len(qrels_70b)} relevance judgments")

In [ ]:
qrels_df_70b = pd.DataFrame(qrels_70b)

# TREC format: qid Q0 docno relevance
qrels_df_70b['Q0'] = 0
qrels_df_70b = qrels_df_70b[['qid', 'Q0', 'docno', 'relevance']]
qrels_df_70b

In [ ]:
qrels_df_70b.to_csv('/kaggle/working/qrels_70b.tsv', sep='\t', index=False, header=False)

# codeDL analysis using colBERT

In [26]:
%pip install -q faiss-cpu pyterrier-dr

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 77.7 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.3/208.3 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 42.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 51.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 58.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 2.3 MB/s eta 0:00:00
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Building wheel for cbor (setup.py) ... done
Note: you may need to restart the kernel to use updated packages.

In [27]:
import pyterrier_dr

model = pyterrier_dr.TctColBert()

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/441M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [39]:
index = pyterrier_dr.FlexIndex('/kaggle/working/codedl.tctcolbert.flex')

In [41]:
corpus["docno"] = corpus["docno"].astype(str)

/tmp/ipykernel_55/3750218120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corpus["docno"] = corpus["docno"].astype(str)

In [44]:
idx_pipeline = model >> index
idx_pipeline.index(corpus.to_dict('records') )

indexing: 1000dvec [00:31, 32.23dvec/s]

FlexIndex('/kaggle/working/codedl.tctcolbert.flex')

In [45]:
retr_pipeline = model >> index.np_retriever()

In [49]:
%pip install -q python-terrier

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Note: you may need to restart the kernel to use updated packages.

In [52]:
qrels_df

       qid  Q0  docno  relevance
0       q1   0      0          3
1       q1   0      1          2
2       q1   0      2          0
3       q1   0      3          0
4       q1   0      4          3
...    ...  ..    ...        ...
20995  q21   0    995          2
20996  q21   0    996          2
20997  q21   0    997          2
20998  q21   0    998          3
20999  q21   0    999          3

[21000 rows x 4 columns]

In [55]:
qrels_df["qid"] = qrels_df["qid"].astype(str)
qrels_df["docno"] = qrels_df["docno"].astype(str)
qrels_df['Q0']=qrels_df['Q0'].astype(str)

In [57]:
topics_df

    qid                                              query
0    q1             Example usage of LangGraphAgentAdapter
1    q2                     Explain the capabilities logic
2    q3                             Example usage of serve
3    q4                        Best practices for ChatGroq
4    q5  How does TestResponseRewriting:\n    """Test r...
5    q6                 Example usage of truncate_messages
6    q7  Explain the async test_cache_streaming_list_wi...
7    q8  How does async test_selector_group_chat work i...
8    q9  Example usage of async test_pretty_run_result_...
9   q10                       Explain the StreamArgs logic
10  q11                       Best practices for page_down
11  q12  How to implement async test_buffered_model_con...
12  q13              Example usage of RoboflowProviderSpec
13  q14  How to implement TestRedactStrategy:\n    """T...
14  q15  Example usage of async test_api_failure_during...
15  q16            How to implement subscription_to_proto?
16  q17        Best practices for test_create_search_index
17  q18          Example usage of test_dynamic_model_basic
18  q19                      How to implement task_output?
19  q20  Example usage of async test_forcing_tool_use_b...
20  q21                   Example usage of generate_prompt

In [59]:
topics_df['qid']=topics_df['qid'].astype(str)

In [61]:
import pyterrier as pt
from pyterrier.measures import nDCG, MAP


result = pt.Experiment(
    [retr_pipeline],
    topics_df,
    qrels_df,
    eval_metrics=[nDCG@10, MAP(rel=2)],
    names=["tctColBERT"],
    filter_by_qrels=False,
    verbose=False
)

result

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 38.79docbatch/s]

         name  AP(rel=2)   nDCG@10
0  tctColBERT    0.59472  0.617437

In [67]:
codebert = pyterrier_dr.SBertBiEncoder("microsoft/codebert-base")

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name microsoft/codebert-base. Creating a new one with mean pooling.

In [70]:
codebert_index = pyterrier_dr.FlexIndex("/kaggle/working/codebert.flex")

indexing_pipeline = codebert >> codebert_index
indexing_pipeline.index(corpus.to_dict("records"))

indexing: 1000dvec [00:20, 48.22dvec/s]

FlexIndex('/kaggle/working/codebert.flex')

In [71]:
retr_pipeline = codebert >> index.np_retriever()

In [72]:
import pyterrier as pt
from pyterrier.measures import nDCG, MAP


result = pt.Experiment(
    [retr_pipeline],
    topics_df,
    qrels_df,
    eval_metrics=[nDCG@10, MAP(rel=2)],
    names=["codeBERT"],
    filter_by_qrels=False,
    verbose=False
)

result

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 378.17docbatch/s]

       name  AP(rel=2)   nDCG@10
0  codeBERT   0.523545  0.347075

In [73]:
finetuned_codebert = pyterrier_dr.SBertBiEncoder("shubharuidas/codebert-base-code-embed-mrl-langchain-langgraph")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/648 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

In [75]:
codebert_index = pyterrier_dr.FlexIndex("/kaggle/working/finetuned_codebert.flex")

indexing_pipeline = finetuned_codebert >> codebert_index
indexing_pipeline.index(corpus.to_dict("records"))

indexing: 1000dvec [00:20, 48.46dvec/s]

FlexIndex('/kaggle/working/finetuned_codebert.flex')

In [76]:
retr_pipeline = finetuned_codebert >> index.np_retriever()

In [78]:
import pyterrier as pt
from pyterrier.measures import nDCG, MAP


result = pt.Experiment(
    [retr_pipeline],
    topics_df,
    qrels_df,
    eval_metrics=[nDCG@10, MAP(rel=2)],
    names=["finetunedcodeBERT"],
    filter_by_qrels=False,
    verbose=False
)

result

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 499.38docbatch/s]

                name  AP(rel=2)   nDCG@10
0  finetunedcodeBERT   0.565216  0.482891

In [79]:
finetuned_codebert = pyterrier_dr.SBertBiEncoder("shubharuidas/codebert-embed-base-dense-retriever")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

WARNING:sentence_transformers.SentenceTransformer:You are trying to use a model that was created with Sentence Transformers version 5.2.0, but you're currently using version 5.1.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/648 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

In [80]:
codebert_index = pyterrier_dr.FlexIndex("/kaggle/working/finetuned_codebert2.flex")

indexing_pipeline = finetuned_codebert >> codebert_index
indexing_pipeline.index(corpus.to_dict("records"))

indexing: 1000dvec [00:20, 49.88dvec/s]

FlexIndex('/kaggle/working/finetuned_codebert2.flex')

In [81]:
retr_pipeline = finetuned_codebert >> index.np_retriever()

In [82]:
import pyterrier as pt
from pyterrier.measures import nDCG, MAP


result = pt.Experiment(
    [retr_pipeline],
    topics_df,
    qrels_df,
    eval_metrics=[nDCG@10, MAP(rel=2)],
    names=["finetunedcodeBERT"],
    filter_by_qrels=False,
    verbose=False
)

result

NumpyRetriever scoring: 100%|██████████| 1/1 [00:00<00:00, 1005.59docbatch/s]

                name  AP(rel=2)   nDCG@10
0  finetunedcodeBERT    0.55262  0.465302